### ISSUE TITLE
net.sf.json.JSONException: Object is null 

### ISSUE THREAD

**Issue by iamfeng** [alibaba/fastjson#1003]
fastjson 在静态方法 JSONObject.toJSONString(Object obj)
如果obj中存在map子对象，并且map子对象中 value为“null”字符串时，会报错“net.sf.json.JSONException: Object is null”
（目前在fastjson 版本1.1.41发现该问题）

net.sf.json.JSONException: Object is null
at net.sf.json.JSONNull.isEmpty(JSONNull.java:69) ~[json-lib-2.4-jdk15.jar:na]
at Serializer_77.write1(Unknown Source) ~[na:na]
at Serializer_77.write(Unknown Source) ~[na:na]
at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:188) ~[fastjson-1.1.41.jar:na]
at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:398) ~[fastjson-1.1.41.jar:na]
at Serializer_9.write1(Unknown Source) ~[na:na]
at Serializer_9.write(Unknown Source) ~[na:na]
at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:369) ~[fastjson-1.1.41.jar:na]
at com.alibaba.fastjson.JSON.toJSONString(JSON.java:418) ~[fastjson-1.1.41.jar:na]
at com.alibaba.fastjson.JSON.toJSONString(JSON.java:406) ~[fastjson-1.1.41.jar:na]
at com.alibaba.fastjson.JSON$toJSONString.call(Unknown Source) ~[na:na]
at

**Comment by wenshao** [comment]
为啥json-lib和fastjson混用？

**Comment by wuwen5** [comment]
和 #997  是重复的问题， 我觉得是json-lib的问题。

**Comment by wenshao** [comment]
已经支持，请用最新版1.2.24

**Comment by iamfeng** [comment]
OK 修复好了就好，json-lib fastjson 共用都应该没有问题。 这个“null” 如果是直接 stringSerializer 是不报错，只是在map下在调用 stringSerializer 才会报错。
