### ISSUE TITLE
object to json

### ISSUE THREAD

**Issue by fds2003** [alibaba/fastjson#1058]
java.lang.OutOfMemoryError: Java heap space
        at com.alibaba.fastjson.serializer.SerializeWriter.expandCapacity(SerializeWriter.java:203)
        at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:682)
        at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:605)
        at com.alibaba.fastjson.serializer.SerializeWriter.writeString(SerializeWriter.java:1463)
        at com.alibaba.fastjson.serializer.StringCodec.write(StringCodec.java:49)
        at com.alibaba.fastjson.serializer.StringCodec.write(StringCodec.java:34)
        at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:183)
        at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:369)
        at com.alibaba.fastjson.JSON.toJSONString(JSON.java:594)

fastjson-1.1.46.jar

**Comment by wenshao** [comment]
which version？

**Comment by wenshao** [comment]
Please upgrade to the new version. 
http://repo1.maven.org/maven2/com/alibaba/fastjson/1.2.24/
