### ISSUE TITLE
JSONObject.parseObject("中文",String.class)调用会导致crash问题

### ISSUE THREAD

**Issue by lightFuture1105** [alibaba/fastjson#1059]
在android中，出现`JSONObject.parseObject("中文",String.class)`这类调用，会导致app崩溃，最新版本的也会导致崩溃：

`  Caused by: com.alibaba.fastjson.JSONException: syntax error, pos 1, json : 中文
                                                     at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1436)
                                                     at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1355)
                                                     at com.alibaba.fastjson.parser.DefaultJSONParser.parseString(DefaultJSONParser.java:1530)
                                                     at com.alibaba.fastjson.serializer.StringCodec.deserialze(StringCodec.java:50)
                                                     at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:679)
                                                     at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:652)
                                                     at com.alibaba.fastjson.JSON.parseObject(JSON.java:218)`

而` Gson gson = new Gson(); gson.fromJson("中文",String.class);`则是ok的

**Comment by wenshao** [comment]
```java
JSON.parseObject("\"中文\"", String.class); 
```
试试看

**Comment by lightFuture1105** [comment]
@`JSON.parseObject("\"中文\"", String.class); `这样是ok的，但是服务器返回的数据可能就是字符串不带转义的`"`，只能要服务器端进行处理了吗。。。。可不可以有这种支持呢

**Comment by wenshao** [comment]
这个不是JSON格式哦，不好支持这个不是JSON格式哦，不好支持
