### ISSUE TITLE
ClassCastException 愁人的问题又来了 重启服务器容易出现 1.1.35

### ISSUE THREAD

**Issue by kingbo401** [alibaba/fastjson#107]
10:34:47.232][2013-11-07 10:34:47 232 ERROR] [resin-tcp-connection-_:8051-1] lang.throwable.NxErrorHandler - Unknown Error
[10:34:47.232]com.alibaba.fastjson.JSONException: write javaBean error
[10:34:47.232]  at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:212)
[10:34:47.232]  at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:369)
[10:34:47.232]  at com.alibaba.fastjson.JSON.toJSONString(JSON.java:414)
[10:34:47.232]  at com.nx.commons.lang.external.json.core.FastJsonSerializer.toJsonString(FastJsonSerializer.java:34)
[10:34:47.232]  at com.nx.commons.lang.external.json.JsonParser.toJsonString(JsonParser.java:47)
[10:34:47.232]  at com.nx.commons.server.logic.rest.RestLogicRouter.executeLogic(RestLogicRouter.java:65)
[10:34:47.232]  at com.nx.commons.server.logic.rest.RestLogicRouter.routeLogic(RestLogicRouter.java:40)
[10:34:47.232]  at com.nx.commons.server.servlet.NxRestServlet.executeServlet(NxRestServlet.java:38)
[10:34:47.232]  at com.nx.commons.server.servlet.NxServlet.doPost(NxServlet.java:61)
[10:34:47.232]  at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
[10:34:47.232]  at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
[10:34:47.232]  at com.caucho.server.dispatch.ServletFilterChain.doFilter(ServletFilterChain.java:106)
[10:34:47.232]  at com.caucho.server.cache.CacheFilterChain.doFilter(CacheFilterChain.java:188)
[10:34:47.232]  at com.caucho.server.webapp.WebAppFilterChain.doFilter(WebAppFilterChain.java:173)
[10:34:47.232]  at com.caucho.server.dispatch.ServletInvocation.service(ServletInvocation.java:229)
[10:34:47.232]  at com.caucho.server.http.HttpRequest.handleRequest(HttpRequest.java:274)
[10:34:47.232]  at com.caucho.server.port.TcpConnection.run(TcpConnection.java:511)
[10:34:47.232]  at com.caucho.util.ThreadPool.runTasks(ThreadPool.java:516)
[10:34:47.232]  at com.caucho.util.ThreadPool.run(ThreadPool.java:442)
[10:34:47.232]  at java.lang.Thread.run(Thread.java:662)
[10:34:47.232]Caused by: java.lang.ClassCastException: com.nx.service.uc.vo.CheckInfoVo cannot be cast to com.nx.commons.lang.service.uc.params.UserInfo
[10:34:47.232]  at Serializer_3.write1(Unknown Source)
[10:34:47.232]  at Serializer_3.write(Unknown Source)
[10:34:47.232]  at com.alibaba.fastjson.serializer.ObjectFieldSerializer.writeValue(ObjectFieldSerializer.java:115)
[10:34:47.232]  at com.alibaba.fastjson.serializer.ObjectFieldSerializer.writeProperty(ObjectFieldSerializer.java:68)
[10:34:47.232]  at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:194)
[10:34:47.232]  ... 19 more
[10:34:47.234][2013-11-07 10:34:47 234 INFO ] [resin-tcp-connection-_:8051-1] server.servlet.NxRestServlet - URI:/uc/v1/user/check_info cost 8 ms
[10:34:55.282][2013-11-07 10:34:55 281 ERROR] [resin-tcp-connection-*:8051-13] lang.throwable.NxErrorHandler - Unknown Error
[10:34:55.282]com.alibaba.fastjson.JSONException: write javaBean error
[10:34:55.282]  at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:212)
[10:34:55.282]  at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:369)
[10:34:55.282]  at com.alibaba.fastjson.JSON.toJSONString(JSON.java:414)
[10:34:55.282]  at com.nx.commons.lang.external.json.core.FastJsonSerializer.toJsonString(FastJsonSerializer.java:34)
[10:34:55.282]  at com.nx.commons.lang.external.json.JsonParser.toJsonString(JsonParser.java:47)
[10:34:55.282]  at com.nx.commons.server.logic.rest.RestLogicRouter.executeLogic(RestLogicRouter.java:65)
[10:34:55.282]  at com.nx.commons.server.logic.rest.RestLogicRouter.routeLogic(RestLogicRouter.java:40)
[10:34:55.282]  at com.nx.commons.server.servlet.NxRestServlet.executeServlet(NxRestServlet.java:38)
[10:34:55.282]  at com.nx.commons.server.servlet.NxServlet.doPost(NxServlet.java:61)
[10:34:55.282]  at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
[10:34:55.282]  at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
[10:34:55.282]  at com.caucho.server.dispatch.ServletFilterChain.doFilter(ServletFilterChain.java:106)
[10:34:55.282]  at com.caucho.server.cache.CacheFilterChain.doFilter(CacheFilterChain.java:188)
[10:34:55.282]  at com.caucho.server.webapp.WebAppFilterChain.doFilter(WebAppFilterChain.java:173)
[10:34:55.282]  at com.caucho.server.dispatch.ServletInvocation.service(ServletInvocation.java:229)
[10:34:55.282]  at com.caucho.server.http.HttpRequest.handleRequest(HttpRequest.java:274)
[10:34:55.282]  at com.caucho.server.port.TcpConnection.run(TcpConnection.java:511)
[10:34:55.282]  at com.caucho.util.ThreadPool.runTasks(ThreadPool.java:516)
[10:34:55.282]  at com.caucho.util.ThreadPool.run(ThreadPool.java:442)
[10:34:55.282]  at java.lang.Thread.run(Thread.java:662)
[10:34:55.282]Caused by: java.lang.ClassCastException: com.nx.service.uc.vo.CheckInfoVo cannot be cast to com.nx.commons.lang.service.uc.params.UserInfo
[10:34:55.282]  at Serializer_3.write1(Unknown Source)
[10:34:55.282]  at Serializer_3.write(Unknown Source)
[10:34:55.282]  at com.alibaba.fastjson.serializer.ObjectFieldSerializer.writeValue(ObjectFieldSerializer.java:115)
[10:34:55.282]  at com.alibaba.fastjson.serializer.ObjectFieldSerializer.writeProperty(ObjectFieldSerializer.java:68)
[10:34:55.282]  at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:194)
[10:34:55.282]  ... 19 more

**Comment by icanfly** [comment]
额，，，我也踩到这坑了，，版本:1.1.41 ，服务器报错：
Caused by: java.lang.ClassCastException: com.xxx.yyy.zzz cannot be cast to com.xxx.common.dto.pager.PagerData，而我返回的对象中根本就没有com.xxx.common.dto.pager.PagerData这个类信息。。。。报错得毫无根据。找了一天的问题。

应该早点上来找issue的 = =!
