### ISSUE TITLE
1.2.28反序列化类bug  java.lang.VerifyError:

### ISSUE THREAD

**Issue by renhongchao** [alibaba/fastjson#1081]
代码如下：  首先转换为字符串，然后反序列化报错
TopicVO vo = new TopicVO();
vo.setTopicid("sdf");
String str = JSON.toJSONString(vo);
TopicVO v2 = JSON.parseObject(str, TopicVO.class);

Exception in thread "main" java.lang.VerifyError: (class: com/alibaba/fastjson/parser/deserializer/FastjsonASMDeserializer_1_TopicVO, method: deserialze signature: (Lcom/alibaba/fastjson/parser/DefaultJSONParser;Ljava/lang/reflect/Type;Ljava/lang/Object;I)Ljava/lang/Object;) Accessing value from uninitialized register 52
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2585)
	at java.lang.Class.getConstructor0(Class.java:2885)
	at java.lang.Class.getConstructor(Class.java:1723)
	at com.alibaba.fastjson.parser.deserializer.ASMDeserializerFactory.createJavaBeanDeserializer(ASMDeserializerFactory.java:82)
	at com.alibaba.fastjson.parser.ParserConfig.createJavaBeanDeserializer(ParserConfig.java:639)
	at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:491)
	at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:348)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:639)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:350)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:254)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:467)

**Comment by 240668488** [comment]
+10086
错误一模一样
没找到原因是为啥

**Comment by 240668488** [comment]
我的调用代码如下
JSONArray.parseArray(xxxString, Xxx.class);
但报的错一模一样。

**Comment by wenshao** [comment]
1.2.29修复过一个这样的问题，帮忙试一下1.2.29是否还有这个问题。
http://repo1.maven.org/maven2/com/alibaba/fastjson/1.2.29/

**Comment by renhongchao** [comment]
1.2.29测试没发现这个问题  多谢

**Comment by 240668488** [comment]
经验证，修复无误。

**Comment by smallCC** [comment]
it works
