### ISSUE TITLE
toJsonString 返回异常,包含	"user":{"$ref":"$.admin"}

### ISSUE THREAD

**Issue by GuChuan** [alibaba/fastjson#1121]
```
JSONObject userObject = new JSONObject();
        userObject.put("name","jack");
        userObject.put("age",20);
        JSONObject result = new JSONObject();
        result.put("host","127.0.0.1");
        result.put("port",3306);
        result.put("user",userObject);
        result.put("admin",userObject);
```

调用
```
String objJson = JSON.toJSONString(result,true);
```

```
{
	"port":3306,
	"host":"127.0.0.1",
	"admin":{
		"name":"jack",
		"age":20
	},
	"user":{"$ref":"$.admin"}
}%
```

**Comment by wenshao** [comment]
我测试是好的哈，你什么版本？

**Comment by wenshao** [comment]
```java
JSON.toJSONString(result, SerializerFeature.PrettyFormat, SerializerFeature.DisableCircularReferenceDetect);
```

**Comment by GuChuan** [comment]
我的版本      
  <fastjson.version>1.2.22</fastjson.version>

**Comment by GuChuan** [comment]
JSON.toJSONString(result, SerializerFeature.PrettyFormat, SerializerFeature.DisableCircularReferenceDetect); 有这几个参数的说明文档吗？

**Comment by ustcstar06** [comment]
1.2.28也有类似问题

**Comment by wenshao** [comment]
@GuChuan 
PrettyFormat 的介绍 https://github.com/alibaba/fastjson/wiki/SerializerFeature_PrettyFormat_cn

**Comment by javapriyan** [comment]
Adding the , SerializerFeature.PrettyFormat, SerializerFeature.DisableCircularReferenceDetect causing the below error. In my case, 

class A{
A a;
}

A aa = new A();

a !=aa


Exception in thread "main" java.lang.StackOverflowError
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:103)
	at Serializer_1.write1(Unknown Source)
	at Serializer_1.write(Unknown Source)
	at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:84)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:189)
	at com.alibaba.fastjson.serializer.ObjectFieldSerializer.writeValue(ObjectFieldSerializer.java:129)
	at com.alibaba.fastjson.serializer.ObjectFieldSerializer.writeProperty(ObjectFieldSerializer.java:70)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:235)
	at Serializer_1.write1(Unknown Source)
