### ISSUE TITLE
1.2.30 版本 在三星note3上解析空数组 异常  突然出现的问题 其他手机没有  

### ISSUE THREAD

**Issue by MrYang12** [alibaba/fastjson#1131]
Caused by: java.lang.IllegalArgumentException: argument 1 should have type java.lang.String[], got byte[]

private DecorationData[] used_decoration;//对象里面的

"used_decoration": [],//服务端下发的

**Comment by wenshao** [comment]
android应该用android版本啊，比如 http://repo1.maven.org/maven2/com/alibaba/fastjson/1.1.56.android/

另外这个错误信息看不出问题，能够提供更多的错误堆栈信息么？

**Comment by MrYang12** [comment]
（"tag_prefer": "", "used_decoration": [],//服务端下发数据的一部分   正常的json）我把对象中的 “used_decoration” 这个字段去掉也会出现同样的错误  ,而且这个问题  目前的话 正好是在三星note3上发现的  其他机型没有问题。“used_decoration” 该字段返回的是对象数组。


exepct '[', but string, type : class com.mengjun.DanNovel.task.data.common.ReaderInfo
                                                                com.alibaba.fastjson.JSONException: exepct '[', but string, type : class com.mengjun.DanNovel.task.data.common.ReaderInfo
                                                                    at com.alibaba.fastjson.parser.ListTypeFieldDeserializer.parseArray(ListTypeFieldDeserializer.java:162)
                                                                    at com.alibaba.fastjson.parser.ListTypeFieldDeserializer.parseField(ListTypeFieldDeserializer.java:63)
                                                                    at com.alibaba.fastjson.parser.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:874)
                                                                    at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:695)
                                                                    at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:95)
                                                                    at com.alibaba.fastjson.parser.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:45)
                                                                    at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:642)
                                                                    at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:95)
                                                                    at com.alibaba.fastjson.parser.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:45)
                                                                    at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:642)
                                                                    at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:95)
                                                                    at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:679)
                                                                    at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:652)
                                                                    at com.alibaba.fastjson.JSON.parseObject(JSON.java:218)
                                                                    at com.alibaba.fastjson.JSON.parseObject(JSON.java:190)
                                                                    at com.alibaba.fastjson.JSON.parseObject(JSON.java:149)
                                                                    at com.alibaba.fastjson.JSON.parseObject(JSON.java:258)

**Comment by MrYang12** [comment]
谢谢答疑  不过依然有问题  版本已经替换过了
