### ISSUE TITLE
JSONField 反序列化iso-8601日期格式“0001-01-01T00:00:00”失败

### ISSUE THREAD

**Issue by fi5** [alibaba/fastjson#1152]
@wenshao 
JSONField 反序列化iso-8601日期格式“0001-01-01T00:00:00”异常，试了一下小于“1000-01-01T00:00:00”这个时间就异常，否则可以成功。
小于“1000-01-01T00:00:00”的结果：
`Exception in thread "main" com.alibaba.fastjson.JSONException: For input string: "0001-01-01T00:00:00"
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:646)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:350)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:254)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:467)
	at com.credfin.test0.main(test0.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.NumberFormatException: For input string: "0001-01-01T00:00:00"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Long.parseLong(Long.java:419)
	at java.lang.Long.parseLong(Long.java:468)
	at com.alibaba.fastjson.serializer.DateCodec.cast(DateCodec.java:202)
	at com.alibaba.fastjson.parser.deserializer.AbstractDateDeserializer.deserialze(AbstractDateDeserializer.java:142)
	at com.alibaba.fastjson.parser.deserializer.AbstractDateDeserializer.deserialze(AbstractDateDeserializer.java:19)
	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:71)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:828)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:630)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:1010)
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_1_TestBean.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:208)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:642)
	... 9 more
`
大于等于“1000-01-01T00:00:00”的结果：
`1000-01-01 00:00:00`

目前通过自定义反序列化deserializeUsing解决，但是不知道以上情况算不算bug.

测试代码：
```java
public class TestBean {

    private Date shijian;

    public Date getShijian() {
        return shijian;
    }
    @JSONField(name="shijian" )
    public void setShijian(Date shijian) {
        this.shijian = shijian;
    }
}

public class test0 {

    public static void main(String[] args){
        TestBean tb = JSONObject.parseObject("{shijian:\"1000-01-01T00:00:00\"}",TestBean.class);
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        System.out.println(sdf.format(tb.getShijian()));
    }
}
```

**Comment by wenshao** [comment]
故意报错的，因为这个不是一个合法的日期

**Comment by linxingyulxy** [comment]
请教要写自定义的deserializeUsing 要实现哪个接口呢？

**Comment by wenshao** [comment]
com.alibaba.fastjson.parser.deserializer.ObjectDeserializer

**Comment by accphuangxin** [comment]
我们也遇到此问题，我是如下解决的：修改了DateCodec类 的cast()方法中字符串转为Date 基于jodo-time处理。
ParserConfig parserConfig = new ParserConfig();
parserConfig.putDeserializer(Date.class, com.hujiang.xxx.DateCodec.instance);
JSON.parseObject("{\"dateadded\":\"0001-01-01T00:00:00+08:00\"}", BookConfig.class, parserConfig);

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.33
已经发布新版本支持，请使用新版本验证是否解决你的问题，谢谢。
