### ISSUE TITLE
unclosed str, pos XXXX

### ISSUE THREAD

**Issue by liungkejin** [alibaba/fastjson#1162]
在我们应用中，偶尔会出现这个错误，我们的json 里面包含 Unicode 编码
```
04-20 20:13:15.733  8782  8837 W System.err: com.alibaba.fastjson.JSONException: unclosed str, pos 1380, json : {"face":[{"icon":"a_facetheme_20161019135730.png","iconHover":"a_facetheme_hover_20161019135730.png","label":"\u8138\u578b","label_en":"Face","label_zh_tw":"\u81c9\u578b","name":"a_facetheme","components":[{"name":"face_theme_nothing","label":"\u539f\u56fe","label_en":"Normal","label_zh_tw":"\u539f\u5716","icon":"face_theme_nothing_20161219204033.png","package":"","date":""},{"name":"face_theme_yushe","label":"\u9884\u8bbe","label_en":"Star","label_zh_tw":"\u9810\u8a2d","icon":"face_theme_yushe_20161219204042.png","package":"","date":""},{"name":"face_theme1","label":"\u7f8e\u80a4","label_en":"Beauty","label_zh_tw":"\u7f8e\u819a","icon":"face_theme1_20161219203739.png","package":"face_theme1_20170419105706.zip","date":"20170419105706"},{"name":"face_theme2","label":"\u5929\u7136","label_en":"Natural","label_zh_tw":"\u5929\u7136","icon":"face_theme2_20161219203913.png","package":"face_theme2_20170419105715.zip","date":"20170419105715"},{"name":"face_theme3","label":"\u5a03\u5a03","label_en":"Baby","label_zh_tw":"\u5a03\u5a03","icon":"face_theme3_20161219203923.png","package":"face_theme3_20170419105722.zip","date":"20170419105722"},{"name":"face_theme4","label":"\u9e45\u86cb","label_en":"Goose","label_zh_tw":"\u9e45\u86cb","icon":"face_theme4_20161219203930.png","package":"face_theme4_20170419105728.zip","date":"20170419105728"},{"name":"face_theme5","label":"\u
04-20 20:13:15.733  8782  8837 W System.err: 	at com.alibaba.fastjson.parser.JSONLexer.scanStringValue(JSONLexer.java:1062)
04-20 20:13:15.733  8782  8837 W System.err: 	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:432)
04-20 20:13:15.733  8782  8837 W System.err: 	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1235)
04-20 20:13:15.733  8782  8837 W System.err: 	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:467)
04-20 20:13:15.733  8782  8837 W System.err: 	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1235)
04-20 20:13:15.733  8782  8837 W System.err: 	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:467)
04-20 20:13:15.733  8782  8837 W System.err: 	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1378)
04-20 20:13:15.733  8782  8837 W System.err: 	at com.alibaba.fastjson.JSON.parse(JSON.java:103)
04-20 20:13:15.733  8782  8837 W System.err: 	at com.alibaba.fastjson.JSON.parse(JSON.java:94)
04-20 20:13:15.733  8782  8837 W System.err: 	at com.benqu.serverside.model.ApiModelBase.setData(ApiModelBase.java:28)
04-20 20:13:15.733  8782  8837 W System.err: 	at com.benqu.serverside.model.ApiModelBase.<init>(ApiModelBase.java:19)
04-20 20:13:15.733  8782  8837 W System.err: 	at com.benqu.serverside.model.componenttree.ApiModelComponentTree.<init>(ApiModelComponentTree.java:28)
04-20 20:13:15.733  8782  8837 W System.err: 	at java.lang.reflect.Constructor.newInstance(Native Method)
04-20 20:13:15.733  8782  8837 W System.err: 	at com.benqu.serverside.controller.apis.ApiBase$3.run(ApiBase.java:133)
04-20 20:13:15.734  8782  8837 W System.err: 	at java.lang.Thread.run(Thread.java:833)
```

**Comment by liungkejin** [comment]
是我的问题，不好意思
