### ISSUE TITLE
Attempt to read from null array

### ISSUE THREAD

**Issue by shangmingchao** [alibaba/fastjson#1167]
版本：fastjson-1.2.7.jar  
问题描述：偶然出现下面这样的错误反馈：
```
Caused by: java.lang.NullPointerException: Attempt to read from null array
	at com.alibaba.fastjson.parser.SymbolTable.addSymbol(SymbolTable.java:144)
	at com.alibaba.fastjson.parser.JSONScanner.addSymbol(JSONScanner.java:157)
	at com.alibaba.fastjson.parser.JSONLexerBase.scanSymbol(JSONLexerBase.java:826)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:220)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1236)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1205)
	at com.alibaba.fastjson.parser.deserializer.StringFieldDeserializer.parseField(StringFieldDeserializer.java:32)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:420)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:330)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:135)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)
	... 12 more
com.alibaba.fastjson.JSONException: Attempt to read from null array
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:555)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:251)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:227)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:186)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:304)
	at xxx.xxx.xxx
	at android.os.AsyncTask$2.call(AsyncTask.java:307)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:833)
```
但一直没有办法复现，请问什么情况下的json解析会出现这样的错误？是json格式不规范还是fastjson解析的bug？有什么措施可以避免这种错误出现？

**Comment by wenshao** [comment]
什么版本？

**Comment by shangmingchao** [comment]
嗯，好的，谢谢。
