### ISSUE TITLE
android 调用 JSON.parseObject 。FastJson内部调用 String 类 API 出现JNI Crash 

### ISSUE THREAD

**Issue by GYGG** [alibaba/fastjson#1168]
我的应用调用 JSON.parseObject 的时候出现了一个 Native 的 Crash 。估计跟FastJson 中的 JSONScanner 使用 String 的方式有关系。
下面附上我崩溃时的 java stack 以及 ndk stack

```
04-26 22:11:43.247 9417-9413/? E/DEBUG: all threads dump:
04-26 22:11:43.247 9417-9413/? E/DEBUG: [DEBUG] enter dumpAllThreadsIntoFileFunc, fd: 56, overridedMalloc: 0
04-26 22:11:43.248 9417-9413/? E/DEBUG: [DEBUG] dumpDvmThreads, fd: 56
04-26 22:11:43.248 9417-9413/? E/DEBUG: [DEBUG] dvmDumpAllThreadsEx: 0x0
04-26 22:11:43.248 9417-9413/? E/DEBUG: [DEBUG] dvmDumpAllThreadsEx-2: 0x0
04-26 22:11:43.249 9417-9413/? E/DEBUG: Crash thread java stack trace:
04-26 22:11:43.249 9417-9413/? E/DEBUG:     at com.alibaba.fastjson.parser.JSONScanner.subString(JSONScanner.java:130)
04-26 22:11:43.250 9417-9413/? E/DEBUG:     at com.alibaba.fastjson.parser.JSONScanner.scanFieldString(JSONScanner.java:794)
04-26 22:11:43.251 9417-9413/? E/DEBUG:     at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:388)
04-26 22:11:43.251 9417-9413/? E/DEBUG:     at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:188)
04-26 22:11:43.252 9417-9413/? E/DEBUG:     at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:184)
04-26 22:11:43.252 9417-9413/? E/DEBUG:     at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:642)
04-26 22:11:43.253 9417-9413/? E/DEBUG:     at com.alibaba.fastjson.JSON.parseObject(JSON.java:350)
04-26 22:11:43.253 9417-9413/? E/DEBUG:     at com.alibaba.fastjson.JSON.parseObject(JSON.java:318)
04-26 22:11:43.254 9417-9413/? E/DEBUG:     at com.alibaba.fastjson.JSON.parseObject(JSON.java:281)
04-26 22:11:43.254 9417-9413/? E/DEBUG:     at com.alibaba.fastjson.JSON.parseObject(JSON.java:381)
04-26 22:11:43.255 9417-9413/? E/DEBUG:     at com.alibaba.fastjson.JSON.parseObject(JSON.java:361)

```

```
********** Crash dump: **********
Build fingerprint: ''
pid: 12858, tid: 13061  >>> [我的包名]<<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000004
Stack frame #00  pc 000eb5e4  /system/lib/libart.so (_ZNSt3__1lsINS_11char_traitsIcEEEERNS_13basic_ostreamIcT_EES6_PKc)
Stack frame #01  pc 001ec564  /system/lib/libart.so (_ZN3art11interpreter10DoFieldPutILNS_13FindFieldTypeE3ELNS_9Primitive4TypeE6ELb1ELb0EEEbPNS_6ThreadERKNS_11ShadowFrameEPKNS_11InstructionEt)
Stack frame #02  pc 001ec5d2  /system/lib/libart.so (_ZN3art11interpreter10DoFieldPutILNS_13FindFieldTypeE3ELNS_9Primitive4TypeE6ELb1ELb0EEEbPNS_6ThreadERKNS_11ShadowFrameEPKNS_11InstructionEt)
Stack frame #03  pc 001ecacc  /system/lib/libart.so (_ZN3art11interpreter10DoFieldGetILNS_13FindFieldTypeE4ELNS_9Primitive4TypeE0ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEt)
Stack frame #04  pc 000b2b3a  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb1ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_)
Stack frame #05  pc 001d2b0c  /system/lib/libart.so (_ZN3art5hprof8DumpHeapEPKcib)
Stack frame #06  pc 001ec760  /system/lib/libart.so (_ZN3art11interpreter10DoFieldGetILNS_13FindFieldTypeE2ELNS_9Primitive4TypeE6ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEt)
Stack frame #07  pc 001ee904  /system/lib/libart.so (_ZN3art11interpreter10DoFieldGetILNS_13FindFieldTypeE6ELNS_9Primitive4TypeE6ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEt)
Stack frame #08  pc 000b2c72  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb1ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_)
Stack frame #09  pc 001d2b0c  /system/lib/libart.so (_ZN3art5hprof8DumpHeapEPKcib)
Stack frame #10  pc 001ec760  /system/lib/libart.so (_ZN3art11interpreter10DoFieldGetILNS_13FindFieldTypeE2ELNS_9Primitive4TypeE6ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEt)
Stack frame #11  pc 001ee904  /system/lib/libart.so (_ZN3art11interpreter10DoFieldGetILNS_13FindFieldTypeE6ELNS_9Primitive4TypeE6ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEt)
Stack frame #12  pc 000b2c72  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb1ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_)
Stack frame #13  pc 001d2b0c  /system/lib/libart.so (_ZN3art5hprof8DumpHeapEPKcib)
Stack frame #14  pc 001ed622  /system/lib/libart.so (_ZN3art11interpreter10DoFieldGetILNS_13FindFieldTypeE6ELNS_9Primitive4TypeE5ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEt)
Stack frame #15  pc 001f1ac2  /system/lib/libart.so (_ZNSt3__16__treeINS_12__value_typeIPN3art6mirror6ObjectENS2_11Transaction9ObjectLogEEENS_19__map_value_compareIS5_S8_NS_4lessIS5_EELb1EEENS_9allocatorIS8_EEE7destroyEPNS_11__tree_nodeIS8_PvEE)
Stack frame #16  pc 000b2c20  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb1ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_)
Stack frame #17  pc 001d2b0c  /system/lib/libart.so (_ZN3art5hprof8DumpHeapEPKcib)
Stack frame #18  pc 001ec760  /system/lib/libart.so (_ZN3art11interpreter10DoFieldGetILNS_13FindFieldTypeE2ELNS_9Primitive4TypeE6ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEt)
Stack frame #19  pc 001ee904  /system/lib/libart.so (_ZN3art11interpreter10DoFieldGetILNS_13FindFieldTypeE6ELNS_9Primitive4TypeE6ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEt)
Stack frame #20  pc 000b2c72  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb1ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_)
Stack frame #21  pc 001d2b0c  /system/lib/libart.so (_ZN3art5hprof8DumpHeapEPKcib)
Stack frame #22  pc 001ec760  /system/lib/libart.so (_ZN3art11interpreter10DoFieldGetILNS_13FindFieldTypeE2ELNS_9Primitive4TypeE6ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEt)
Stack frame #23  pc 001f0518  /system/lib/libart.so (_ZN3art11interpreter10DoFieldPutILNS_13FindFieldTypeE7ELNS_9Primitive4TypeE2ELb1ELb1EEEbPNS_6ThreadERKNS_11ShadowFrameEPKNS_11InstructionEt)
Stack frame #24  pc 000b27ba  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb1ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_)
Stack frame #25  pc 001d2b0c  /system/lib/libart.so (_ZN3art5hprof8DumpHeapEPKcib)
Stack frame #26  pc 001ec760  /system/lib/libart.so (_ZN3art11interpreter10DoFieldGetILNS_13FindFieldTypeE2ELNS_9Primitive4TypeE6ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEt)
Stack frame #27  pc 001ee904  /system/lib/libart.so (_ZN3art11interpreter10DoFieldGetILNS_13FindFieldTypeE6ELNS_9Primitive4TypeE6ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEt)
Stack frame #28  pc 000b2c72  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb1ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_)
Stack frame #29  pc 001d2b0c  /system/lib/libart.so (_ZN3art5hprof8DumpHeapEPKcib)
Stack frame #30  pc 001ed622  /system/lib/libart.so (_ZN3art11interpreter10DoFieldGetILNS_13FindFieldTypeE6ELNS_9Primitive4TypeE5ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEt)
Stack frame #31  pc 000b2546  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb1ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_)
Stack frame #32  pc 001d2b0c  /system/lib/libart.so (_ZN3art5hprof8DumpHeapEPKcib)
Stack frame #33  pc 001ec760  /system/lib/libart.so (_ZN3art11interpreter10DoFieldGetILNS_13FindFieldTypeE2ELNS_9Primitive4TypeE6ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEt)
Stack frame #34  pc 000b271e  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb1ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_)
Stack frame #35  pc 001d2b0c  /system/lib/libart.so (_ZN3art5hprof8DumpHeapEPKcib)
Stack frame #36  pc 001ec760  /system/lib/libart.so (_ZN3art11interpreter10DoFieldGetILNS_13FindFieldTypeE2ELNS_9Primitive4TypeE6ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEt)
Stack frame #37  pc 000b271e  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb1ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_)
Stack frame #38  pc 001d2b0c  /system/lib/libart.so (_ZN3art5hprof8DumpHeapEPKcib)
Stack frame #39  pc 001ed622  /system/lib/libart.so (_ZN3art11interpreter10DoFieldGetILNS_13FindFieldTypeE6ELNS_9Primitive4TypeE5ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEt)
Stack frame #40  pc 000b2546  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb1ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_)
Stack frame #41  pc 001d2b0c  /system/lib/libart.so (_ZN3art5hprof8DumpHeapEPKcib)
Stack frame #42  pc 001ec760  /system/lib/libart.so (_ZN3art11interpreter10DoFieldGetILNS_13FindFieldTypeE2ELNS_9Primitive4TypeE6ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEt)
Stack frame #43  pc 000b271e  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb1ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_)
Stack frame #44  pc 001d2b0c  /system/lib/libart.so (_ZN3art5hprof8DumpHeapEPKcib)
Stack frame #45  pc 001ec760  /system/lib/libart.so (_ZN3art11interpreter10DoFieldGetILNS_13FindFieldTypeE2ELNS_9Primitive4TypeE6ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEt)
Stack frame #46  pc 000b271e  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb1ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_)
Stack frame #47  pc 001d2b0c  /system/lib/libart.so (_ZN3art5hprof8DumpHeapEPKcib)
Stack frame #48  pc 001ec760  /system/lib/libart.so (_ZN3art11interpreter10DoFieldGetILNS_13FindFieldTypeE2ELNS_9Primitive4TypeE6ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEt)
Stack frame #49  pc 000b271e  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb1ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_)
Stack frame #50  pc 001d28e4  /system/lib/libart.so (_ZN3art5hprof8DumpHeapEPKcib)
Stack frame #51  pc 003d8e5a  /system/lib/libart.so (artAllocStringFromBytesFromCodeRegionTLAB)
Stack frame #52  pc 000dc732  /system/lib/libart.so (_ZN3art11interpreter17ExecuteSwitchImplILb0ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_)
Crash dump is completed

********** Crash dump: **********
Build fingerprint: 'google/bullhead/bullhead:6.0.1/MTC19T/2741993:user/release-keys'
pid: 12858, tid: 13061, name: MTOPSDK Callbac  >>> com.cainiao.apanti.android.mirror <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4
Stack frame #00 pc 000f95e4  /system/lib/libart.so (_ZNSt3__127__tree_balance_after_insertIPNS_16__tree_node_baseIPvEEEEvT_S5_+143)
Stack frame #01 pc 001fa565  /system/lib/libart.so (_ZNSt3__16__treeINS_12__value_typeIN3art15MethodReferenceENS2_7SafeMapIjNS_3setIjNS_4lessIjEENS_9allocatorIjEEEES7_NS2_17TrackingAllocatorINS_4pairIKjSA_EELNS2_12AllocatorTagE6EEEEEEENS_19__map_value_compareIS3_SI_NS2_25MethodReferenceComparatorELb1EEENS8_ISI_EEE15__insert_uniqueINSC_IS3_SH_EEEENSC_INS_15__tree_iteratorISI_PNS_11__tree_nodeISI_PvEEiEEbEEOT_+216)
Stack frame #02 pc 001fa5d3  /system/lib/libart.so (_ZN3art7SafeMapINS_15MethodReferenceENS0_IjNSt3__13setIjNS2_4lessIjEENS2_9allocatorIjEEEES5_NS_17TrackingAllocatorINS2_4pairIKjS8_EELNS_12AllocatorTagE6EEEEENS_25MethodReferenceComparatorENS9_INSA_IKS1_SF_EELSD_6EEEE9OverwriteERSH_RKSF_+78)
Stack frame #03 pc 001faacd  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+1208)
Stack frame #04 pc 000c0b3b  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb0ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_+27178)
Stack frame #05 pc 001e0b0d  /system/lib/libart.so (artInterpreterToInterpreterBridge+120)
Stack frame #06 pc 001fa761  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+332)
Stack frame #07 pc 001fc905  /system/lib/libart.so (_ZN3art11interpreterL8DoInvokeILNS_10InvokeTypeE2ELb0ELb0EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+192)
Stack frame #08 pc 000c0c73  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb0ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_+27490)
Stack frame #09 pc 001e0b0d  /system/lib/libart.so (artInterpreterToInterpreterBridge+120)
Stack frame #10 pc 001fa761  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+332)
Stack frame #11 pc 001fc905  /system/lib/libart.so (_ZN3art11interpreterL8DoInvokeILNS_10InvokeTypeE2ELb0ELb0EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+192)
Stack frame #12 pc 000c0c73  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb0ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_+27490)
Stack frame #13 pc 001e0b0d  /system/lib/libart.so (artInterpreterToInterpreterBridge+120)
Stack frame #14 pc 001fb623  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb1ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+302)
Stack frame #15 pc 001ffac3  /system/lib/libart.so (_ZN3art11interpreterL8DoInvokeILNS_10InvokeTypeE2ELb1ELb0EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+182)
Stack frame #16 pc 000c0c21  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb0ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_+27408)
Stack frame #17 pc 001e0b0d  /system/lib/libart.so (artInterpreterToInterpreterBridge+120)
Stack frame #18 pc 001fa761  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+332)
Stack frame #19 pc 001fc905  /system/lib/libart.so (_ZN3art11interpreterL8DoInvokeILNS_10InvokeTypeE2ELb0ELb0EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+192)
Stack frame #20 pc 000c0c73  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb0ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_+27490)
Stack frame #21 pc 001e0b0d  /system/lib/libart.so (artInterpreterToInterpreterBridge+120)
Stack frame #22 pc 001fa761  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+332)
Stack frame #23 pc 001fe519  /system/lib/libart.so (_ZN3art11interpreterL8DoInvokeILNS_10InvokeTypeE4ELb0ELb0EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+524)
Stack frame #24 pc 000c07bb  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb0ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_+26282)
Stack frame #25 pc 001e0b0d  /system/lib/libart.so (artInterpreterToInterpreterBridge+120)
Stack frame #26 pc 001fa761  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+332)
Stack frame #27 pc 001fc905  /system/lib/libart.so (_ZN3art11interpreterL8DoInvokeILNS_10InvokeTypeE2ELb0ELb0EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+192)
Stack frame #28 pc 000c0c73  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb0ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_+27490)
Stack frame #29 pc 001e0b0d  /system/lib/libart.so (artInterpreterToInterpreterBridge+120)
Stack frame #30 pc 001fb623  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb1ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+302)
Stack frame #31 pc 000c0547  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb0ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_+25654)
Stack frame #32 pc 001e0b0d  /system/lib/libart.so (artInterpreterToInterpreterBridge+120)
Stack frame #33 pc 001fa761  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+332)
Stack frame #34 pc 000c071f  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb0ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_+26126)
Stack frame #35 pc 001e0b0d  /system/lib/libart.so (artInterpreterToInterpreterBridge+120)
Stack frame #36 pc 001fa761  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+332)
Stack frame #37 pc 000c071f  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb0ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_+26126)
Stack frame #38 pc 001e0b0d  /system/lib/libart.so (artInterpreterToInterpreterBridge+120)
Stack frame #39 pc 001fb623  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb1ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+302)
Stack frame #40 pc 000c0547  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb0ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_+25654)
Stack frame #41 pc 001e0b0d  /system/lib/libart.so (artInterpreterToInterpreterBridge+120)
Stack frame #42 pc 001fa761  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+332)
Stack frame #43 pc 000c071f  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb0ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_+26126)
Stack frame #44 pc 001e0b0d  /system/lib/libart.so (artInterpreterToInterpreterBridge+120)
Stack frame #45 pc 001fa761  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+332)
Stack frame #46 pc 000c071f  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb0ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_+26126)
Stack frame #47 pc 001e0b0d  /system/lib/libart.so (artInterpreterToInterpreterBridge+120)
Stack frame #48 pc 001fa761  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+332)
Stack frame #49 pc 000c071f  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb0ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_+26126)
Stack frame #50 pc 001e08e5  /system/lib/libart.so (_ZN3art11interpreter30EnterInterpreterFromEntryPointEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameE+84)
Stack frame #51 pc 003e6e5b  /system/lib/libart.so (artQuickToInterpreterBridge+546)
Stack frame #52 pc 000ea733  /system/lib/libart.so (art_quick_to_interpreter_bridge+34)
Stack frame #53 pc 000e5fc1  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
Stack frame #54 pc 003e8807  /system/lib/libart.so (art_quick_invoke_stub+170)
Stack frame #55 pc 00100114  [stack:13061]
```

**Comment by wenshao** [comment]
什么版本？

**Comment by GYGG** [comment]
@wenshao 
下面两个都试过，都有：
```
compile 'com.alibaba:fastjson:1.2.28'
compile 'com.alibaba:fastjson:1.1.56.android'
```
```
compile 'com.alibaba:fastjson:1.2.31'
compile 'com.alibaba:fastjson:1.1.56.android'
```

**Comment by wenshao** [comment]
上面出错信息是在哪个版本下的？

**Comment by XiaoMinwm** [comment]
这个问题在最新版1.2.58还是会出现，尤其是oppo/vivo 6.0.1的机子上，麻烦看下
