### ISSUE TITLE
JSON.toJSONString(obj)时 对object 是有什么要求？

### ISSUE THREAD

**Issue by GuChuan** [alibaba/fastjson#1172]
```
            SwitchContext switchContext = context.getValue();
             JSON.toJSONString(switchContext)
```

报异常：
```
ava.lang.NullPointerException
	at com.alibaba.search.autoumars.middleware.dcc.TableOnlineConfig.getLoadConfig(TableOnlineConfig.java:75)
	at com.alibaba.fastjson.serializer.ASMSerializer_6_TableOnlineConfig.write(Unknown Source)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:251)
	at com.alibaba.fastjson.serializer.ASMSerializer_1_SwitchContext.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:275)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:637)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:579)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:544)
```

**Comment by wenshao** [comment]
这个是序列化时调用方法getLoadConfig报错了，具体解决办法参考文档 https://github.com/alibaba/fastjson/wiki/SerializerFeature_IgnoreErrorGetter_cn
