### ISSUE TITLE
JSON.parseObject 报错

### ISSUE THREAD

**Issue by GuChuan** [alibaba/fastjson#1174]
```
public class SwitchTask {
    private static Logger logger = LoggerFactory.getLogger(SwitchTask.class);

    private ArrayList<TableTarget> tableTargets;
    private SwitchTaskType taskType ;
    private long startTime;
    private long endTime;
    private long timeoutThreshold;
    private String status;

    protected ZoneInfo zoneInfo;
    protected SuezService suezService;

    private boolean hasError;
    private String errorMessage;
}

public class ZoneInfo {
    private Long zoneID;
    private Long clusterID;
    private Long serviceID;
    private String clusterName;
    private String zoneName;
    private String roleType;
    private Long partitionNum;
    private Long replicaNum;
    private ZoneStatus status;
    private String adminAddress;
    private long maxPartitionIndexSize = 300L;
    private int maxSwitchTables = 10;
    private long smallTaskIndexSize = 50L;
    private SmokeConfig smokeConfig;
    private TimeWindow switchWindow = new TimeWindow();
    private SwitchMode switchMode = SwitchMode.SM_SWITCH_AUTO;
    private boolean isSmoke = false;
    private String zoneHttpPort;
    private Logger logger = LoggerFactory.getLogger(ZoneInfo.class);



 SwitchTask switchTask = new SwitchTask(zoneInfo,tableTargets, SwitchTaskType.UPDATE);
 JSON.parseObject(JSON.toJSONString(switchTask),SwitchTask.class);
```

报错是这个，报错的这个类和我要反序列化的这个类没有直接关系，为什么会报错？
```
com.alibaba.fastjson.JSONException: default constructor not found. class com.alibaba.search.autoumars.dataswitchcenter.model.TableOfflineInfo$IndexMeta

```

**Comment by wenshao** [comment]
非静态内嵌类，无法创建实例，把内嵌类加上static修饰符就好了

**Comment by halfhq** [comment]
#1173

**Comment by halfhq** [comment]
@wenshao 即使申明为静态也是不行的
```java
 /**
     * {"state":1,"data":{"msg":"123"}}
     */
    void testInternalClass() {
        String json = "{\"state\":1,\"data\":{\"msg\":\"123\"}}";
        try {
            InternalClassTest c = JSON.parseObject(json, InternalClassTest.class);
            Log.d("JSON", "c.state=" + c.state + ", c.data.msg=" + (c.data == null ? "null" : c.data.msg));
        } catch (Exception e) {
            e.printStackTrace();    //com.alibaba.fastjson.JSONException: default constructor not found
        }
    }

    public static class InternalClassTest {
        public InternalClassTest() {
            super();
        }
        @JSONField(name = "state")
        public boolean state;
        @JSONField(name = "data")
        public Data data;

        public static class Data {
            public Data() {
                super();
            }
            @JSONField(name = "msg")
            public String msg;
        }
    }
```
执行结果如下：
```java
om.alibaba.fastjson.JSONException: default constructor not found. class com.yyw.fastjson_example.MainActivit
   at com.alibaba.fastjson.util.JavaBeanInfo.build(Unknown Source)
   at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.<init>(Unknown Source)
   at com.alibaba.fastjson.parser.ParserConfig.createJavaBeanDeserializer(Unknown Source)
   at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(Unknown Source)
   at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.getFieldValueDeserilizer(Unknown Sou
   at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(Unknown Source)
   at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(Unknown Source)
   at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(Unknown Source)
   at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(Unknown Source)
   at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(Unknown Source)
   at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(Unknown Source)
   at com.alibaba.fastjson.JSON.parseObject(Unknown Source)
   at com.alibaba.fastjson.JSON.parseObject(Unknown Source)
   at com.alibaba.fastjson.JSON.parseObject(Unknown Source)
```
compile 'com.alibaba:fastjson:1.2.33'
compile 'com.alibaba:fastjson:1.1.58.android'
混淆：
#fastjson
-dontwarn com.alibaba.fastjson.**
-keepattributes Signature
-keepattributes Annotation
-keep class com.alibaba.fastjson.** { *; }

**Comment by halfhq** [comment]
@GuChuan 采用下面的方式避免：
1.使用static类
2.创建一个interface IFastJson，将此类的全部implements IFastJson
3.在proguard.txt中配置
```
-keep class * implements com.yyw.box.base.json.IFastJson { 
    public <init>(***);
}
```

**Comment by bingxuebage** [comment]
mark
