### ISSUE TITLE
JSONPath  "deepScan属性访问，例如$..name"  抛出异常

### ISSUE THREAD

**Issue by l99xl** [alibaba/fastjson#1177]
使用1.2.8版本，main方法中执行以下代码：
`String text = "{\"a\":{\"b\":\"c\",\"g\":{\"e\":\"f\"}},\"d\":{\"a\":\"f\",\"h\":[\"s1\"]}} ";
        JSONObject jsonObject = JSONObject.parseObject(text);
        Object eval = JSONPath.eval(jsonObject, "$..a");`

抛出异常
Exception in thread "main" com.alibaba.fastjson.JSONPathException: illeal jsonpath syntax. $..a
	at com.alibaba.fastjson.JSONPath$JSONPathParser.readName(JSONPath.java:826)
	at com.alibaba.fastjson.JSONPath$JSONPathParser.readSegement(JSONPath.java:356)
	at com.alibaba.fastjson.JSONPath$JSONPathParser.explain(JSONPath.java:889)
	at com.alibaba.fastjson.JSONPath.init(JSONPath.java:66)
	at com.alibaba.fastjson.JSONPath.eval(JSONPath.java:75)
	at com.alibaba.fastjson.JSONPath.eval(JSONPath.java:251)
	at com.apidocs.test.test.main(test.java:65)

**Comment by wenshao** [comment]
我刚测试过，新版本是好的，升级到最新版吧 https://github.com/alibaba/fastjson/releases/tag/1.2.31

**Comment by l99xl** [comment]
果然如此。非常感谢！
不过在使用的过程中又遇到了新的问题：
 
String text = "{\"a\":{\"x\":\"y\"},\"b\":{\"x\":\"y\"}}";
JSONObject jsonObject = JSONObject.parseObject(text);
System.out.println(jsonObject);
String jsonpath = "$..x";
String value="y2";
JSONPath.set(jsonObject, jsonpath, value);
System.out.println(jsonObject);



执行以上代码，
我期望的结果是：{"a":{"x":"y2"},"b":{"x":"y2"}}
但实际结果却是：{"a":{"x":"y"},"b":{"x":"y"},"x":"y2"}


同样的，text="{\"a\":{\"x\":[\"e1\",\"e2\"]},\"b\":{\"x\":[\"e1\",\"e2\"]}}" 时，
执行结果为{"a":{"x":["e1","e2"]},"b":{"x":["e1","e2"]},"x":"y"}，期望的结果依然是{"a":{"x":"y2"},"b":{"x":"y2"}}


所以，请问JSONPath是否有方法可以实现我预期的结果，即批量替换json对象及其子节点中多个相同key的值。




------------------ Original ------------------

**Comment by wenshao** [comment]
已经支持，我会尽快发布新版修复此问题。
