### ISSUE TITLE
Android 上解析json 转 Parcelable序列化的实体崩溃

### ISSUE THREAD

**Issue by ShengJunHu** [alibaba/fastjson#1182]
fastJson解析报错，Gson解析不会报错

com.alibaba.fastjson.JSONException: default constructor not found. class com.rzy.xbs.assistant.bean.DeviceRespBean$DataBean
at com.alibaba.fastjson.parser.JavaBeanInfo.build(JavaBeanInfo.java:371)
at com.alibaba.fastjson.parser.JavaBeanDeserializer.<init>(JavaBeanDeserializer.java:31)
at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:211)
at com.alibaba.fastjson.parser.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:32)
at com.alibaba.fastjson.parser.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:874)
at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:695)
at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:95)
at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:679)
at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:652)
at com.alibaba.fastjson.JSON.parseObject(JSON.java:218)
at com.alibaba.fastjson.JSON.parseObject(JSON.java:190)
at com.alibaba.fastjson.JSON.parseObject(JSON.java:149)
at com.alibaba.fastjson.JSON.parseObject(JSON.java:258)

**Comment by wenshao** [comment]
DataBean 这个是非静态内嵌类，能否加上static修饰符？

**Comment by ShengJunHu** [comment]
嗯嗯，可以的

**Comment by halfhq** [comment]
#1173

**Comment by okpoint** [comment]
我也遇到了这个问题，添加了一个无参数的构造器就可以了。
