### ISSUE TITLE
注解@JSONField(deserialize = false)，反系列化出错

### ISSUE THREAD

**Issue by chenhongtu** [alibaba/fastjson#1188]
对象是这样的
```
	public class Info{
		
		@JSONField(deserialize=false)
		private List<Integer> ids;
		private String name;
		
		public List<Integer> getIds() {
			return ids;
		}

		public void setIds(List<Integer> ids) {
			this.ids = ids;
		}

		public String getName() {
			return name;
		}
		
		public void setName(String name) {
			this.name = name;
		}
		
	}
```
json是`{"ids":"1,2","name":"abc"}` 反系列化是正常的,ids 也是 null
当json是`{"ids":"a1,a2","name":"abc"}`就出错了
```
Exception in thread "main" com.alibaba.fastjson.JSONException: For input string: "a1a2"
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:646)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:350)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:254)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:467)
	at com.huateng.weixin.Test.main(Test.java:54)
Caused by: java.lang.NumberFormatException: For input string: "a1a2"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:492)
	at java.lang.Integer.parseInt(Integer.java:527)
	at com.alibaba.fastjson.util.TypeUtils.castToInt(TypeUtils.java:578)
	at com.alibaba.fastjson.serializer.IntegerCodec.deserialze(IntegerCodec.java:100)
	at com.alibaba.fastjson.parser.deserializer.ArrayListTypeFieldDeserializer.parseArray(ArrayListTypeFieldDeserializer.java:174)
	at com.alibaba.fastjson.parser.deserializer.ArrayListTypeFieldDeserializer.parseField(ArrayListTypeFieldDeserializer.java:62)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:602)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:212)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:208)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:642)
	... 4 more

```
为什么加了@JSONField(deserialize=false)不是直接忽略 ids呢？
这个问题要怎么解决呢？

**Comment by SuperDubbo** [comment]
这个类的正常JSON值应该是这样{"ids":[1,2],"name":"abc"}，如果故意换成{"ids":[a1,b2],"name":"abc"}解析还是报错啊，温少，我刚刚试过了{"ids":"a1,a2","name":"abc"}这样的话，经过你修改JavaBeanInfo的处理是可以的，现在就是这种还是不能正常转换{"ids":[a1,b2],"name":"abc"}的

**Comment by SuperDubbo** [comment]
Info info=new Info();
        info.setName("abc");
        List<Integer> list=new ArrayList<>();
        list.add(1);
        list.add(2);
        info.setIds(list);
        System.out.println(JSON.toJSONString(info));
        String str="{\"ids\":[a1,a2],\"name\":\"abc\"}";
//        String str = "{\"ids\":\"a1,a2\",\"name\":\"abc\"}";
        Info info1=JSON.parseObject(str,Info.class);
        System.out.println(info1);
    }



"D:\Program Files\Java\jdk1.8.0_101\bin\java" "-javaagent:D:\Program Files (x86)\JetBrains\IntelliJ IDEA 2017.1\lib\idea_rt.jar=62507:D:\Program Files (x86)\JetBrains\IntelliJ IDEA 2017.1\bin" -Dfile.encoding=UTF-8 -classpath "D:\Program Files\Java\jdk1.8.0_101\jre\lib\charsets.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\deploy.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\access-bridge-64.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\cldrdata.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\dnsns.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\jaccess.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\jfxrt.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\localedata.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\nashorn.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunec.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunjce_provider.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunmscapi.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunpkcs11.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\zipfs.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\javaws.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\jce.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\jfr.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\jfxswt.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\jsse.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\management-agent.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\plugin.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\resources.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\rt.jar;E:\git_repositoryforplay\test\build\classes\main;D:\gradlelib\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-databind\2.5.3\c37875ff66127d93e5f672708cb2dcc14c8232ab\jackson-databind-2.5.3.jar;D:\gradlelib\caches\modules-2\files-2.1\com.alibaba\fastjson\1.2.31\1ca964122c53f03f6fc3938b58c16d63b40490ab\fastjson-1.2.31.jar;D:\gradlelib\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-annotations\2.5.0\a2a55a3375bc1cef830ca426d68d2ea22961190e\jackson-annotations-2.5.0.jar;D:\gradlelib\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-core\2.5.3\a8b8a6dfc8a17890e4c7ff8aed810763d265b68b\jackson-core-2.5.3.jar" com.hz.json.bean.T
{"ids":[1,2],"name":"abc"}
Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error, pos 9, json : {"ids":[a1,a2],"name":"abc"}
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1394)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1301)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1185)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1328)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1301)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseExtra(DefaultJSONParser.java:1506)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:807)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:630)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:1010)
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_1_Info.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:208)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:642)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:350)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:254)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:467)
	at com.hz.json.bean.T.main(T.java:22)

**Comment by chenhongtu** [comment]
@SuperDubbo 
`{"ids":[a1,b2],"name":"abc"}`这是json语法错误了吧，你要测试的是`{"ids":["a1","b2"],"name":"abc"}`吧

**Comment by SuperDubbo** [comment]
@chenhongtu
对，是我搞错了，我要测试的是{"ids":["a1","b2"],"name":"abc"}，谢谢

**Comment by wenshao** [comment]
问题已经重现并解决，正准备发布新版本。

**Comment by wenshao** [comment]
新版本已经解决问题 https://github.com/alibaba/fastjson/releases/tag/1.2.32
