### ISSUE TITLE
android版本在某些机型上报java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonInclude

### ISSUE THREAD

**Issue by wuxia2001** [alibaba/fastjson#1209]
java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonInclude
	at java.lang.Class.getDeclaredAnnotation(Native Method)
	at java.lang.Class.getAnnotation(Class.java:260)
	at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:175)
	at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:144)
	at com.alibaba.fastjson.parser.ListTypeFieldDeserializer.parseArray(ListTypeFieldDeserializer.java:157)
	at com.alibaba.fastjson.parser.ListTypeFieldDeserializer.parseField(ListTypeFieldDeserializer.java:63)
	at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:595)
	at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:97)
	at com.alibaba.fastjson.parser.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:45)
	at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:595)
	at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:97)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:682)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:655)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:216)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:188)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:142)
	at com.hentre.android.util.JsonUtil.toObject(JsonUtil.java:66)
	at com.hentre.android.hnkzy.activity.MainActivity.decodeData(MainActivity.java:363)
	at com.hentre.android.hnkzy.activity.MainActivity.initData(MainActivity.java:336)
	at com.hentre.android.hnkzy.activity.MainActivity.onResume(MainActivity.java:243)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1191)
	at android.app.Activity.performResume(Activity.java:5236)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2746)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2785)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
	at android.app.ActivityThread.access$600(ActivityThread.java:142)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1235)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5069)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.fasterxml.jackson.annotation.JsonInclude" on path: /data/app/com.hentre.android.hnkzy-1.apk
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
	... 35 more
java.lang.ClassNotFoundException: Didn't find class "com.fasterxml.jackson.annotation.JsonInclude" on path: /data/app/com.hentre.android.hnkzy-1.apk
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
	at java.lang.Class.getDeclaredAnnotation(Native Method)
	at java.lang.Class.getAnnotation(Class.java:260)
	at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:175)
	at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:144)
	at com.alibaba.fastjson.parser.ListTypeFieldDeserializer.parseArray(ListTypeFieldDeserializer.java:157)
	at com.alibaba.fastjson.parser.ListTypeFieldDeserializer.parseField(ListTypeFieldDeserializer.java:63)
	at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:595)
	at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:97)
	at com.alibaba.fastjson.parser.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:45)
	at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:595)
	at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:97)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:682)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:655)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:216)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:188)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:142)
	at com.hentre.android.util.JsonUtil.toObject(JsonUtil.java:66)
	at com.hentre.android.hnkzy.activity.MainActivity.decodeData(MainActivity.java:363)
	at com.hentre.android.hnkzy.activity.MainActivity.initData(MainActivity.java:336)
	at com.hentre.android.hnkzy.activity.MainActivity.onResume(MainActivity.java:243)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1191)
	at android.app.Activity.performResume(Activity.java:5236)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2746)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2785)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
	at android.app.ActivityThread.access$600(ActivityThread.java:142)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1235)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5069)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at dalvik.system.NativeStart.main(Native Method)

这个错只要某些机型上报出来,大部分机型都是没有问题的
有问题的机型在于
魅族MX3  4.2.1系统
魅族M355 4.2.1系统
金立GN9002  4.2.2系统
三星SM-G3818  4.2.2系统

很奇怪,在大部分机型上都没有问题的......

**Comment by wenshao** [comment]
你的类有如下标注 ？
```java
@JsonInclude
```
