### ISSUE TITLE
JSON.parseObject(json, class)和jsonObject.toJavaObject(class)结果不一致，并且都是错误的

### ISSUE THREAD

**Issue by halfhq** [alibaba/fastjson#1227]
有如下json字符串和类：
String t2 = "{\"state\":2,\"msg\":\"msg2222\",\"data\":{}}";
    public static class Test {
        public int state;
        public String msg;
        public List<Data> data;
        public static class Data {
            public int d1;
            public String d2;
        }
    }
测试代码如下：
        try {
            Test c2 = JSON.parseObject(t2, Test.class);
            Log.d("JSON", "c2 ----");
            com.alibaba.fastjson.JSONObject jsonObject = JSON.parseObject(t2);
            Test model = jsonObject.toJavaObject(Test.class);
            Log.d("JSON", "model ----");
        } catch ( Exception e) {
            e.printStackTrace();
        }
c2可以格式化出结果，但结果是**错误**的，
c2 = {MainActivity$Test@830029442312} 
 **data = {ArrayList@830029442520}  size = 1**
  0 = {MainActivity$Test$Data@830029442600} 
   d2 = null
   d1 = 0
 msg = "msg2222"
 state = 2
model执行出现异常
e = {JSONException@830029375048} "com.alibaba.fastjson.JSONException: can not cast to : java.util.List<com.yyw.fastjson_example.MainActivity$Test$Data>"
 cause = {JSONException@830029373272} "com.alibaba.fastjson.JSONException: can not cast to : java.util.List<com.yyw.fastjson_example.MainActivity$Test$Data>"
 detailMessage = "can not cast to : java.util.List<com.yyw.fastjson_example.MainActivity$Test$Data>"
 stackState = {int[38]@830029375080} 
 stackTrace = {StackTraceElement[0]@830024963328} 
 suppressedExceptions = {Collections$EmptyList@830024961208}  size = 0

**Comment by halfhq** [comment]
@weicao 要求data为空（不存在或者 "data":{}），输出的List data==null（或size==0）
请问，有没有选项使得忽略“can not cast to”错误？

**Comment by yrom** [comment]
看起来跟我遇到的问题类似 https://github.com/alibaba/fastjson/issues/1229

**Comment by kimmking** [comment]
data:{}  与 data ==null 可不等价。
可以试试用data:[]，data:null

**Comment by kimmking** [comment]
[Issue1227.java.txt](https://github.com/alibaba/fastjson/files/1028546/Issue1227.java.txt)

try this

**Comment by kimmking** [comment]
测试来看：
1、在master上的代码，data:{}转List都会报错：
Test{state=2, msg='msg2222', data=[{}]}
-------------------
com.alibaba.fastjson.JSONException: exepct '[', but {, pos 1, json : {}
	at com.alibaba.fastjson.util.TypeUtils.castToJavaBean(TypeUtils.java:1058)
	at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:695)
	at com.alibaba.fastjson.JSON.toJavaObject(JSON.java:939)
	at com.alibaba.json.bvt.issue_1200.Issue1227.test_for_issue(Issue1227.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: com.alibaba.fastjson.JSONException: exepct '[', but {, pos 1, json : {}
	at com.alibaba.fastjson.util.TypeUtils.castToJavaBean(TypeUtils.java:1058)
	at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:695)
	at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:874)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.createInstance(JavaBeanDeserializer.java:1011)
	at com.alibaba.fastjson.util.TypeUtils.castToJavaBean(TypeUtils.java:1056)
	... 25 more
Caused by: com.alibaba.fastjson.JSONException: exepct '[', but {, pos 1, json : {}
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:658)
	at com.alibaba.fastjson.serializer.CollectionCodec.deserialze(CollectionCodec.java:120)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:628)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:354)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:258)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:471)
	at com.alibaba.fastjson.util.TypeUtils.castToJavaBean(TypeUtils.java:1017)
	... 29 more


2、改成[]，则完全ok：
Test{state=2, msg='msg2222', data=[]}
-------------------
Test{state=2, msg='msg2222', data=[]}

Process finished with exit code 0

**Comment by kimmking** [comment]
确实存在解析不一致，
 JSON.parseObject 可以解析，但是List里是一个空的JSONObject，都是{}与[]惹的锅。

**Comment by halfhq** [comment]
@kiminotes json字符串是后台返回的，不可更改。
我想要：提供一个参数，发生cast异常时忽略，
这样List data就不会被赋值

**Comment by kimmking** [comment]
如果是这样，说明你们后台序列化的库有bug，
建议替换成fastjson之类的，它不会把一个array序列化成{}

**Comment by halfhq** [comment]
@kimmking 后台是php的。
如果某个函数返回为null则默认输出data:{}是允许的。
当然最好的情况是data整个都不输出

**Comment by a3600266** [comment]
这个问题到现在都还是老样子吗
