### ISSUE TITLE
org.springframework.util.LinkedMultiValueMap反序列化失败

### ISSUE THREAD

**Issue by dongxingong** [alibaba/fastjson#1240]
fastjson版本：1.2.32
LinkedMultiValueMap数据无法反序列化

testcase：
```
        ParserConfig.getGlobalInstance().setAutoTypeSupport(true);
        LinkedMultiValueMap<String, String> result = new LinkedMultiValueMap();
        result.add("test", "11111");
        String test = JSON.toJSONString(result, SerializerFeature.WriteClassName);
        JSON.parseObject(test);
```

报错信息：

```
   Exception in thread "main" com.alibaba.fastjson.JSONException: autoType is not support. org.springframework.util.LinkedMultiValueMap
	at com.alibaba.fastjson.parser.ParserConfig.checkAutoType(ParserConfig.java:830)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:325)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1335)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1301)
	at com.alibaba.fastjson.JSON.parse(JSON.java:152)
	at com.alibaba.fastjson.JSON.parse(JSON.java:143)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:216)
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.33
已经发布新版本支持，请使用新版本验证是否解决你的问题，谢谢。
