### ISSUE TITLE
com.alibaba.fastjson.JSONException: TODO

### ISSUE THREAD

**Issue by Abelsf** [alibaba/fastjson#1261]
com.alibaba.fastjson.JSONException: TODO
        at com.alibaba.fastjson.util.TypeUtils.getRawClass(TypeUtils.java:2019)
        at com.alibaba.fastjson.util.TypeUtils.createCollection(TypeUtils.java:1981)
        at com.alibaba.fastjson.serializer.CollectionCodec.deserialze(CollectionCodec.java:117)
        at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:71)
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:828)
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:630)
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:212)
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:208)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:642)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:350)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:254)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:467)
        at com.djdg.product.api.sdk.service.StockService.operateStockRecord(StockService.java:59)
        at com.djdg.product.api.sdk.Service.operateStockRecord(Service.java:391)
        at com.djdg.pos.client.api.help.ProductHelper.generateWarehouseRecord(ProductHelper.java:78)
        at com.djdg.pos.client.api.help.OrderHelper.generateWarehouseRecord(OrderHelper.java:102)
        at com.djdg.pos.client.api.service.order.product.StoreProductOrderServiceImpl.orderPayedHandle(StoreProductOrderServiceImpl.java:546)
        at com.djdg.pos.client.api.service.order.product.StoreProductOrderServiceImpl.lambda$updateOrder$1(StoreProductOrderServiceImpl.java:298)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:590)
        at com.djdg.pos.client.api.service.order.product.StoreProductOrderServiceImpl.updateOrder(StoreProductOrderServiceImpl.java:289)
        at com.djdg.pos.client.api.rest.v1.CheckoutApi.updateStoreOrder(CheckoutApi.java:82)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
        at org.jboss.resteasy.plugins.server.netty.RequestDispatcher.service(RequestDispatcher.java:83)
        at org.jboss.resteasy.plugins.server.netty.RequestHandler.messageReceived(RequestHandler.java:56)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
        at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
        at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:314)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by kimmking** [comment]
能否提供你用到的json和pojo结构，
如果能做个testcase最好了

**Comment by wenshao** [comment]
还有能否提供fastjson的版本？

**Comment by mustfun** [comment]
1.2.29版本，数据结构：
```json
{"data":2660885,"count":0,"hasError":false,"errorCode":null,"errorMessage":null,"errorTrace":null,"status":0,"message":null}
````
不定时不定期出现，使用的下面这段代码进行解析
```java
JSON.parseObject(entityStream, this.fastJsonConfig.getCharset(), type, this.fastJsonConfig.getFeatures())
```
返回的结果是这种数据结构   `Result<Integer>` ，其中Result如下
```java
    private long status;
    private String message;
    private T data;

    private Integer count;
    private boolean hasError;
    private String errorCode;
    private String errorMessage;
    private String errorTrace;

```

感谢！

**Comment by slankka** [comment]
我也是1.2.29，也是出这个异常。SpringBoot + Feign+JDK 1.7.0_55。
JDK1.8就没有问题。
`Caused by: com.alibaba.fastjson.JSONException: TODO
        at com.alibaba.fastjson.util.TypeUtils.getRawClass(TypeUtils.java:1932) ~[fastjson-1.2.29.jar!/:?]
        at com.alibaba.fastjson.util.TypeUtils.createCollection(TypeUtils.java:1894) ~[fastjson-1.2.29.jar!/:?]
        at com.alibaba.fastjson.serializer.CollectionCodec.deserialze(CollectionCodec.java:117) ~[fastjson-1.2.29.jar!/:?]
        at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:71) ~[fastjson-1.2.29.jar!/:?]
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:575) ~[fastjson-1.2.29.jar!/:?]
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:188) ~[fastjson-1.2.29.jar!/:?]
`

**Comment by su1216** [comment]
1.1.68.android
json:

> {
  "data": {},
  "errorCode": 0
}

@kimmking

**Comment by su1216** [comment]
> com.alibaba.fastjson.JSONException: TODO
	at com.alibaba.fastjson.serializer.CollectionCodec.deserialze(CollectionCodec.java:138)
	at com.alibaba.fastjson.parser.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:73)
	at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:713)
	at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:116)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:686)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:659)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:238)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:210)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:164)

**Comment by nicksheng** [comment]
我是1.2.22版本，也有这个异常。诡异的是服务器上有这个异常，在本地测试就正常，JDK都是1.8，看不出别的问题。
```
com.alibaba.fastjson.JSONException: TODO
        at com.alibaba.fastjson.util.TypeUtils.getRawClass(TypeUtils.java:1735) ~[fastjson-1.2.22.jar!/:?]
        at com.alibaba.fastjson.util.TypeUtils.createCollection(TypeUtils.java:1697) ~[fastjson-1.2.22.jar!/:?]
        at com.alibaba.fastjson.serializer.CollectionCodec.deserialze(CollectionCodec.java:119) ~[fastjson-1.2.22.jar!/:?]
        at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:71) ~[fastjson-1.2.22.jar!/:?]
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:722) ~[fastjson-1.2.22.jar!/:?]
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:568) ~[fastjson-1.2.22.jar!/:?]
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:187) ~[fastjson-1.2.22.jar!/:?]
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:183) ~[fastjson-1.2.22.jar!/:?]
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:624) ~[fastjson-1.2.22.jar!/:?]
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:339) ~[fastjson-1.2.22.jar!/:?]
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:243) ~[fastjson-1.2.22.jar!/:?]
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:456) ~[fastjson-1.2.22.jar!/:?]
```

**Comment by helloworldtang** [comment]
好奇怪，也报了同样的错：
fastjson版本：1.2.31
```java
   com.alibaba.fastjson.JSONException: TODO
```

同样的spring boot的fat jar，部署在两台机器上，只有一台机器报上面的错。
等转成json的字符串：
```json
{
	"code": 0,
	"data": true,
	"message": "OK",
	"status": 0
}
```
调用的API:  
```java
   com.alibaba.fastjson.JSON.toJSONString()
```
报错的信息：
com.alibaba.fastjson.JSONException: TODO

**Comment by slankka** [comment]
@helloworldtang 你能在某一台机器上复现吗？这两台机器的JDK版本是不是一样的？我一直想复现来着。还有你的Model Class 是什么内容

**Comment by helloworldtang** [comment]
@slankka 
重新发布后，两台机器都开始报错了。刚才把报错的详细信息也粘上去了

**Comment by su1216** [comment]
高版本已经没有这个问题了 @helloworldtang 似乎很久之前就改了

**Comment by helloworldtang** [comment]
@su1216  这种是偶发的，怎么证明已经解决了呢？

对比了下1.2.31和1.2.49中com.alibaba.fastjson.util.TypeUtils.getRawClass, 在第一行代码有变化：
```java
        if (type instanceof  Class<?>) {
```

v1.2.31中：
```java
    public static Class<?> getRawClass(Type type) {
        if (type instanceof  Class<?>) {
            return (Class<?>) type;
        } else if (type instanceof ParameterizedType) {
            return getRawClass(((ParameterizedType) type).getRawType());
        } else {
            throw new JSONException("TODO");
        }
    }
```

v1.2.49中：
```java
    public static Class<?> getRawClass(Type type) {
        if (type instanceof Class) {
            return (Class)type;
        } else if (type instanceof ParameterizedType) {
            return getRawClass(((ParameterizedType)type).getRawType());
        } else {
            throw new JSONException("TODO");
        }
    }
```

**Comment by su1216** [comment]
@helloworldtang 抱歉，之前看成另一个问题了。这个问题不了解。

**Comment by slankka** [comment]
@helloworldtang 我怎么没有看出有什么不同的地方？1.2.31和1.2.49中com.alibaba.fastjson.util.TypeUtils.getRawClass 前两行 没有变化啊

**Comment by jannal** [comment]
我是1.2.54版本，也有这个异常。服务器上有这个异常，在本地mac系统测试就正常，JDK都是1.8

**Comment by VinneyZheng** [comment]
1.2.29版本，我也遇到了这个问题，所以各位大神有解决方案了么，是升级到1.2.49可以了么？

**Comment by zhangptang** [comment]
更新到最新的1.2.58版本，同样报这个错误，错误日志信息和上面都一样，都是在 TypeUtils.getRawClass这个里。各位大佬有解决方法么？这个报错很随机，有点任性啊

**Comment by hhli** [comment]
这个问题我也遇到了，jdk版本测试与本地都是1.8，但是我最终使用TypeReference解决了
原始写法（备注：RespBase是一个范型类型）：
**RespBase base = JSON.parseObject(resultStr, RespBase.class);**
第二种写法也不行：
**JSON.parseObject(resultStr, new TypeReference<RespBase>(){});**
最终使用下面的方式解决了：
**JSON.parseObject(resultStr, new TypeReference<RespBase<?>>(){})**

结论：
推测fastjson对类型的推断处理没有做好，从抛出的异常：“TODO Exception”来看也是，因此对于范型的json转化时，最好加上类型变量或者通配符，希望能够到大家。

**Comment by vicoolee** [comment]
fastjson 1.2.28 
使用反序列化泛型对象后：
PlatformPage<User> userPage = JSON.parseObject(response.getResponseText(), new TypeReference<PlatformPage<User>>(){});
上述代码运行后，其他代码执行报错如：
Result result = JSON.parseObject(response.getResponseText(), Result.class);

public class Result<T> implements Serializable {
    private boolean success;
    private String code;
    private String message;
    private T data;
}
本地测试 无法复现。Jenkins 构建 k8s部署测试环境 每次都是

**Comment by harkue** [comment]
> fastjson 1.2.28 使用反序列化泛型对象后： _PlatformPage userPage = JSON.parseObject(response.getResponseText(), new TypeReference<PlatformPage>(){});_ 上述代码运行后（正常运行），其他代码执行报错如： Result result = JSON.parseObject(response.getResponseText(), Result.class);
> 
> public class Result implements Serializable { private boolean success; private String code; private String message; private T data; } 本地测试 无法复现。Jenkins 构建 k8s部署测试环境 每次都是
> 
> 已使用jackjson 替换反斜线代码。 其他服务未发现上述问题

为啥还在使用这么老的版本？

**Comment by slliver** [comment]
版本2.0.1 也遇到这个问题了

**Comment by Times125** [comment]
2.0.2 也有这个问题

**Comment by ruizhanglei** [comment]
2.0.1有这个问题，2.0.12没有这个问题

**Comment by Times125** [comment]
您好，我已经收到您的来信，会尽快处理。

**Comment by liuzhebaba** [comment]
2.0.26也有这样的问题，服务器上报错，本地是好的

**Comment by Times125** [comment]
您好，我已经收到您的来信，会尽快处理。
