### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by AlanCheen** [alibaba/fastjson#1273]
log:

Caused by: java.lang.OutOfMemoryError: Failed to allocate a 393326954 byte allocation with 16777216 free bytes and 231MB until OOM
	at com.alibaba.fastjson.serializer.SerializeWriter.expandCapacity(SerializeWriter.java:173)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:528)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeString(SerializeWriter.java:805)
	at com.alibaba.fastjson.serializer.StringCodec.write(StringCodec.java:45)
	at com.alibaba.fastjson.serializer.CollectionCodec.write(CollectionCodec.java:110)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:262)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:614)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:334)

**Comment by AlanCheen** [comment]
补充一下  参数，是个 HashSet
JSON.toJSONString(HashSet<String>)

**Comment by kimmking** [comment]
HashSet里的数据，能发出来吗

**Comment by wuwen5** [comment]
这是在安卓环境下吧？环境信息可以提供下，是不是堆大小不够呢？

**Comment by AlanCheen** [comment]
set里只有几个 String，怀疑可能是线程同步的问题

**Comment by AlanCheen** [comment]
是 Android 环境

**Comment by wenshao** [comment]
已沟通，应该并发写导致一个脏的HashSet导致的

**Comment by mavsplus** [comment]
方便具体描述一下并发写导致一个脏的HashSet是怎么回事吗?
