### ISSUE TITLE
原来运行一直正常，忽然报oom了

### ISSUE THREAD

**Issue by lirenzuo** [alibaba/fastjson#1289]
Exception in thread "Thread-2" Exception in thread "Thread-3" java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOfRange(Arrays.java:2694)
	at java.lang.String.<init>(String.java:203)
	at com.alibaba.fastjson.parser.JSONScanner.stringVal(JSONScanner.java:1977)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:346)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:387)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1033)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1011)
	at com.alibaba.fastjson.JSON.parse(JSON.java:94)
	at com.alibaba.fastjson.JSON.parse(JSON.java:85)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:156)

**Comment by lirenzuo** [comment]
调用的语句如下： JSONObject.parseObject(str)

**Comment by wenshao** [comment]
什么版本？

**Comment by lirenzuo** [comment]
版本是fastjson-1.1.25，已经在线上环境添加oom之后dump了，如果在遇到会分析下，就是告诉你们下，看看是否有这方面的问题 ，谢谢

**Comment by jiaoqingbo** [comment]
和你调用的语句一样  版本1.2.47也出现了java heap space

**Comment by YuYuYan** [comment]
和你调用的语句一样 版本1.2.47也出现了java heap space

**Comment by Leedding** [comment]
版本1.2.41
我这边调用了JSONObject.toJSONString(XXXVo)出现了
com.alibaba.fastjson.JSONException: create asm serializer error, class class  xxx.xxx.XXXVo
at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:225)
at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:101)
at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:690)
at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:394)
...
java.lang.OutOfMemoryError: Metaspace
XXXVo包含51个字段，没有复杂类型

**Comment by hans1980775481** [comment]
版本1.2.79
调用如下语：JSON.parseObject(hit.getSourceAsString(), clazz)
同样报：java heap space 错误
![image](https://github.com/alibaba/fastjson/assets/29484912/66ae87a9-e23f-4c5e-8d24-ed5c02716368)
