### ISSUE TITLE
大对象序列化为json时报StackOverflowError

### ISSUE THREAD

**Issue by zhanggang807** [alibaba/fastjson#1295]
如题，具体异常位置：
java.lang.StackOverFlowError
at com.alibaba.fastjsonserializer.Serializer.write(SerializerWrite.java:296)
at com.alibaba.fastjsonserializer.Serializer.write(SerializerWrite.java:449)
at com.alibaba.fastjsonserializer.Serializer.writeDouble(SerializerWrite.java:584)

**Comment by izern** [comment]
Mark一下

**Comment by kimmking** [comment]
对象里有循环引用吧

**Comment by wenshao** [comment]
应该是有循环引用或者get方法中有new

**Comment by zhanggang807** [comment]
然而并没有，普通对象pojo

**Comment by wenshao** [comment]
能提供重现问题的testcase么？

**Comment by maoxiajun** [comment]
> 能提供重现问题的testcase么？

https://www.cnblogs.com/buguge/p/10140073.html

**Comment by YAGAMIL** [comment]
> 应该是有循环引用或者get方法中有new

get方法有new为什么回影响这个
