### ISSUE TITLE
NullPointerException版本1.2.33开始，之前版本不会

### ISSUE THREAD

**Issue by Luckywb** [alibaba/fastjson#1306]
```
package com.yht.goods.model;

import com.alibaba.fastjson.JSON;
import org.junit.Test;

import java.io.Serializable;
import java.util.Arrays;
import java.util.List;

public class FastjsonTest {

    public static abstract class IdEntity<ID extends Serializable> implements Cloneable, Serializable{

        private static final long serialVersionUID = 4877536176216854937L;

        public IdEntity() {}

        public abstract ID getId();
        public abstract void setId(ID id);
    }

    public static class LongEntity extends IdEntity<Long> {

        private static final long serialVersionUID = -2740365657805589848L;

        private Long id;

        @Override
        public Long getId() {
            return id;
        }

        public void setId(Long id) {
            this.id = id;
        }
    }

    public static class Goods extends LongEntity{
        private static final long serialVersionUID = -5751106975913625097L;
        private List<Property> properties;

        public List<Property> getProperties() {
            return properties;
        }

        public void setProperties(List<Property> properties) {
            this.properties = properties;
        }

        public static class Property extends LongEntity{
            private static final long serialVersionUID = 7941148286688199390L;
        }
    }

    public static class TT extends LongEntity {
        private static final long serialVersionUID = 2988415809510669142L;

        public TT(){}
        public TT(Goods goods){
            goodsList = Arrays.asList(goods);
        }


        private List<Goods> goodsList;

        public List<Goods> getGoodsList() {
            return goodsList;
        }

        public void setGoodsList(List<Goods> goodsList) {
            this.goodsList = goodsList;
        }
    }

    @Test
    public void fast() {
        Goods goods = new Goods();
        goods.setProperties(Arrays.asList(new Goods.Property()));

        TT tt = new TT(goods);

        TT n = JSON.parseObject(JSON.toJSONString(tt), TT.class);
        System.out.println(n);
    }
}
```

```
java.lang.NullPointerException
	at com.alibaba.fastjson.util.FieldInfo.getFieldType(FieldInfo.java:302)
	at com.alibaba.fastjson.util.FieldInfo.<init>(FieldInfo.java:208)
	at com.alibaba.fastjson.util.TypeUtils.computeGetters(TypeUtils.java:1575)
	at com.alibaba.fastjson.util.TypeUtils.buildBeanInfo(TypeUtils.java:1360)
	at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:118)
	at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:636)
	at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:400)
	at com.alibaba.fastjson.serializer.JSONSerializer.getObjectWriter(JSONSerializer.java:359)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:275)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:656)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:598)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:563)
	at com.yht.goods.model.FastjsonTest.fast(FastjsonTest.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
```

**Comment by wenshao** [comment]
问题已经修复，请使用新版本
https://github.com/alibaba/fastjson/releases/tag/1.2.35

**Comment by wyfSunflower** [comment]
Error: java.lang.NullPointerException
	at com.jd.stat.AlarmDataFormat$MergeReducer.reduce(AlarmDataFormat.java:271)
	at com.jd.stat.AlarmDataFormat$MergeReducer.reduce(AlarmDataFormat.java:210)
	at org.apache.hadoop.mapreduce.Reducer.run(Reducer.java:171)
	at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:627)
	at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:389)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:168)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1830)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:162)
fastjson 1.2.61
