### ISSUE TITLE
反序列化LocalDateTime类型,值为null的问题

### ISSUE THREAD

**Issue by superwen0001** [alibaba/fastjson#1357]
当我class中存在LocalDateTime时.json字符串中对应值为null时,反序列出现下面问题
有什么处理方案

```
    @Test
    public void test2(){
        String str = "{\"d2\":null}";
        Test2Bean b = JSONObject.parseObject(str,Test2Bean.class);
        System.out.println(b);
    }

    @Data
    public static class Test2Bean{
        private LocalDateTime d2;

    }

```

```
com.alibaba.fastjson.JSONException: not close json text, token : }

	at com.alibaba.fastjson.parser.DefaultJSONParser.close(DefaultJSONParser.java:1440)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:354)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:254)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:467)
	at com.caiyi.financial.nirvana.json.FastJsonTest.test2(FastJsonTest.java:57)
```

**Comment by superwen0001** [comment]
fasjson版本1.2.28

**Comment by wenshao** [comment]
我测试新版本是好的，你升级到最新版本吧 http://repo1.maven.org/maven2/com/alibaba/fastjson/1.2.35/

**Comment by superwen0001** [comment]
嗯,升级到1.2.35没问题了
