### ISSUE TITLE
JsonObject转为java对象（包含Timestamp）报错com.alibaba.fastjson.JSONException: can not cast to Timestamp, value : 2017-08-04 15:16:41.0

### ISSUE THREAD

**Issue by bofei222** [alibaba/fastjson#1370]
数据库 Timestamp类型 字段createtime：2017-08-04 15:16:41.000000000
Policy  包含 creatime 属性的实体对象。
```java
        List<JSONObject> policys = ps.GetPolicys();
        for (JSONObject js : policys) {
            System.out.println("查询策略列表..............");
            
            Policy p = JSON.toJavaObject(js, Policy.class);
```

```java
com.alibaba.fastjson.JSONException: can not cast to Timestamp, value : 2017-08-04 15:16:41.0
	at com.alibaba.fastjson.util.TypeUtils.castToJavaBean(TypeUtils.java:1077)
	at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:714)
	at com.alibaba.fastjson.JSON.toJavaObject(JSON.java:945)
	at cn.com.nei.drmp.feign.controller.MainController.setTask(MainController.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.36
问题已经修复，请使用新版本

**Comment by kenhan90** [comment]
Caused by: com.alibaba.fastjson.JSONException: can not cast to Timestamp, value : 2006-8-9
	at com.alibaba.fastjson.util.TypeUtils.castToSqlDate(TypeUtils.java:412)
	at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:750)
	at com.bcss.poi.excel.utils.ExcelUtils.setProperty(ExcelUtils.java:1414)
	at com.bcss.poi.excel.utils.ExcelUtils.readRow(ExcelUtils.java:424)
