### ISSUE TITLE
使用features 组合 出现 java.lang.NullPointerException

### ISSUE THREAD

**Issue by lveliu** [alibaba/fastjson#1425]
测试版本：1.2.28， 1.2.37
测试代码
public class DicDomain  {

    private String code;

    private String name;

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

public static void main(String[] args) {
        DicDomain dicDomain = new DicDomain();
        dicDomain.setCode("A001");
        dicDomain.setName("测试");

        SerializerFeature[] features = new SerializerFeature[]{
                SerializerFeature.NotWriteRootClassName,
                SerializerFeature.WriteClassName,
                SerializerFeature.DisableCircularReferenceDetect
        };

        System.out.println(JSON.toJSONString(dicDomain, features));
    }
错误原因：
      只有当这个三个features 搭配使用会出现错误，是这三个不能搭配使用么？。去掉其中任何一个都不会错误。

错误信息;
Exception in thread "main" java.lang.NullPointerException
	at com.alibaba.fastjson.serializer.JSONSerializer.isWriteClassName(JSONSerializer.java:140)
	at com.alibaba.fastjson.serializer.ASMSerializer_1_DicDomain.writeNormal(Unknown Source)
	at com.alibaba.fastjson.serializer.ASMSerializer_1_DicDomain.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:278)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:587)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:576)
	at com.zcareze.json.DicTest.main(DicTest.java:35)

**Comment by wenshao** [comment]
谢谢反馈，这是一个bug，已经修复，会在下个版本中带上

**Comment by wenshao** [comment]
问题已经修，请使用新版本 https://github.com/alibaba/fastjson/releases/tag/1.2.38
