### ISSUE TITLE
在对象转String是偶遇这个报错,使用fastjson版本1.2.32

### ISSUE THREAD

**Issue by shiyan3** [alibaba/fastjson#1453]
{exception_info=com.xxx.core.exception.CustomUncaughtExceptionHandler:write javaBean error, class com.xxx.lib.exercise.statistics.OklibReportedDataResponse, write javaBean error, class com.xxx.lib.exercise.statistics.OxlibReportedDataResponse$QuestionInfoEntity, fieldName : question_info, Index: 3, Size: 0
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:359)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:111)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:275)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:652)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:594)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:559)
	at com.xxx.logprintlib.OkLogPrintManager$2.run(OkLogPrintManager.java:186)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
com.xxx.core.exception.CustomUncaughtExceptionHandler:write javaBean error, class com.xxx.lib.exercise.statistics.OxlibReportedDataResponse$QuestionInfoEntity, fieldName : question_info, Index: 3, Size: 0
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:359)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:111)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:240)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:327)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:111)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:275)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:652)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:594)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:559)
	at com.xxx.logprintlib.OxLogPrintManager$2.run(OxLogPrintManager.java:186)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
com.xxx.core.exception.CustomUncaughtExceptionHandler:Index: 3, Size: 0
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:96)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:240)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:327)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:111)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:240)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:327)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:111)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:275)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:652)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:594)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:559)
	at com.xxx.logprintlib.OxLogPrintManager$2.run(OkLogPrintManager.java:186)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

**Comment by kimmking** [comment]
并发问题，序列化过程中，list的长度变了。

这样的话，感觉此处的业务代码逻辑是有问题的。
比如说 开始序列化前list有4个元素，处理的这10ms内list被去掉了一个元素。
这时候只有3个元素了，那么就会有上面的问题产生。
请问按照业务逻辑，是应该序列化4个元素给rest接口，还是3个元素呢？

请修改代码，保持list内容的一致性。
1、要么保持list不变，如果要变，使用新的list对象表示变化后的列表。
2、如果上面一条也保证不了，就序列化之前，复制一个新的list返回。即：
```
List list = new ArrayList(); 
list.addAll(原本的list);
return list;
```

**Comment by shiyan3** [comment]
明白了，谢谢回复。
