### ISSUE TITLE
反序列化两次序列化后的字符串报NPE

### ISSUE THREAD

**Issue by LNAmp** [alibaba/fastjson#1463]
```
People wenshao = new People("wenshao", "18");
String firstSerialized = JSON.toJSONString(wenshao);
String secondSerialized = JSON.toJSONString(firstSerialized);
People people = JSON.parseObject(secondSerialized, People.class);
 ```
抛出NPE
```
Exception in thread "main" com.alibaba.fastjson.JSONException
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:630)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:348)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:252)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:471)
	at com.alibaba.fastjson.issuenpe.TestIssueNpe.main(TestIssueNpe.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.NullPointerException
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:418)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:274)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:270)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:626)
	... 9 more
```

**Comment by LNAmp** [comment]
fixed
