### ISSUE TITLE
default constructor not found

### ISSUE THREAD

**Issue by zenochan** [alibaba/fastjson#1471]

**Comment by zenochan** [comment]
想搜索的手太快，1.1.63.android kotlin 有noArgs 构造方法还是跑了 default constructor not found 异常， 1.1.61.android 能正常解析，不知道是啥变化了

```
default constructor not found. class com.churgo.market.data.models.Res
at com.alibaba.fastjson.parser.JavaBeanInfo.build(JavaBeanInfo.java:475)
at com.alibaba.fastjson.parser.JavaBeanDeserializer.<init>(JavaBeanDeserializer.java:35)
at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:216)
at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:150)
at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:683)
at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:659)
at com.alibaba.fastjson.JSON.parseObject(JSON.java:212)
at com.alibaba.fastjson.JSON.parseObject(JSON.java:184)
```

**Comment by zenochan** [comment]
#1451 应该与这个是相同的问题
