### ISSUE TITLE
序列化 "2017-06-28T07:20:05.000+05:30" 报错

### ISSUE THREAD

**Issue by plaxj** [alibaba/fastjson#1482]
https://github.com/alibaba/fastjson/blob/0818ecf14649b2893b486441f685ed8eb2ffd510/src/main/java/com/alibaba/fastjson/parser/JSONScanner.java#L583

**Comment by plaxj** [comment]
Exception in thread "main" java.lang.NumberFormatException: For input string: "2017-06-27T07:12:41.000+05:30"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at com.alibaba.fastjson.serializer.DateCodec.cast(DateCodec.java:202)
	at com.alibaba.fastjson.parser.deserializer.AbstractDateDeserializer.deserialze(AbstractDateDeserializer.java:142)
	at com.alibaba.fastjson.parser.deserializer.AbstractDateDeserializer.deserialze(AbstractDateDeserializer.java:19)
	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:71)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:888)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:633)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:1070)

**Comment by wenshao** [comment]
谢谢反馈，问题已修复，预计在国庆期间会发布新版本解决问题

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.39
问题已经修复，请用新版本
