### ISSUE TITLE
com.alibaba.fastjson.JSONException: syntax error, expect {, actual string, pos 917

### ISSUE THREAD

**Issue by zzwb** [alibaba/fastjson#1486]
我发现这个出错是因为json里有一个songList,一个songlist 这样两个key,我的实体类里只写了songList（songlist这个字段不需要）。

1.2.32  处理json  songlist这个key时，匹配到是类型是songList
1.2.36  在抛出这个异常之前有一个空指针

**Comment by wenshao** [comment]
能提供异常错误堆栈信息么？

**Comment by zzwb** [comment]
1.2.32 
`Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error, expect {, actual string, pos 917
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:370)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:1070)
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_2_DigitalSongPlatform.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:211)
	at com.alibaba.fastjson.parser.deserializer.ArrayListTypeFieldDeserializer.parseArray(ArrayListTypeFieldDeserializer.java:178)
	at com.alibaba.fastjson.parser.deserializer.ArrayListTypeFieldDeserializer.parseField(ArrayListTypeFieldDeserializer.java:65)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:888)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:633)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:1070)
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_1_DigitalAlbumPlatform.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:211)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:726)
	at com.alibaba.fastjson.serializer.CollectionCodec.deserialze(CollectionCodec.java:120)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:642)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:354)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:322)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:236)
        at com.XXX.service.XXX.XXX(XXX.java:97)
`

1.2.36
`Exception in thread "main" com.alibaba.fastjson.JSONException
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:627)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:361)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:329)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:243)
	at com.XXX.service.XXX.XXX(XXX.java:97)
Caused by: java.lang.NullPointerException
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:413)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:1146)
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_2_DigitalSongPlatform.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:268)
	at com.alibaba.fastjson.parser.deserializer.ArrayListTypeFieldDeserializer.parseArray(ArrayListTypeFieldDeserializer.java:178)
	at com.alibaba.fastjson.parser.deserializer.ArrayListTypeFieldDeserializer.parseField(ArrayListTypeFieldDeserializer.java:65)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:973)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:718)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:1146)
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_1_DigitalAlbumPlatform.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:268)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:709)
	at com.alibaba.fastjson.serializer.CollectionCodec.deserialze(CollectionCodec.java:120)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:623)
	... 5 more`

**Comment by zzwb** [comment]
1.2.32
代码是这个样子的  如果注释掉songlist属性,会报错，如果不住事 songList属性为null
`   public static void main(String[] args) {

        String json = "[{\"song_list\":[{\"val\":1,\"v_al\":2},{\"val\":2,\"v_al\":2},{\"val\":3,\"v_al\":2}], \"songlist\":\"v_al\"}]";
        List<Value> parseObject = JSON.parseObject(json, new TypeReference<List<Value>>() {
        });
        for (Value value : parseObject) {
            System.out.println(value.songList + "  " );

        }

    }

    public static class Value {
        @JSONField(alternateNames = {"song_list", "songList"})
        List<Value2> songList;

//        @JSONField(alternateNames = {"songlist"})
//        String songlist;

        public List<Value2> getSongList() {
            return songList;
        }

        public void setSongList(List<Value2> songList) {
            this.songList = songList;
        }

//        public String getSonglist() {
//            return songlist;
//        }
//
//        public void setSonglist(String songlist) {
//            this.songlist = songlist;
//        }
    }

    public static class Value2 {
        int val;

        int v_al;

        public int getVal() {
            return val;
        }

        public void setVal(int val) {
            this.val = val;
        }

        public int getV_al() {
            return v_al;
        }

        public void setV_al(int v_al) {
            this.v_al = v_al;
        }

        @Override
        public String toString() {
            return "Value2{" +
                    "val=" + val +
                    ", v_al=" + v_al +
                    '}';
        }
    }`

**Comment by miscsstake** [comment]
我也遇到类似的问题：

报错信息：Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error, expect {, actual [, pos 1226, fastjson-version 1.2.70

测试数据:
```java
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class TestNameDTO {
	private String a;
	private List<List<String>> b;
}

public static void main(String[] args) {
		String name = "[{\"mdmCode\":\"V2019016269\",\"userList\":[[\"30528469\",\"29405035\"],[\"30528337\",\"29390957\"]]},{\"mdmCode\":\"V2022002341\",\"userList\":[[\"30550065\",\"29405035\"],[\"30528337\",\"29390957\"]]},{\"mdmCode\":\"V2021042689\",\"userList\":[[\"30586821\",\"29405035\"],[\"30528337\",\"29390957\"]]},{\"mdmCode\":\"V2022003368\",\"userList\":[[\"29373641\",\"30396818\"],[\"30528337\",\"29390957\"]]},{\"mdmCode\":\"V2022003367\",\"userList\":[[\"30586821\",\"30396818\"],[\"30528337\",\"29390957\"]]},{\"mdmCode\":\"V2021042688\",\"userList\":[[\"30528469\",\"29405035\"],[\"30528337\",\"29390957\"]]},{\"mdmCode\":\"V2022002344\",\"userList\":[[\"29373641\",\"29405035\"],[\"30528337\",\"29390957\"]]},{\"mdmCode\":\"V2023013243\",\"userList\":[[\"20174120\"],[\"26763937\"]]},{\"mdmCode\":\"V2022011174\",\"userList\":[[\"20174120\"],[\"26763937\"]]},{\"mdmCode\":\"V2022005503\",\"userList\":[[\"20174120\"],[\"26763937\"]]},{\"mdmCode\":\"V2022001155\",\"userList\":[[\"23102085\",\"26706279\"],[\"26776274\"]]},{\"mdmCode\":\"C200503113\",\"userList\":[[\"23102085\",\"26706279\"],[\"26776274\"]]},{\"mdmCode\":\"V2023000133\",\"userList\":[[\"30512455\"],[\"26795634\"]]},{\"mdmCode\":\"V2022005172\",\"userList\":[[\"30512455\"],[\"26795634\"]]},{\"mdmCode\":\"V2022004505\",\"userList\":[[\"30280956\"],[\"29022631\",\"26556487\"]]},{\"mdmCode\":\"V2022004088\",\"userList\":[[\"30057619\"],[\"28818553\"]]},[{\"mdmCode\":\"V2019016269\",\"userList\":[[\"30528469\",\"29405035\"],[\"30528337\",\"29390957\"]]},{\"mdmCode\":\"V2022002341\",\"userList\":[[\"30550065\",\"29405035\"],[\"30528337\",\"29390957\"]]},{\"mdmCode\":\"V2021042689\",\"userList\":[[\"30586821\",\"29405035\"],[\"30528337\",\"29390957\"]]},{\"mdmCode\":\"V2022003368\",\"userList\":[[\"29373641\",\"30396818\"],[\"30528337\",\"29390957\"]]},{\"mdmCode\":\"V2022003367\",\"userList\":[[\"30586821\",\"30396818\"],[\"30528337\",\"29390957\"]]},{\"mdmCode\":\"V2021042688\",\"userList\":[[\"30528469\",\"29405035\"],[\"30528337\",\"29390957\"]]},{\"mdmCode\":\"V2022002344\",\"userList\":[[\"29373641\",\"29405035\"],[\"30528337\",\"29390957\"]]},{\"mdmCode\":\"V2023013243\",\"userList\":[[\"20174120\"],[\"26763937\"]]},{\"mdmCode\":\"V2022011174\",\"userList\":[[\"20174120\"],[\"26763937\"]]},{\"mdmCode\":\"V2022005503\",\"userList\":[[\"20174120\"],[\"26763937\"]]},{\"mdmCode\":\"V2022001155\",\"userList\":[[\"23102085\",\"26706279\"],[\"26776274\"]]},{\"mdmCode\":\"C200503113\",\"userList\":[[\"23102085\",\"26706279\"],[\"26776274\"]]},{\"mdmCode\":\"V2023000133\",\"userList\":[[\"30512455\"],[\"26795634\"]]},{\"mdmCode\":\"V2022005172\",\"userList\":[[\"30512455\"],[\"26795634\"]]},{\"mdmCode\":\"V2022004505\",\"userList\":[[\"30280956\"],[\"29022631\",\"26556487\"]]},{\"mdmCode\":\"V2022004088\",\"userList\":[[\"30057619\"],[\"28818553\"]]}],{\"mdmCode\":\"V2022004837\",\"userList\":[[\"30507887\"]]},{\"mdmCode\":\"V2022001958\",\"userList\":[[\"30507887\"]]},{\"mdmCode\":\"V2022004049\",\"userList\":[[\"29419309\"],[\"26556487\"]]},{\"mdmCode\":\"V2022001979\",\"userList\":[[\"29366404\"]]},{\"mdmCode\":\"V2022001333\",\"userList\":[[\"29369283\"]]},{\"mdmCode\":\"V2022001318\",\"userList\":[[\"29369396\"]]},{\"mdmCode\":\"V2022001322\",\"userList\":[[\"29369437\"]]},{\"mdmCode\":\"V2022001329\",\"userList\":[[\"29367102\"]]},{\"mdmCode\":\"V2023013873\",\"userList\":[[\"20174120\"],[\"30391461\"]]},{\"mdmCode\":\"V2022006187\",\"userList\":[[\"20174120\"],[\"30391461\"]]},{\"mdmCode\":\"V2022005972\",\"userList\":[[\"20174120\"],[\"30391461\"]]},{\"mdmCode\":\"V2022001321\",\"userList\":[[\"29369200\"]]},{\"mdmCode\":\"V2022003880\",\"userList\":[[\"29414700\"],[\"29258623\"]]},{\"mdmCode\":\"V2022001331\",\"userList\":[[\"29388396\"]]},{\"mdmCode\":\"V2022002375\",\"userList\":[[\"29373168\"]]},{\"mdmCode\":\"V2022002378\",\"userList\":[[\"29373833\"]]},{\"mdmCode\":\"C211203792\",\"userList\":[[\"29373538\"]]},{\"mdmCode\":\"V2022002364\",\"userList\":[[\"29373107\"]]},{\"mdmCode\":\"V2022002338\",\"userList\":[[\"29373833\"]]},{\"mdmCode\":\"V2022003478\",\"userList\":[[\"30581171\"],[\"29258623\"]]},{\"mdmCode\":\"C211203780\",\"userList\":[[\"29369797\"]]},{\"mdmCode\":\"V2022001069\",\"userList\":[[\"29369797\"]]},{\"mdmCode\":\"V2022001070\",\"userList\":[[\"29369797\"]]},{\"mdmCode\":\"V2022001316\",\"userList\":[[\"29369797\"]]},{\"mdmCode\":\"V2022001952\",\"userList\":[[\"29369797\"]]},{\"mdmCode\":\"V2022004134\",\"userList\":[[\"29031882\"],[\"28818553\"]]},{\"mdmCode\":\"V2022001340\",\"userList\":[[\"29367527\"]]},{\"mdmCode\":\"V2022001342\",\"userList\":[[\"29389231\"]]},{\"mdmCode\":\"V2022001330\",\"userList\":[[\"29367507\"]]},{\"mdmCode\":\"V2022001326\",\"userList\":[[\"30620306\"]]},{\"mdmCode\":\"C211203779\",\"userList\":[[\"29403876\"]]},{\"mdmCode\":\"V2022001346\",\"userList\":[[\"29403876\"]]},{\"mdmCode\":\"V2022002114\",\"userList\":[[\"29403876\"]]},{\"mdmCode\":\"V2022002340\",\"userList\":[[\"29403876\"]]}]";
		List<TestNameDTO> nameDTOList = JSON.parseObject(name, new TypeReference<List<TestNameDTO>>() {
		});
}
```
