### ISSUE TITLE
Map null key值序例化空指针

### ISSUE THREAD

**Issue by Luckywb** [alibaba/fastjson#1503]
版本1.2.38

```
static {
    ParserConfig.getGlobalInstance().setAutoTypeSupport(true);
}

public static class Bean {

}

@Test
public void test() {
    Map<Long, Bean> map = new HashMap<>();
    map.put(null, new Bean());
    Map<Long, Bean> rmap = (Map<Long, Bean>) JSON.parse(JSON.toJSONString(map, SerializerFeature.WriteClassName));
    System.out.println(rmap);
}
```
```
java.lang.NullPointerException
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:518)
	at com.alibaba.fastjson.parser.deserializer.MapDeserializer.deserialze(MapDeserializer.java:64)
	at com.alibaba.fastjson.parser.deserializer.MapDeserializer.deserialze(MapDeserializer.java:41)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:358)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1321)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1287)
	at com.alibaba.fastjson.JSON.parse(JSON.java:139)
	at com.alibaba.fastjson.JSON.parse(JSON.java:130)
	at com.yhtframework.utils.third.FastjsonUtilsTest.test(FastjsonUtilsTest.java:63)
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.39
问题已经修复，请用新版本
