### ISSUE TITLE
com.alibaba.fastjson.JSONException: can not get javaBeanDeserializer. int

### ISSUE THREAD

**Issue by Huang-Jinxian** [alibaba/fastjson#1539]
json转对象的时候报这个异常`com.alibaba.fastjson.JSONException: can not get javaBeanDeserializer. int`
```
Caused by: com.alibaba.fastjson.JSONException: can not get javaBeanDeserializer. int
	at com.alibaba.fastjson.util.TypeUtils.castToJavaBean(TypeUtils.java:1002)
	at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:652)
	at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:831)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.createInstance(JavaBeanDeserializer.java:889)
	at com.alibaba.fastjson.util.TypeUtils.castToJavaBean(TypeUtils.java:1000)
	... 99 common frames omitted
Caused by: com.alibaba.fastjson.JSONException: can not get javaBeanDeserializer. int
	at com.alibaba.fastjson.util.TypeUtils.castToJavaBean(TypeUtils.java:997)
	... 103 common frames omitted
```
这是部分的json
```
{
    "updatetime": 1452265573,
    "copy_count": 50,
    "paperid": 0,
    "categoryid": 30624,
    "id": 140515,
    "favorite_count": 11,
    "datetime": 1399341833,
    "comment_count": 13,
    "publishid": 0,
    "view_count": 5492
  }
```

**Comment by zhou-hao** [comment]
同样的问题 can not get javaBeanDeserializer. java.lang.Integer

**Comment by velowang** [comment]
也是同样的问题

**Comment by Huang-Jinxian** [comment]
我用gson解决了，完全没有这个问题

**Comment by menggudaoke** [comment]
升级到最新版本就OK了。
