### ISSUE TITLE
fastjson1.2.2版本遇到一个问题,使用json_simple1.1解析没有问题,使用fastjson解析报错(规律就是不能解析包含反斜杠的字符)

### ISSUE THREAD

**Issue by mrccao** [alibaba/fastjson#1579]
com.alibaba.fastjson.JSONException: unclosed string : 萌
	at com.alibaba.fastjson.parser.JSONLexerBase.scanString(JSONLexerBase.java:999)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:393)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1071)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:418)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1236)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1205)
	at com.alibaba.fastjson.JSON.parse(JSON.java:108)
	at com.alibaba.fastjson.JSON.parse(JSON.java:99)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:170)
	at com.zyhq.tms.gate.service.core.pos.HuofenghuangPosApiMangager.getFilms(HuofenghuangPosApiMangager.java:421)
	at com.zyhq.tms.gate.service.core.pos.HuofenghuangPosApiMangager.main(HuofenghuangPosApiMangager.java:607)

"青蛙小�\萌与妈妈意外"萌前面有一个反斜杠,解析报错,而json_simple不会报错

json串如下:
{
    "code": "1005",
    "version": "1.0.0.0",
    "serialNumber": "821e0128-c3ba-4056-b28b-c551f5a04a54",
    "result": 0,
    "films": [
         {
            "filmCode": "001b02662016",
            "filmCd": "001b0266201601",
            "promotion": "",
            "dimensional": "2D",
            "carrierCd": "2",
            "carrierName": "数字",
            "syopsis": "影片讲述了萌萌哒青蛙家族一直快乐的生活在美丽的大沼泽里，但是一群牛蛙的到来，让青蛙家族陷入了空前的危机中，在抵抗牛蛙逃亡之时，青蛙小�\萌与妈妈意外走散了，而大沼泽周围即将建设的人类工厂更让青蛙家族无处安家，不得不集体迁徙，立志找到妈妈的小黑萌无奈跟随着青蛙家族一起去寻找属于它们的桃花源，在充满着未知与危机的路途上，小黑萌到底能否寻找到妈妈呢？",
            "filmDuration": 74,
            "filmLongTitle": "青蛙总动员",
            "filmShortTitle": "青蛙总动员",
            "filmEnglishTitle": "",
            "languageCd": "CN",
            "languageName": "国语",
            "showDateOut": "2016-05-03",
            "image": null,
            "filmVerson": "b",
            "hasImageFlg": false,
            "mainStars": "吉静 Jing Ji / 郭政建 Zhengjian Guo / 白涛 Tao Bai / 王秋明 Qiuming Wang / 谷峰 Feng Ku / 滕奎兴 Kuixing Teng / 李金燕 Jinyan Li"
        },
    ]
}

**Comment by wenshao** [comment]
这个不符合JSON语法规范哦，报错是合适，json_simple1.1如果不报错，那才应该是不恰当的。
