### ISSUE TITLE
Map.Entry 反序列化异常，

### ISSUE THREAD

**Issue by radcat1987** [alibaba/fastjson#1583]
如题目， 在序列化后，反序列化异常，异常信息如下

`Exception in thread "main" com.alibaba.fastjson.JSONException: expect string
	at com.alibaba.fastjson.serializer.MiscCodec.deserialze(MiscCodec.java:265)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:712)
	at com.alibaba.fastjson.serializer.CollectionCodec.deserialze(CollectionCodec.java:120)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:626)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:348)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:316)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:230)
	at MapToJson.main(MapToJson.java:31)`

源代码如下：
```java
Map<String, List<String>> totalMap = new HashMap<>();
for (int i = 0; i < 10; i++) {
	List<String> list = new ArrayList<>();
	for (int j = 0; j < 2; j++) {
		list.add("list" + j);
	}
	totalMap.put("map" + i, list);
}
List<Map.Entry<String, List<String>>> mapList = new ArrayList<>(totalMap.entrySet());
List<Map<String, List<String>>> mapList1 = new ArrayList<>();
mapList1.add(totalMap);
String jsonString = JSON.toJSONString(mapList1, SerializerFeature.DisableCircularReferenceDetect);
System.out.println(jsonString);
List<Map.Entry<String, List<String>>> parse = JSON.parseObject(jsonString, new TypeReference<List<Map.Entry<String, List<String>>>>() {});
System.out.println(parse);
```

使用环境：fastjson-1.2.40

**Comment by wenshao** [comment]
已增强对Map.Entry反序列化的支持

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.41
新版本已经支持，请使用新版本
