### ISSUE TITLE
JSONPath throw UnsupportedOperationException

### ISSUE THREAD

**Issue by kid1412z** [alibaba/fastjson#1587]
`JSONPath.set()` set key including `-` throws `UnsupportedOperationException`
```java
public static void main(String[] args) {

        JSONObject aa= new JSONObject();
        aa.put("app-a", "haj ");
        JSONPath.set(aa, "$.app-a.x", "123");
        
```

```text
Exception in thread "main" java.lang.UnsupportedOperationException
  at com.alibaba.fastjson.JSONPath$JSONPathParser.readSegement(JSONPath.java:387)
  at com.alibaba.fastjson.JSONPath$JSONPathParser.explain(JSONPath.java:889)
  at com.alibaba.fastjson.JSONPath.init(JSONPath.java:66)
  at com.alibaba.fastjson.JSONPath.set(JSONPath.java:216)
  at com.alibaba.fastjson.JSONPath.set(JSONPath.java:281)
  at com.xxxxx.main(VideoTaskService.java:407)
```

**Comment by wenshao** [comment]
```java
JSONPath.set(aa, "$.app\\-a\\.x", "123");
```
需要做转义符处理

**Comment by kid1412z** [comment]
多谢
