### ISSUE TITLE
fastjson调用writeToEx时返回MalformedInputException异常. 

### ISSUE THREAD

**Issue by longzl2015** [alibaba/fastjson#1592]
有一份gbk的文件csvFile，当使用错误的编码utf-8去解析生成dto后。通过@RestController返回给前端时，出现MalformedInputException异常。
源文件地址：https://github.com/longzl2015/public/blob/master/fea.csv
```
 DwTablePreviewDto tablePreviewDto = new DwTablePreviewDto();
 List<List<Object>> records = new ArrayList<>();
 LineIterator it = null;
 it = FileUtils.lineIterator(csvFile, "UTF-8");
 while (it.hasNext()) {
    String line = it.nextLine();
    readTextFile(line, records);
 }
 tablePreviewDto.setRecords(records);
return tablePreviewDto;
```
异常信息如下：
```
java.nio.charset.MalformedInputException: Input length = 1
	at com.alibaba.fastjson.util.IOUtils.encodeUTF8(IOUtils.java:626) ~[fastjson-1.2.32.jar:na]
	at com.alibaba.fastjson.serializer.SerializeWriter.encodeToUTF8(SerializeWriter.java:414) ~[fastjson-1.2.32.jar:na]
	at com.alibaba.fastjson.serializer.SerializeWriter.writeToEx(SerializeWriter.java:345) ~[fastjson-1.2.32.jar:na]
	at com.alibaba.fastjson.JSON.writeJSONString(JSON.java:798) ~[fastjson-1.2.32.jar:na]
	at com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter.writeInternal(FastJsonHttpMessageConverter.java:168) ~[fastjson-1.2.32.jar:na]
	at cn.com.bsfit.dm.conf.SwaggerFastJsonHttpMessageConverter.writeInternal(SwaggerFastJsonHttpMessageConverter.java:37) ~[classes/:na]
	at com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter.write(FastJsonHttpMessageConverter.java:238) ~[fastjson-1.2.32.jar:na]
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:231) ~[spring-webmvc-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:174) ~[spring-webmvc-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:81) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:113) ~[spring-webmvc-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) ~[spring-webmvc-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) ~[spring-webmvc-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at cn.com.bsfit.portal.service.UserFilter.doFilter(UserFilter.java:133) ~[bsfit-portal-2.0.0-20171013.063735-69-single.jar:2.0.0-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317) ~[spring-security-web-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127) ~[spring-security-web-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) ~[spring-security-web-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114) ~[spring-security-web-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) ~[spring-security-web-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.2.RELEASE.jar:4.2.2.RELEASE]
```

**Comment by kimmking** [comment]
这个bug的处理方式是：

> it = FileUtils.lineIterator(csvFile, "gbk");

**Comment by longzl2015** [comment]
额。。。。
目前的工程是这样的，前端允许用户上传 gbk和utf8的文件，但用户经常会把gbk文件当成utf8文件上传。所以出现了 `it = FileUtils.lineIterator(csvFile, "UTF-8")`这种情况，然后导致fastjson出现了MalformedInputException

**Comment by neil4dong** [comment]
那这个问题和FastJson无关的嘛。

**Comment by longzl2015** [comment]
好吧
