### ISSUE TITLE
请支持集合类型反序列化报错，　java.lang.UnsupportedOperationException ,谢谢。

### ISSUE THREAD

**Issue by suanping** [alibaba/fastjson#1603]
在应用　GenericFastJsonRedisSerializer　实现shiro 的 session 序列化，在反序化过程中报异常，

fastjson 版本：　１.２.４１
反序列化内容：　
```json
{
  "@type": "org.apache.shiro.session.mgt.SimpleSession",
  "attributeKeys": [
    "shiroSavedRequest"
  ],
  "attributes": {
    "@type": "java.util.HashMap",
    "shiroSavedRequest": {
      "@type": "org.apache.shiro.web.util.SavedRequest",
      "method": "GET",
      "requestURI": "/",
      "requestUrl": "/"
    }
  },
  "expired": false,
  "host": "0:0:0:0:0:0:0:1",
  "id": "04471851-7b22-4539-9d4b-ecc4e8423ce8",
  "lastAccessTime": 1511430200586,
  "startTimestamp": 1511430200586,
  "timeout": 1800000,
  "valid": true
}
```
异常：

java.lang.UnsupportedOperationException: null
	at java.util.AbstractCollection.add(AbstractCollection.java:262)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
	at com.alibaba.fastjson.parser.deserializer.FieldDeserializer.setValue(FieldDeserializer.java:92)
	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:118)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:728)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:271)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:267)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:370)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1335)
	at com.alibaba.fastjson.parser.deserializer.JavaObjectDeserializer.deserialze(JavaObjectDeserializer.java:45)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:640)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:365)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:328)
	at com.alibaba.fastjson.support.spring.GenericFastJsonRedisSerializer.deserialize(GenericFastJsonRedisSerializer.java:37)

**Comment by suanping** [comment]
请问这个问题是bug么。有什么好的解决建议！！

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.42
新版已发布，请使用新版本。
