### ISSUE TITLE
 java.lang.ClassCastException

### ISSUE THREAD

**Issue by haoxunwang** [alibaba/fastjson#1622]
并发请求几个接口，fastjson序列化就会出现` java.lang.ClassCastException`异常，像这种错误Fatal Exception: java.lang.ClassCastException: com.nelson.demo.model.CarListModel cannot be cast to com.nelson.demo.model.TaskListModel  
版本：com.alibaba:fastjson:1.1.60.android

**Comment by wenshao** [comment]
能提供完整堆栈信息么？

**Comment by haoxunwang** [comment]
截取了fabric线上的，页面并发请求几个接口就会出现，现在在callback做了try{}catch()处理了
`Fatal Exception: java.lang.ClassCastException: com.guazi.crm.business.seller.model.CarSourceOptionModel cannot be cast to com.guazi.crm.business.seller.model.CarSourceListModel
       at com.guazi.android.sales.base.vl.activity.CarSourceFragment$8.onChanged(CarSourceFragment.java:451)
       at com.guazi.android.sales.base.vl.activity.CarSourceFragment$8.onChanged(CarSourceFragment.java:446)
       at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:131)
       at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:148)
       at android.arch.lifecycle.LiveData.setValue(LiveData.java:294)
       at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
       at com.guazi.crm.business.common.source.CarSourceRepository$2.onSuccess(CarSourceRepository.java:49)
       at com.guazi.crm.business.common.oknet.retrofitapi.base.ResponseCallback.onResponse(ResponseCallback.java:51)
       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5665)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)`
