### ISSUE TITLE
oom toJSONString

### ISSUE THREAD

**Issue by beiliubei** [alibaba/fastjson#1626]
java.lang.OutOfMemoryError: Failed to allocate a 34530770 byte allocation with 16777216 free bytes and 26MB until OOM
	at com.alibaba.fastjson.serializer.SerializeWriter.expandCapacity(SerializeWriter.java:173)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeInt(SerializeWriter.java:313)
	at com.alibaba.fastjson.serializer.IntegerCodec.write(IntegerCodec.java:57)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:143)
	at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:170)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:262)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:509)

**Comment by wenshao** [comment]
which version?

**Comment by beiliubei** [comment]
#1730 重复，关闭

**Comment by nickylin** [comment]
我这边也遇到了toJsonString触发oom问题, 而且都集中在4.2.2机型上面, 不知为啥申请了100M数据,
