### ISSUE TITLE
default constructor not found   

### ISSUE THREAD

**Issue by abc20899** [alibaba/fastjson#1631]
use kotlin
 Caused by: com.alibaba.fastjson.JSONException: default constructor not found. class 
                                                                               at com.alibaba.fastjson.parser.JavaBeanInfo.build(JavaBeanInfo.java:496)
                                                                               at com.alibaba.fastjson.parser.JavaBeanDeserializer.<init>(JavaBeanDeserializer.java:35)
                                                                               at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:229)
                                                                               at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:148)
                                                                               at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:683)
                                                                               at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:659)
                                                                               at com.alibaba.fastjson.JSON.parseObject(JSON.java:238)
                                                                               at com.alibaba.fastjson.JSON.parseObject(JSON.java:210)
                                                                               at com.alibaba.fastjson.JSON.parseObject(JSON.java:169)
                                                                               at com.alibaba.fastjson.JSON.parseObject(JSON.java:278)

**Comment by wenshao** [comment]
please provide a testcase
