### ISSUE TITLE
反序列化后使用JSON对象获取JavaObject时，解析LocalDateTime发生错误

### ISSUE THREAD

**Issue by jzoe** [alibaba/fastjson#1645]
fastjson版本: 1.2.39

测试类:

```java
@Data
public class TestDateClass{
    String name;
    LocalDateTime testDateTime;
}
```

反序列化代码:
```java
    @Test
    public void testEnum() {
        String test = "{\"name\":\"test\",\"testDateTime\":\"2017-12-08 14:55:16\"}";

        //success
        logger.info(JSON.toJSONString(JSON.parseObject(test, TestDateClass.class), SerializerFeature.PrettyFormat));

        //fail
        logger.info(JSON.toJSONString(JSON.parseObject(test).toJavaObject(TestDateClass.class), SerializerFeature.PrettyFormat));
    }
```
结果:
```java
15:14:49.374 [main] INFO com.my.test.TestEnum - {
	"name":"test",
	"testDateTime":"2017-12-08 14:55:16"
}

com.alibaba.fastjson.JSONException: can not cast to : java.time.LocalDateTime

	at com.alibaba.fastjson.util.TypeUtils.castToJavaBean(TypeUtils.java:941)
	at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:644)
	at com.alibaba.fastjson.JSON.toJavaObject(JSON.java:971)
	at com.netease.mail.service.TestEnum.testRole(TestEnum.java:209)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.alibaba.fastjson.JSONException: can not cast to : java.time.LocalDateTime
	at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:745)
	at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:788)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.createInstance(JavaBeanDeserializer.java:1153)
	at com.alibaba.fastjson.util.TypeUtils.castToJavaBean(TypeUtils.java:939)
	... 25 more
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.44
问题解决，请使用新版本
