### ISSUE TITLE
jsonpath length()报错

### ISSUE THREAD

**Issue by zsf513** [alibaba/fastjson#1651]
$是一个json数组，使用$.length()报错，$.size()不报错，但是文档(https://github.com/alibaba/fastjson/wiki/JSONPath )中有length()的说明。
fastjson版本:1.2.42

com.alibaba.fastjson.JSONPathException: not support jsonpath : $.length()
	at com.alibaba.fastjson.JSONPath$JSONPathParser.readSegement(JSONPath.java:687)
	at com.alibaba.fastjson.JSONPath$JSONPathParser.explain(JSONPath.java:1290)
	at com.alibaba.fastjson.JSONPath.init(JSONPath.java:60)
	at com.alibaba.fastjson.JSONPath.eval(JSONPath.java:69)
	at com.alibaba.fastjson.JSONPath.eval(JSONPath.java:355)
	at com.szr.fastjson.test.FastJsonJunitTest.testJsonpath(FastJsonJunitTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.43
问题已修复，请使用新版本
