### ISSUE TITLE
对象转JSON时出错，非必现

### ISSUE THREAD

**Issue by HomHomLin** [alibaba/fastjson#1658]
偶现，感觉用起来没有了底气，能否看下什么原因？

E/UncaughtHandler: catch exception:com.alibaba.fastjson.JSONException: write javaBean error
                                                                               at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:620)
                                                                               at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:262)
                                                                               at com.alibaba.fastjson.JSON.toJSONString(JSON.java:620)
                                                                               at com.alibaba.fastjson.JSON.toJSONString(JSON.java:340)

**Comment by kimmking** [comment]
什么版本，出错代码跟目前版本对应不上。
试试最新版本。

**Comment by Harlber** [comment]
通遇到相同的问题
 - 版本：`compile 'com.alibaba:fastjson:1.1.51.android'`
 - 出现的问题：
在线程池中的一个任务遇到这个错误，会导致线程池意外销毁

跟踪了下代码，
```java
 /**
     * @since 1.2.9, back port to 1.1.49.android
     * @return
     */
    public static String toJSONString(Object object, // 
                                      SerializeConfig config, // 
                                      SerializeFilter[] filters, // 
                                      String dateFormat, //
                                      int defaultFeatures, // 
                                      SerializerFeature... features)
```

有try，没有catch，求大佬讲解下该思想
