### ISSUE TITLE
SymbolTable.addSymbol非线程安全的空指针异常

### ISSUE THREAD

**Issue by salten** [alibaba/fastjson#1659]
版本：1.1.38 异常信息： com.alibaba.fastjson.JSONException at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:517) at com.alibaba.fastjson.JSON.parseObject(JSON.java:244) at com.alibaba.fastjson.JSON.parseObject(JSON.java:220) at com.alibaba.fastjson.JSON.parseObject(JSON.java:179) at com.alibaba.fastjson.JSON.parseObject(JSON.java:327) at com.cmbc.FastJsonTest$1.run(FastJsonTest.java:30) at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.NullPointerException at com.alibaba.fastjson.parser.SymbolTable.addSymbol(SymbolTable.java:144) at com.alibaba.fastjson.parser.JSONScanner.addSymbol(JSONScanner.java:154) at com.alibaba.fastjson.parser.JSONLexerBase.scanSymbol(JSONLexerBase.java:797) at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:214) at com.alibaba.fastjson.parser.deserializer.MapDeserializer.deserialze(MapDeserializer.java:63) at com.alibaba.fastjson.parser.deserializer.MapDeserializer.deserialze(MapDeserializer.java:44) at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:513) ... 6 more

后发现该SymbolTable的addSymbol方法是非线程安全的。能否在1.1版本下(jdk1.7)能出一个修复版本？

**Comment by wenshao** [comment]
升级到1.2.42版本可以么？

**Comment by salten** [comment]
1.2.42我看build-jdk是1.8版本，看代码里面好像使用了jdk1.8的东西，我们生产上还在使用jdk1.7，暂时还不能升级jdk。1.2.42可以支持jdk1.7么？

**Comment by wenshao** [comment]
1.2.42支持JDK 1.6/1.7/1.8

**Comment by salten** [comment]
多谢温绍~~
