### ISSUE TITLE
请问Andriod代码混淆时，JSONException: default constructor not found，怎么破

### ISSUE THREAD

**Issue by xing-kenny** [alibaba/fastjson#167]
有如下数据结果，在代码混淆前，JSONObject.parseObject() 正常
    public class LoginStartBean implements Serializable {

```
    private static final long serialVersionUID = -436820542377254363L;
    public int code = 0;
    public String errormsg = "";
    public Data data;

    public class Data implements Serializable {
```

在进行代码混淆时，报错

```
 FATAL EXCEPTION: main
 com.alibaba.fastjson.JSONException: default constructor not found. class
 com.test.LoginStartBean$Data
at com.alibaba.fastjson.util.DeserializeBeanInfo.computeSetters(Unknown Source)
at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.<init>(Unknown Source)
at  com.alibaba.fastjson.parser.ParserConfig.createJavaBeanDeserializer(Unknown Source)
```

混淆声明如下：

```
-keep public class * implements java.io.Serializable {  
    public *;  
}  

-keepclassmembers class * implements java.io.Serializable {  
    static final long serialVersionUID;  
    private static final java.io.ObjectStreamField[] serialPersistentFields;  
    private void writeObject(java.io.ObjectOutputStream);  
    private void readObject(java.io.ObjectInputStream);  
    java.lang.Object writeReplace();  
    java.lang.Object readResolve();  
}   

 -libraryjars libs/fastjson-1.1.34.android.jar 
```

请问这个问题怎么破？

**Comment by halfhq** [comment]
加入static无效，请参考：#1173

**Comment by halfhq** [comment]
1.使用static类
2.创建一个interface IFastJson，将此类的全部implements IFastJson
3.在proguard.txt中配置

-keep class * implements com.xxxx.IFastJson { 
    public <init>(***);
}
