### ISSUE TITLE
DateCodec cast  日期格式兼容有问题

### ISSUE THREAD

**Issue by youxiaobing** [alibaba/fastjson#1679]
`
class User{
        Date create;

        public Date getCreate() {
            return create;
        }

        public void setCreate(Date create) {
            this.create = create;
        }
    }
`
版本：1.2.44
如果日期格式：{"create":"2018-01-10 08:30:00"} 这种解析没问题

如果日期格式: {"create":"2018-1-10 8:30:00"}  这种解析就会有问题  如果是1.2.20版本就没问题
`
Exception in thread "main" com.alibaba.fastjson.JSONException: For input string: "2018-1-10 8:30:00"
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:643)
	at com.alibaba.fastjson.parser.deserializer.MapDeserializer.parseMap(MapDeserializer.java:165)
	at com.alibaba.fastjson.parser.deserializer.MapDeserializer.deserialze(MapDeserializer.java:53)
	at com.alibaba.fastjson.parser.deserializer.MapDeserializer.deserialze(MapDeserializer.java:39)
	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:71)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:573)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:916)
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_1_ShoppingResult.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:184)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:639)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:339)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:243)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:456)
`

**Comment by wenshao** [comment]
我补充了testcase是好的啊

**Comment by zccccccc** [comment]
谢谢，果然把版本降下来就好了，fastjson 不维护了吗？ 这个应该是升级的bug把，我看最高版本也有这个问题
