### ISSUE TITLE
fastjson java.lang.StackOverflowError

### ISSUE THREAD

**Issue by terrytang2017** [alibaba/fastjson#1713]
null java.lang.StackOverflowError
	at com.alibaba.fastjson.serializer.SerializeWriter.writeFieldName(SerializeWriter.java:2014)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeFieldName(SerializeWriter.java:1996)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeFieldValue(SerializeWriter.java:1887)
	at com.alibaba.fastjson.serializer.ASMSerializer_140_QuerySKU.write(Unknown Source)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:196)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:367)
	at com.alibaba.fastjson.serializer.ASMSerializer_157_CombinedSkuData.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:367)
	at com.alibaba.fastjson.serializer.ASMSerializer_156_Item.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:367)
	at com.alibaba.fastjson.serializer.ASMSerializer_158_ItemSku.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:367)
	at com.alibaba.fastjson.serializer.ASMSerializer_156_Item.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:367)
	at com.alibaba.fastjson.serializer.ASMSerializer_158_ItemSku.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:367)
	at com.alibaba.fastjson.serializer.ASMSerializer_156_Item.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:367)
	at com.alibaba.fastjson.serializer.ASMSerializer_158_ItemSku.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:367)
	at com.alibaba.fastjson.serializer.ASMSerializer_156_Item.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:367)
	at com.alibaba.fastjson.serializer.ASMSerializer_158_ItemSku.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:367)
	at com.alibaba.fastjson.serializer.ASMSerializer_156_Item.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:367)
	at com.alibaba.fastjson.serializer.ASMSerializer_158_ItemSku.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:367)
	at com.alibaba.fastjson.serializer.ASMSerializer_156_Item.write(Unknown Source)

**Comment by joviqiao** [comment]
版本？？
