### ISSUE TITLE
Date with \n

### ISSUE THREAD

**Issue by Chad2li** [alibaba/fastjson#1766]
# Example: 
```
    @Test
    public void format()
    {
        // succ
        String json = "{\"name\":\"张三\"\n, \"birthday\":\"2017-01-01 01:01:01\"}";
        User user = JSON.parseObject(json, User.class);
        Assert.assertEquals("张三", user.getName());
        Assert.assertNotNull(user.getBirthday());

        // failed
        json = "{\"name\":\"张三\", \"birthday\":\"2017-01-01 01:01:02\"\n}";
        user = JSON.parseObject(json, User.class);// will exception
        Assert.assertEquals("张三", user.getName());
        Assert.assertNotNull(user.getBirthday());
    }

    public static class User
    {
        private String name;

        @JSONField(format = "yyyy-MM-dd HH:mm:ss")
        private Date birthday;

        public String getName()
        {
            return name;
        }

        public void setName(String name)
        {
            this.name = name;
        }

        public Date getBirthday()
        {
            return birthday;
        }

        public void setBirthday(Date birthday)
        {
            this.birthday = birthday;
        }
    }
```
# Exception:
```
com.alibaba.fastjson.JSONException: not match : - b

	at com.alibaba.fastjson.parser.JSONLexer.nextTokenWithChar(JSONLexer.java:194)
	at com.alibaba.fastjson.parser.JavaBeanDeserializer.parseExtra(JavaBeanDeserializer.java:1019)
	at com.alibaba.fastjson.parser.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:1001)
	at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:766)
	at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:116)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:686)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:659)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:238)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:210)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:169)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:278)

```

# Description
The first json has '\n' with the name, it will parse ok,
but the second's json has '\n' with the birthday, it will exception in parse.
why has different result with same operate.

**Comment by wenshao** [comment]
我测试1.2.47版本是好的，请问是什么版本？
