### ISSUE TITLE
fastjson 默认JSONObject内部实现为java.util.HashMap, 可能存在Race Condition

### ISSUE THREAD

**Issue by zhwbqd** [alibaba/fastjson#1771]
目前在排查线上cpu 100问题时, 意外发现在多线程使用fastsjon的jsonObject.get()时, 会导致cpu100情况, 相关调用栈情况如下. 应该是触发了java HashMap的race condition导致环形链表. 希望可以在Json.parseObject中增加线程安全Map的Feature或者参数
`
http-apr-8080-exec-4" daemon prio=10 tid=0x00007fedcc010000 nid=0x2b72 runnable [0x00007fed3e96e000]
   java.lang.Thread.State: RUNNABLE
	at java.util.HashMap.getEntry(HashMap.java:465)
	at java.util.HashMap.get(HashMap.java:417)
	at com.alibaba.fastjson.JSONObject.get(JSONObject.java:100)`

**Comment by LyZane** [comment]
附议
