### ISSUE TITLE
Json format identification error

### ISSUE THREAD

**Issue by yanzhenjie** [alibaba/fastjson#1775]
FastJSON version: 1.1.68.android, 1.1.64.android  and 1.1.62.android, other versions did not try.

This is a JSON string (not formatted for easy copy testing): 
```
{"data":{"id":32667,"user_id":758,"shop_id":1,"name":"按摩卡","cid":297,"cat_name":"其他","seller_cids":"1784","price":1,"market_price":39900,"pic_url":"http://mamaqunaer.oss-cn-shanghai.aliyuncs.com/user/758/42CeTiJaN5.jpg","qrcode_url":"http://mamaqunaer.oss-cn-shanghai.aliyuncs.com/qrcode/item/00b6ad034a7f7cd5d5cf46c3168ac50f.png","sold_quantity":6,"quantity":92,"is_recommend":1,"baby_gender":"1,2,3","baby_age":"1,2,3,4,5,6,7","score":"4.0000","status":1,"sort_order":100,"created_at":1521691842,"updated_at":1521705147,"consume_times":10,"expired_type":1,"expired_value":10,"contents":[{"id":"11","shop_id":"1","name":"小佳按摩","pic_url":"http://mamaqunaer.oss-cn-shanghai.aliyuncs.com/user/758/w6cdFiDkS5.jpg","price":"1","desc":"这是一家技术很好的洗浴中心","comment_count":"2","score":"4.0000","status":"1"},{"id":"33","shop_id":"1","name":"小丽按摩","pic_url":"http://mamaqunaer.oss-cn-shanghai.aliyuncs.com/user/758/zWPQhJJz4h.jpg","price":"1","desc":"大飞","comment_count":"0","score":"0.0000","status":"1"}],"is_collected":0,"imgs":[{"url":"http://mamaqunaer.oss-cn-shanghai.aliyuncs.com/user/758/42CeTiJaN5.jpg","position":0}],"commentStat":{"avg_score":"4.0000","score1_count":0,"score2_count":0,"score3_count":1,"score4_count":1,"score5_count":1,"total_count":3},"desc":""},"code":200,"message":"OK","success":true}
```

Here is the stack information at the time of the error:  

![qq 20180323110129](https://user-images.githubusercontent.com/13534988/37809339-ce8396fc-2e89-11e8-8b10-bff9dc1594c6.png)

```text
at com.alibaba.fastjson.parser.JSONLexer.scanSymbolUnQuoted(JSONLexer.java:953)
at com.alibaba.fastjson.parser.JSONLexer.scanSymbol(JSONLexer.java:740)
at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:594)
at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:116)
at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:686)
at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:659)
at com.alibaba.fastjson.JSON.parseObject(JSON.java:238)
at com.alibaba.fastjson.JSON.parseObject(JSON.java:210)
at com.alibaba.fastjson.JSON.parseObject(JSON.java:169)
at com.alibaba.fastjson.JSON.parseObject(JSON.java:278)
at com.zhimore.mama.base.http.EntityRequest.parseEntity(EntityRequest.java:33)
at com.zhimore.mama.base.http.EntityRequest.parseEntity(EntityRequest.java:21)
at com.zhimore.mama.base.http.AbstractRequest.parseResponse(AbstractRequest.java:141)
at com.zhimore.mama.base.http.AbstractRequest.parseResponse(AbstractRequest.java:42)
at com.yanzhenjie.nohttp.rest.RestProtocol.request(RestProtocol.java:66)
at com.yanzhenjie.nohttp.rest.SyncRequestExecutor.execute(SyncRequestExecutor.java:41)
at com.yanzhenjie.nohttp.rest.RequestDispatcher.run(RequestDispatcher.java:96)
```

----

This is some of the main test code:
```java
String json = ...;
JSONObject jsonObj = JSON.parseObject(json);
String dataJson = jsonObj.getString("data");
XXXInfo info = JSON.parseObject(dataJson, XXXInfo.class); // Here is an error.
```
**Note:** Due to business reasons, data needs to be parsed separately. Is it misused by me?

**Comment by yanzhenjie** [comment]
This error was caused by me. I did not correspond to the field type on my side.

The error hint may also need to be optimized. When GSON parsing is used later, it clearly indicates that the field type does not correspond.
