### ISSUE TITLE
Caused by: com.alibaba.fastjson.JSONException: can not cast to Timestamp, value : 2006-8-9

### ISSUE THREAD

**Issue by kenhan90** [alibaba/fastjson#1785]
Use Fastjson 1.2.47
Caused by: com.alibaba.fastjson.JSONException: can not cast to Timestamp, value : 2006-8-9
at com.alibaba.fastjson.util.TypeUtils.castToSqlDate(TypeUtils.java:412)
at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:750)
at com.bcss.poi.excel.utils.ExcelUtils.setProperty(ExcelUtils.java:1414)
at com.bcss.poi.excel.utils.ExcelUtils.readRow(ExcelUtils.java:424)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.49
问题已修复，请用新版本
