### ISSUE TITLE
json里出现反斜杠报错

### ISSUE THREAD

**Issue by llh6054** [alibaba/fastjson#1795]
你好，我们在使用的时候数据出现了反斜杠\报错了，这个是测试
```
import com.alibaba.fastjson.JSON;

public class test {

	public static void main(String[] args) {
		String str = "{\"current\":\"12\\发DDD\"}";
		System.out.println(JSON.parseObject(str));
	}
}
```
报错
```
Exception in thread "main" com.alibaba.fastjson.JSONException: unclosed string : 发
	at com.alibaba.fastjson.parser.JSONLexerBase.scanString(JSONLexerBase.java:999)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:393)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1236)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1205)
	at com.alibaba.fastjson.JSON.parse(JSON.java:108)
	at com.alibaba.fastjson.JSON.parse(JSON.java:99)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:170)
	at com.gpdi.infores.intf.cp.test.main(test.java:11)
```
期望的输出不应该是\\输出\吗

**Comment by llh6054** [comment]
\本身不符合json规范，每个工具的支持都不一样。
测试了net.sf.json会把两个都去掉，前端的话json-handle会保留一个，FE助手保留两个。
太想当然了，还是处理数据吧。
