### ISSUE TITLE
使用JSON.toJSONString(Object[] arr)异常

### ISSUE THREAD

**Issue by brinliu** [alibaba/fastjson#1819]
采用AOP记录日志时，在after方法中使用JSON.toJSONString(Object[] arr)，出现以下异常

o.a.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet][DirectJDKLog.java:182] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.alibaba.fastjson.JSONException: write javaBean error, fastjson version 1.2.47, class org.springframework.security.web.context.HttpSessionSecurityContextRepository$SaveToSessionResponseWrapper, write javaBean error, fastjson version 1.2.47, class org.springframework.security.web.firewall.FirewalledResponse, fieldName : response, getOutputStream() has already been called for this response] with root cause
java.lang.IllegalStateException: getOutputStream() has already been called for this response
        at org.apache.catalina.connector.Response.getWriter(Response.java:625)
        at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade.java:211)
        at com.alibaba.fastjson.serializer.ASMSerializer_15_ResponseFacade.write(Unknown Source)
        at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:298)
        at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:411)
        at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:120)
        at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:298)
        at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:411)
        at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:120)
        at com.alibaba.fastjson.serializer.ObjectArrayCodec.write(ObjectArrayCodec.java:103)
        at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:281)
        at com.alibaba.fastjson.JSON.toJSONString(JSON.java:673)
        at com.alibaba.fastjson.JSON.toJSONString(JSON.java:611)
        at com.alibaba.fastjson.JSON.toJSONString(JSON.java:576)

**Comment by everXu** [comment]
请问是什么原因呢？怎么解决的？

**Comment by chenzhiguo** [comment]
这个原因是什么呢？

**Comment by lixifun** [comment]
```java
    @RequestMapping("/hello")
    public void hello(HttpServletResponse response) {
        try {
            response.getOutputStream().write("hello".getBytes());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
```

出现的原因是，在 Controller 的方法列表里出现了 `HttpServletResponse` 类型的参数，在 aop 中尝试对这个参数调用 JSON.toJSONString(response) 了，这里会触发一次 getOutputStream() ，在 Controller 里也进行了这个操作，就是上面的报错了
