### ISSUE TITLE
泛型反序列化异常

### ISSUE THREAD

**Issue by zhangj311** [alibaba/fastjson#1822]
版本：1.2.30
ServerResult.java:
public class ServerResult<T extends Object> implements Serializable {
	private boolean rlt;
	private String message;
	private String code;
	private T data;
}
json串：{"code":"000000","data":1,"rlt":true,"message":"ok"}

正常代码：ServerResult<Integer> serverResult = JSON.parseObject(response, new TypeReference<ServerResult<Integer>>() {});

异常代码：ServerResult serverResult = JSON.parseObject(response, ServerResult.class);
FusionOrderAddressDto为自定义类。
异常信息，不是必现:       
com.alibaba.fastjson.JSONException: syntax error, expect {, actual int, pos 24, fieldName data
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:367)
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:1006)
        at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_50_FusionOrderAddressDto.deserialze(Unknown Source)
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:208)
        at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:71)

**Comment by kimmking** [comment]
JSON.parseObject(response, new TypeReference<ServerResult<Integer>>() {});
