### ISSUE TITLE
非常简单的操作~ 为啥会有空指针异常~?

### ISSUE THREAD

**Issue by wenerme** [alibaba/fastjson#183]
```
public class TestFJson
{
    interface IA
    {
        @JSONField(name = "wener")
        String getName();
//        @JSONField(name = "wener")
//        IA setName(String name);
    }
    @Data
    @Accessors(chain = true)
    class A implements IA
    {
        String name;
        int age;
    }

    @Test
    public void test()
    {
        A a = new A();
        a.setName("xiao").setAge(21);
        String result = JSON.toJSONString(a);
        A newA = JSON.parseObject(result, A.class);
        assert a.equals(newA);
    }
}
```

```
com.alibaba.fastjson.JSONException: create instance error, class json.TestFJson$A
    at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.createInstance(JavaBeanDeserializer.java:100)
    at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:303)
    at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:119)
    at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:514)
    at com.alibaba.fastjson.JSON.parseObject(JSON.java:244)
    at com.alibaba.fastjson.JSON.parseObject(JSON.java:220)
    at com.alibaba.fastjson.JSON.parseObject(JSON.java:179)
    at com.alibaba.fastjson.JSON.parseObject(JSON.java:327)
    at json.TestFJson.test(TestFJson.java:32)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
Caused by: java.lang.NullPointerException
    at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.createInstance(JavaBeanDeserializer.java:97)
    ... 29 more
```

生成的时候 考虑到了 `JSONField`, 第一次生成结果为 `{"age":21,"wener":"xiao"}`,为啥会有空指针异常? 即便是不注释 IA 的 setName 也是这样.

**Comment by HDHunter** [comment]
Yes,thanks very much .
