### ISSUE TITLE
执行JSON.parse(byte[])时有一定几率抛出异常

### ISSUE THREAD

**Issue by lasting0001** [alibaba/fastjson#1855]
**FastJSON版本**：1.2.8

**堆栈信息如下：**
```
com.hitalk.h5.util.JsonUtil.parse(JsonUtil.java:143)
集合反序列化错误,jsonStr：{"_idx":1,"eng_name":"fxhf.s193","_k":"W4gfKHlq1t2ec5ca"} 
java.lang.NullPointerException
        at com.alibaba.fastjson.parser.SymbolTable.addSymbol(SymbolTable.java:144)
        at com.alibaba.fastjson.parser.JSONScanner.addSymbol(JSONScanner.java:158)
        at com.alibaba.fastjson.parser.JSONLexerBase.scanSymbol(JSONLexerBase.java:860)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:220)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1241)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1210)
        at com.alibaba.fastjson.JSON.parse(JSON.java:148)
        at com.alibaba.fastjson.JSON.parse(JSON.java:132)
        at com.alibaba.fastjson.JSON.parse(JSON.java:119)
```

**代码如下：**
```
	public final static Object parse(byte[] bs) {
		Object obj = null;
		try {
			obj = JSON.parse(bs, Feature.AllowISO8601DateFormat);
		} catch (Exception e) {
			try {
				Log.error("集合反序列化错误,jsonStr：" + new String(bs, "UTF-8"), e);
			} catch (UnsupportedEncodingException e1) {
				Log.error("", e);
			}
		}
		return obj;
	}
```
看了源码，没有看出问题，麻烦各位大大帮忙看看

**Comment by SnowOnion** [comment]
你能否确定一个 `byte[] bs`，使得 `JSON.parse(bs, Feature.AllowISO8601DateFormat)` **有时**会抛异常？
能否进一步给一个你觉得有可能的复现方式？
