### ISSUE TITLE
Rejected access for beyond hit limit per minute

### ISSUE THREAD

**Issue by lyzq** [alibaba/fastjson#1867]
具体异常：
Caused by: com.alibaba.fastjson.JSONException: syntax error, pos 1, json : Rejected access for beyond hit limit per minute, max limit is: 300.0
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1394)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1301)
	at com.alibaba.fastjson.JSON.parse(JSON.java:148)
	at com.alibaba.fastjson.JSON.parse(JSON.java:139)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:212)

使用fastjson的时候遇到这个问题，字面意思理解是 每分钟访问量超过了300，所以被拒绝了。但是不理解的是：
每分钟访问量是用来限制什么的？
该如何避免这个问题？

**Comment by superyouyo** [comment]
我也出现了，后来发现是Cat报错信息= =
