### ISSUE TITLE
想问下这个错误不知道是哪里的呢，乱码了，怎么解决呢

### ISSUE THREAD

**Issue by gaojiecai** [alibaba/fastjson#1872]
Caused by: java.lang.NumberFormatException: For input string: "7.jpg5b.jpgg������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������"

**Comment by gaojiecai** [comment]
接口返回的数据太多，没办法一个个排查，错误的log又定位不到具体哪个数据异常

**Comment by gaojiecai** [comment]
05-24 17:54:40.298 17279-23885/com.thestore.main W/System.err: Caused by: java.lang.NumberFormatException: For input string: "7.jpg5b.jpgg������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������"
05-24 17:54:40.298 17279-23885/com.thestore.main W/System.err:     at java.lang.Integer.parseInt(Integer.java:521)
05-24 17:54:40.298 17279-23885/com.thestore.main W/System.err:     at java.lang.Integer.parseInt(Integer.java:556)
05-24 17:54:40.298 17279-23885/com.thestore.main W/System.err:     at java.math.BigDecimal.<init>(BigDecimal.java:336)
05-24 17:54:40.298 17279-23885/com.thestore.main W/System.err:     at java.math.BigDecimal.<init>(BigDecimal.java:390)
05-24 17:54:40.298 17279-23885/com.thestore.main W/System.err:     at com.alibaba.fastjson.parser.JSONLexerBase.scanFieldDecimal(JSONLexerBase.java:3594)
05-24 17:54:40.299 17279-23885/com.thestore.main W/System.err:     at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:521)
05-24 17:54:40.299 17279-23885/com.thestore.main W/System.err:     at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:271)
05-24 17:54:40.299 17279-23885/com.thestore.main W/System.err:     at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:267)
05-24 17:54:40.299 17279-23885/com.thestore.main W/System.err:     at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:86)
05-24 17:54:40.299 17279-23885/com.thestore.main W/System.err:     at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:745)
05-24 17:54:40.299 17279-23885/com.thestore.main W/System.err:     at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:271)
05-24 17:54:40.299 17279-23885/com.thestore.main W/System.err:     at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:267)
05-24 17:54:40.299 17279-23885/com.thestore.main W/System.err:     at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:661)
05-24 17:54:40.299 17279-23885/com.thestore.main W/System.err: 	... 30 more
