### ISSUE TITLE
Spring5 环境下， 自引用的数据结构会出现死循环，导致内存溢出

### ISSUE THREAD

**Issue by apegeek** [alibaba/fastjson#1950]
```
public Menu {
    private String id;

    private String name;

    private List<Menu> children;
}
```
（fastjson version： 1.2.47）
这样的结构输出会带有$ref, 为了解决，加入
fastJsonConfig.setSerializerFeatures(SerializerFeature.DisableCircularReferenceDetect);

这样会出现内存溢出
Caused by: java.lang.StackOverflowError
	at com.alibaba.fastjson.serializer.SerializeWriter.writeFieldNameDirect(SerializeWriter.java:1544)
	at com.alibaba.fastjson.serializer.ASMSerializer_2_Menu.writeDirectNonContext(Unknown Source)
	at com.alibaba.fastjson.serializer.ASMSerializer_2_Menu.writeDirectNonContext(Unknown Source)
	at com.alibaba.fastjson.serializer.ASMSerializer_2_Menu.writeDirectNonContext(Unknown Source)
	at com.alibaba.fastjson.serializer.ASMSerializer_2_Menu.writeDirectNonContext(Unknown Source)
	at com.alibaba.fastjson.serializer.ASMSerializer_2_Menu.writeDirectNonContext(Unknown Source)

**Comment by apegeek** [comment]
sorry, 自己写入数据问题
