### ISSUE TITLE
仍然有特殊字符的问题，一直有，可能是\u00A0

### ISSUE THREAD

**Issue by xkaifei** [alibaba/fastjson#2070]
看了之前的isuuses 说是解决了，可现在还是有
业务数据比较大，无法查询到具体出现位置，fastjson版本是1.2.5
java.lang.ArrayIndexOutOfBoundsException: 160
	at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:683) ~[fastjson-1.2.5.jar:?]
	at com.alibaba.fastjson.serializer.SerializeWriter.writeFieldValueStringWithDoubleQuote(SerializeWriter.java:1232) ~[fastjson-1.2.5.jar:?]
	at com.alibaba.fastjson.serializer.SerializeWriter.writeFieldValue(SerializeWriter.java:1200) ~[fastjson-1.2.5.jar:?]
	at Serializer_19.write1(Unknown Source) ~[?:?]
	at Serializer_19.write(Unknown Source) ~[?:?]
	at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:127) ~[fastjson-1.2.5.jar:?]
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:188) ~[fastjson-1.2.5.jar:?]
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:390) ~[fastjson-1.2.5.jar:?]
	at Serializer_11.write1(Unknown Source) ~[?:?]
	at Serializer_11.write(Unknown Source) ~[?:?]
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:361) ~[fastjson-1.2.5.jar:?]
	at com.alibaba.fastjson.JSON.writeJSONStringTo(JSON.java:579) ~[fastjson-1.2.5.jar:?]

**Comment by xkaifei** [comment]
String sPstr = IntStream.range(1,1023).mapToObj(i->"=").collect(Collectors.joining()) + "\u4E2D\u56FD\u00A0\u4E2D";
        SerializeWriter writer = new SerializeWriter();
        JSON.writeJSONStringTo(sPstr, writer);
        System.out.println(writer.toString());
