### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.fastjson.serializer.SerializeConfig

### ISSUE THREAD

**Issue by house0128** [alibaba/fastjson#2099]
在项目里嵌入了一个日志调用链项目，项目中用了fastJson的1.1.33版本。有一个spring的项目引用了这个lib，报错，报错堆栈
    Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.fastjson.serializer.SerializeConfig
	at com.alibaba.fastjson.serializer.JSONSerializer.<init>(JSONSerializer.java:70)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:377)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:370)

但是如果在启动的时候，直接调用JSON.toJSONString  就不会报错，求解？

**Comment by wenshao** [comment]
多个版本存在冲突了
