### ISSUE TITLE
JsonPath 解析带 . 的key

### ISSUE THREAD

**Issue by shawzh** [alibaba/fastjson#2306]
我有一个json, 其中一段的key是 help_score_avg.cbm
用JSONPath.extract 提取, 这样写法也不行['help_score_avg.cbm'] 

把 . 去掉后可以正常解析

**Comment by shawzh** [comment]
com.alibaba.fastjson.JSONPathException: expect '], but '.'
        at com.alibaba.fastjson.JSONPath$JSONPathParser.accept(JSONPath.java:1620)
        at com.alibaba.fastjson.JSONPath$JSONPathParser.parseArrayAccessFilter(JSONPath.java:1413)
        at com.alibaba.fastjson.JSONPath$JSONPathParser.parseArrayAccess(JSONPath.java:783)
        at com.alibaba.fastjson.JSONPath$JSONPathParser.readSegement(JSONPath.java:756)
        at com.alibaba.fastjson.JSONPath$JSONPathParser.explain(JSONPath.java:1636)
        at com.alibaba.fastjson.JSONPath.init(JSONPath.java:61)
        at com.alibaba.fastjson.JSONPath.extract(JSONPath.java:86)
        at com.alibaba.fastjson.JSONPath.extract(JSONPath.java:542)
        at com.alibaba.fastjson.JSONPath.extract(JSONPath.java:548)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.57
问题已修复，请用新版本
