### ISSUE TITLE
com.alibaba.fastjson.JSONException: write <ConstraintDescriptorImpl> error 

### ISSUE THREAD

**Issue by gumutianqi** [alibaba/fastjson#2342]
`Caused by: com.alibaba.fastjson.JSONException: write javaBean error, fastjson version 1.2.56, class javax.validation.ConstraintViolationException, fieldName : errorData, write javaBean error, fastjson version 1.2.56, class org.hibernate.validator.internal.metadata.descriptor.ConstraintDescriptorImpl, fieldName : constraintDescriptor
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:523)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:160)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:314)
	at com.alibaba.fastjson.serializer.ASMSerializer_1_ApiResponse.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:285)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:731)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:669)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:634)
	at cn.sxw.commons.web.response.ApiResponse.toJSON(ApiResponse.java:121)
	at cn.sxw.commons.web.util.ResponseUtils.sendResponse(ResponseUtils.java:46)
	at cn.sxw.commons.config.exception.ErrorInfoBuilder.resolveException(ErrorInfoBuilder.java:444)
	at org.springframework.web.servlet.DispatcherServlet.processHandlerException(DispatcherServlet.java:1222)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1034)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	... 69 common frames omitted
Caused by: com.alibaba.fastjson.JSONException: write javaBean error, fastjson version 1.2.56, class org.hibernate.validator.internal.metadata.descriptor.ConstraintDescriptorImpl, fieldName : constraintDescriptor
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:523)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:160)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:314)
	at com.alibaba.fastjson.serializer.ASMSerializer_2_ConstraintViolationImpl.write(Unknown Source)
	at com.alibaba.fastjson.serializer.CollectionCodec.write(CollectionCodec.java:101)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:324)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:454)
	... 84 common frames omitted
Caused by: java.lang.AbstractMethodError: org.hibernate.validator.internal.metadata.descriptor.ConstraintDescriptorImpl.getValueUnwrapping()Ljavax/validation/metadata/ValidateUnwrappedValue;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alibaba.fastjson.util.FieldInfo.get(FieldInfo.java:491)
	at com.alibaba.fastjson.serializer.FieldSerializer.getPropertyValueDirect(FieldSerializer.java:149)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:291)
	... 90 common frames omitted
`

**Comment by collery** [comment]
Did you resolve it?
