### ISSUE TITLE
SupportArrayToBean反序列化报错

### ISSUE THREAD

**Issue by whitejava** [alibaba/fastjson#2351]
JDK版本：1.8.0_191
fastjson版本：1.2.56

复现代码如下：

``` java
import java.util.List;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.parser.Feature;
import com.alibaba.fastjson.serializer.SerializerFeature;

public class TestJsonArray {
    public static void main(String[] argv) {
        // 创建空白对象
        Bean1 c = new Bean1();

        // 序列化
        // 输出[null,null]
        String s = JSON.toJSONString(c, SerializerFeature.BeanToArray);
        System.out.println(s);

        // 反序列化报错
        // Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error, expect [, actual [
        JSON.parseObject(s, Bean1.class, Feature.SupportArrayToBean);
    }

    public static class Bean1 {

        private String a;

        private List<Bean2> b;

        public String getA() {
            return a;
        }

        public void setA(String a) {
            this.a = a;
        }

        public List<Bean2> getB() {
            return b;
        }

        public void setB(List<Bean2> b) {
            this.b = b;
        }
    }

    public static class Bean2  {
        private String c;

        public String getC() {
            return c;
        }

        public void setC(String c) {
            this.c = c;
        }
    }
}
```

完整报错信息：

```
Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error, expect [, actual [
	at com.alibaba.fastjson.parser.DefaultJSONParser.throwException(DefaultJSONParser.java:1431)
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_1_Bean1.deserialzeArrayMapping(Unknown Source)
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_1_Bean1.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:208)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:642)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:350)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:254)
```

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.57
问题已修复，请用新版本
