### ISSUE TITLE
fastjson 1.2.57版本部分机型闪退崩溃

### ISSUE THREAD

**Issue by xuchenchen** [alibaba/fastjson#2372]
![image](https://user-images.githubusercontent.com/5358531/56077411-837bea00-5e0e-11e9-8b8e-90d987ca5964.png)

调用：JSON.parseArray(“json字符串数据”, Map.class);

报错信息如下：
java.lang.NoSuchMethodError: No interface method getTypeName()Ljava/lang/String; in class Ljava/lang/reflect/Type; or its super classes (declaration of 'java.lang.reflect.Type' appears in /system/framework/core-oj.jar)
        at com.alibaba.fastjson.parser.deserializer.MapDeserializer.deserialze(MapDeserializer.java:32)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:776)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:710)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:705)
        at com.alibaba.fastjson.JSON.parseArray(JSON.java:593)

**Comment by wenshao** [comment]
Android版本建议使用1.1.70.android版本

**Comment by wenshao** [comment]
这个是因为用了JDK 1.8 API导致不兼容

**Comment by xuchenchen** [comment]
> 这个是因为用了JDK 1.8 API导致不兼容
非常感谢回答，希望能所有API能给予兼容，我目前暂时回退到上个版本，陆续在替换为GSON来替换fastJson目前回退上个版本和替换为Gson都能解决此问题
