### ISSUE TITLE
com.alibaba.fastjson.JSONException

### ISSUE THREAD

**Issue by amwei** [alibaba/fastjson#2388]
fastjson：1.2.57
spring：5.1.6.RELEASE

2 case：
### **case 1：**
```
  public class MaintenanceInterceptor extends HandlerInterceptorAdapter {

    private static final Logger LOGGER = LoggerFactory.getLogger(MaintenanceInterceptor.class);                                  

    @Override
    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
        if(handler instanceof HandlerMethod){
            HandlerMethod hm=(HandlerMethod)handler;
            LOGGER.info("JSON##1=="+JSON.toJSONString(hm));
```
throw：
```
com.alibaba.fastjson.JSONException: write javaBean error, fastjson version 1.2.57, class org.springframework.web.method.HandlerMethod$HandlerMethodParameter, fieldName : returnType
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:523)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:160)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:333)
	at com.alibaba.fastjson.serializer.ASMSerializer_1_HandlerMethod.write(Unknown Source)
	at com.alibaba.fastjson.serializer.ASMSerializer_1_HandlerMethod.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:285)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:731)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:669)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:634)
```

**### case 2：**
```
@ControllerAdvice
public class ResponseBodyAdviceChain implements ResponseBodyAdvice<MappingJackson2HttpMessageConverter> {
    
    
    private static final Logger LOGGER = LoggerFactory.getLogger(ResponseBodyAdviceChain.class);

    @Override
    public boolean supports(MethodParameter returnType, Class<? extends HttpMessageConverter<?>> converterType) {
        LOGGER.info("ResponseBodyAdviceChain="+JSON.toJSONString(returnType) );
        return false;
    }
```
**throw**
```
com.alibaba.fastjson.JSONException: write javaBean error, fastjson version 1.2.57, class org.springframework.web.method.HandlerMethod$ReturnValueMethodParameter, method : getParameter
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:523)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:160)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:285)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:731)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:669)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:634)
```

**Comment by wuwen5** [comment]
验证了一下，不建议去将一个非纯数据对象转json，不能试图把所有对象都能去转json，它包含特有的逻辑。例如case2 的问题。
完整的异常信息
```
Exception in thread "main" com.alibaba.fastjson.JSONException: write javaBean error, fastjson version 1.2.57, class org.springframework.web.method.HandlerMethod$ReturnValueMethodParameter, method : getParameter
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:523)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:160)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:285)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:731)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:669)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:634)
	at Demo.main(Demo.java:22)
Caused by: java.lang.IllegalStateException: Cannot retrieve Parameter descriptor for method return type
	at org.springframework.core.MethodParameter.getParameter(MethodParameter.java:232)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.alibaba.fastjson.util.FieldInfo.get(FieldInfo.java:491)
	at com.alibaba.fastjson.serializer.FieldSerializer.getPropertyValueDirect(FieldSerializer.java:149)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:291)
```


```
public Parameter getParameter() {
		if (this.parameterIndex < 0) {
			throw new IllegalStateException("Cannot retrieve Parameter descriptor for method return type");
		}
		Parameter parameter = this.parameter;
		if (parameter == null) {
			parameter = getExecutable().getParameters()[this.parameterIndex];
			this.parameter = parameter;
		}
		return parameter;
	}
```

使用jackson、gson 都一样的。 我不认为这是一个bug，而且不建议在fastjson中处理。
