### ISSUE TITLE
com.alibaba.fastjson.JSONException

### ISSUE THREAD

**Issue by xiaosalanqiao** [alibaba/fastjson#2483]
在使用过程中出现异常，错误信息如下：
com.alibaba.fastjson.JSONException: syntax error, expect {, actual 4
	at com.alibaba.fastjson.parser.MapDeserializer.parseMap(MapDeserializer.java:61)
	at com.alibaba.fastjson.parser.MapDeserializer.deserialze(MapDeserializer.java:44)
	at com.alibaba.fastjson.parser.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:73)
	at com.alibaba.fastjson.parser.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:1012)
	at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:770)
	at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:118)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:704)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:677)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:245)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:217)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:176)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:285)
	at hc.mhis.paic.com.essclibrary.activity.ESSCFaceDetectActivity$MsgThread.run(ESSCFaceDetectActivity.java:152)

**Comment by Omega-Ariston** [comment]
可以把你的testcase详细描述一下吗？
