### ISSUE TITLE
SerializeWriter 序列化的时候,多线程情况下 引发 ConcurrentModificationException

### ISSUE THREAD

**Issue by tone316** [alibaba/fastjson#2528]
报这个错, 事实上，只是对 同一个 object 调用了多次的 toJsonString(),  可以确定，序列化的时候出了问题
ConcurrentModificationException: null
	at java.util.ArrayList$SubList.checkForComodification(ArrayList.java:1231)
	at java.util.ArrayList$SubList.size(ArrayList.java:1040)
	at com.alibaba.fastjson.serializer.ASMSerializer_7_XXX.writeDirectNonContext(Unknown Source)
	at com.alibaba.fastjson.serializer.ASMSerializer_3_XXX.writeDirectNonContext(Unknown Source)
	at com.alibaba.fastjson.serializer.ASMSerializer_3_XXX.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:285)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:740)
	at com.alibaba.fastjson.JSON.toJSONStringWithDateFormat(JSON.java:670)

**Comment by tigerchicken** [comment]
toJsonString()应该只是读对象吧，按理不会报出ConcurrentModificationException吧，我猜测是toJsonString()操作某个非线程安全的集合对象的时候  业务其他线程正好再对该对象执行写操作，此时toJsonString()报出ConcurrentModificationException
