### ISSUE TITLE
带有Set成员变量的对象的反序列化问题

### ISSUE THREAD

**Issue by zwqlive** [alibaba/fastjson#254]
请问应该如何正确反序列化带有Set/HashSet成员的对象？
<pre>
<code>
public class PlayerParseTest{

public static void main(String[] args) {
		TestClass ts = new TestClass();
		ts.getHashSet().add(1);
		ts.getHashSet().add(4);
		String jsonStr = JSON.toJSONString(ts, new SerializerFeature[] {
            SerializerFeature.WriteClassName, SerializerFeature.DisableCircularReferenceDetect
        });
		System.out.println(jsonStr);
		ts = JSON.parseObject(jsonStr, TestClass.class);
		for (Integer val : ts.getHashSet()) {
			System.out.println(val);
		}
	}
}

public class TestClass {
	
	private Set<Integer> hashSet = new HashSet<Integer>();
	public TestClass() {
	}
	public Set<Integer> getHashSet() {
		return hashSet;
	}
	public void setHashSet(Set<Integer> hashSet) {
		this.hashSet = hashSet;
	}
}
</code></pre>

序列化完成后的数据是这样的
{"@type":"com.test.fastjson.TestClass","hashSet":Set[1,4]}

反序列化时候就报错
Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error, expect {, actual Set, pos 49
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:153)
	at com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer.parseRest(ASMJavaBeanDeserializer.java:104)
	at Fastjson_ASM_TestClass_1.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:505)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:214)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:174)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:291)
	at com.json.BaseJson.parseObject(Unknown Source)
	at com.game.utils.JsonUtil.parseObject(JsonUtil.java:95)
	at com.test.fastjson.PlayerParseTest.main(PlayerParseTest.java:28)

**Comment by zwqlive** [comment]
TestClass类中再加入一个成员Member，该成员类含有hashSet成员时,仍然有问题，不能正确的反序列化
序列化后的字符串为：
{"@type":"com.test.fastjson.TestClass","hashSet":Set[1,4],"list":[[1,2],[3,4]],"member":{"memIds":Set[]}}

反序列化时候报错：
Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error, expect {, actual Set, pos 98, fieldName member
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:232)
	at com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer.parseRest(ASMJavaBeanDeserializer.java:100)
	at Fastjson_ASM_Member_2.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:33)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:420)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:330)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:135)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:250)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:226)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:180)
	at com.test.fastjson.TestClass.testSet(TestClass.java:64)
	at com.test.fastjson.TestClass.main(TestClass.java:33)

**Comment by zwqlive** [comment]
目前办法还是需要替换掉Set之后才能正确的反序列化

**Comment by shellj** [comment]
我这试了两个版本(1.1.17和1.1.36)都没问题。
```json
{"@type":"com.test.FastJsonSetTest$TestClass","hashSet":Set[1,4],"member":{"members":Set[9,10]}}
1
4
9
10
```

**Comment by zwqlive** [comment]
public class FastJsonTest {

    public static void main(String[] args) {
        TestClass ts = new TestClass();
        ts.getHashSet().add(1);
        ts.getHashSet().add(4);
        ts.getMember().getHashSet().add(10);
        ts.getMember().getHashSet().add(15);
        String jsonStr = JSON.toJSONString(ts, new SerializerFeature[]{
                SerializerFeature.WriteClassName, SerializerFeature.DisableCircularReferenceDetect
        });
        System.out.println(jsonStr);
        ts = JSON.parseObject(jsonStr, TestClass.class);
        for (Integer val : ts.getHashSet()) {
            System.out.println(val);
        }
    }


    public static class TestClass {

        private Set<Integer> hashSet = new HashSet<Integer>();
        private Member member = new Member();

        public TestClass() {
        }

        public Set<Integer> getHashSet() {
            return hashSet;
        }

        public void setHashSet(Set<Integer> hashSet) {
            this.hashSet = hashSet;
        }

        public Member getMember() {
            return member;
        }

        public void setMember(Member member) {
            this.member = member;
        }
    }

    public static class Member{
        private Set<Integer> hashSet = new HashSet<Integer>();

        public Member() {
        }

        public Set<Integer> getHashSet() {
            return hashSet;
        }

        public void setHashSet(Set<Integer> hashSet) {
            this.hashSet = hashSet;
        }
    }
}

这是我的代码：
maven dependency:
<dependency>
          <groupId>com.alibaba</groupId>
          <artifactId>fastjson</artifactId>
          <version>1.1.36</version>
</dependency>
结果还是报错:
{"@type":"org.ngsoft.game.server.FastJsonTest$TestClass","hashSet":Set[1,4],"member":{"hashSet":Set[10,15]}}
Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error, expect {, actual Set, pos 67
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:212)
	at com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer.parseRest(ASMJavaBeanDeserializer.java:96)
	at Fastjson_ASM_TestClass_1.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:513)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:244)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:220)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:179)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:323)
	at org.ngsoft.game.server.FastJsonTest.main(FastJsonTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

**Comment by zwqlive** [comment]
@shellj 的代码我运行确实也没有问题，不知是不是因为我的member中的成员变量名称也是hashSet与TestClass中的hashSet同名导致的这个错

**Comment by wenshao** [comment]
bug fixed. it will include in 1.2.9
