### ISSUE TITLE
1.2.7.sec01升级到1.2.58后，RPC远程调用使用Hessian反序列化问题

### ISSUE THREAD

**Issue by guopengdreams** [alibaba/fastjson#2572]
场景（fastjson1.2.58，rpc调用序列化反序列化使用hessian）：
1、使用如下Json字符串（不规范的，1111111111111111111不是String）反序列化为Map。
```
String source = "{\"key\": {1111111111111111111: \"00000000011111111111111\"} }";
Map<String, Object> param =  JSONObject.parseObject(source, Map.class);
```
2、使用该param作为rpc调用参数调用，该参数中含有JSONObject对象，且该对象的内部Map中，存在key非String的情况1111111111111111111。
![豆芽图片20190718180045](https://user-images.githubusercontent.com/5554418/61448721-0076ac80-a986-11e9-8e73-8105d6d83b40.png)

3、调用到提供方后，hessian反序列化时，生成JSONObject报异常
Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
	at com.alibaba.fastjson.JSONObject.put(JSONObject.java:51)
	at com.caucho.hessian.io.MapDeserializer.readMap(MapDeserializer.java:114)
	at com.caucho.hessian.io.SerializerFactory.readMap(SerializerFactory.java:520)
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2117)
	at com.caucho.hessian.io.MapDeserializer.readMap(MapDeserializer.java:114)
	at com.caucho.hessian.io.SerializerFactory.readMap(SerializerFactory.java:522)
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2110)
	at com.caucho.hessian.io.BasicDeserializer.readLengthList(BasicDeserializer.java:599)
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:1782)
	at com.caucho.hessian.io.UnsafeDeserializer$ObjectFieldDeserializer.deserialize(UnsafeDeserializer.java:419)

原因分析：由于传递的Map中有非String的Key（1111111111111111111）。

通过在反序列化时增加Map<String, Object> param =  JSONObject.parseObject(source, Map.class, Feature.NonStringKeyAsString); 可以解决，但需要全盘回归代码。

请问对于升级到1.2.58后不兼容的问题，有什么好的解决办法？

**Comment by superchaos** [comment]
resources目录下增加fastjson.properties文件
增加内容：
parser.features.NonStringKeyAsString=true
即可

**Comment by wenshao** [comment]
可以使用1.2.7.sec04解决
