### ISSUE TITLE
序列化solr namedlist报错StackOverFlow

### ISSUE THREAD

**Issue by maoxiajun** [alibaba/fastjson#2582]
fastjson：1.2.51
jdk: oracle jdk 11.0.2
现象：调用JSON.toJSONString(response)抛StackOverFlow异常。
testcase：
```java
        QueryResponse response = new QueryResponse();
        response.setElapsedTime(200);
        SolrDocumentList sdl = new SolrDocumentList();
        sdl.setNumFound(100);
        sdl.setMaxScore(123.3f);
        for (int i = 0; i < 10; i++) {
            SolrDocument doc = new SolrDocument();
            doc.addField("id", i);
            doc.addField("name", "hello");
            doc.addField("tags", Arrays.asList(1, 2, 3));
            if (i == 5) {
                doc.addChildDocument(sdl.get(0));
            }
            sdl.add(doc);
        }

        NamedList<Object> debugInfo = new NamedList<>();
        debugInfo.add("q", "status:1");
        debugInfo.add("fq", "tag:1");
        NamedList<Object> explain = new NamedList<>();
        explain.add("score", "a:1, b:2");
        debugInfo.add("explain", explain);

        NamedList<Object> header = new NamedList<>();
        header.add("status", 200);
        header.add("QTime", 180);

        NamedList<Object> namedList = new NamedList<>();
        namedList.add("response", sdl);
        namedList.add("debug", debugInfo);
        namedList.add("responseHeader", header);
        response.setResponse(namedList);
       JSON.toJSONString(response);
```
依赖：solr 7.4.0
异常栈：
java.lang.StackOverflowError
	at java.base/java.util.IdentityHashMap.hash(IdentityHashMap.java:295)
	at java.base/java.util.IdentityHashMap.containsKey(IdentityHashMap.java:353)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.writeReference(JavaBeanSerializer.java:554)
	at com.alibaba.fastjson.serializer.ASMSerializer_2_NamedList.write(Unknown Source)
	at com.alibaba.fastjson.serializer.ASMSerializer_2_NamedList.write(Unknown Source)
	at com.alibaba.fastjson.serializer.ASMSerializer_2_NamedList.write(Unknown Source)
	at com.alibaba.fastjson.serializer.ASMSerializer_2_NamedList.write(Unknown Source)
	at com.alibaba.fastjson.serializer.ASMSerializer_2_NamedList.write(Unknown Source)
	at com.alibaba.fastjson.serializer.ASMSerializer_2_NamedList.write(Unknown Source)
	at com.alibaba.fastjson.serializer.ASMSerializer_2_NamedList.write(Unknown Source)
	at com.alibaba.fastjson.serializer.ASMSerializer_2_NamedList.write(Unknown Source)
	at com.alibaba.fastjson.serializer.ASMSerializer_2_NamedList.write(Unknown Source)
......

**Comment by nevergiveupzhang** [comment]
后来咋解决的？
