### ISSUE TITLE
请问怎样的数据才能复现以下异常？

### ISSUE THREAD

**Issue by jearton** [alibaba/fastjson#2622]
版本号：1.2.51

异常栈：

```
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
        at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
        at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
        at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
        at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
        at java.lang.reflect.Field.declaredAnnotations(Field.java:1150)
        at java.lang.reflect.Field.declaredAnnotations(Field.java:1148)
        at java.lang.reflect.Field.getAnnotation(Field.java:1120)
        at com.alibaba.fastjson.util.TypeUtils.computeGetters(TypeUtils.java:1739)
        at com.alibaba.fastjson.util.TypeUtils.buildBeanInfo(TypeUtils.java:1521)
        at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:98)
        at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:742)
        at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:415)
        at com.alibaba.fastjson.serializer.JSONSerializer.getObjectWriter(JSONSerializer.java:377)
        at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:130)
        at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:313)
        at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:454)
```

**Comment by Omega-Ariston** [comment]
> Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy

参考：https://blog.csdn.net/hengyunabc/article/details/79475505
希望对你有帮助
