### ISSUE TITLE
fastjson 栈溢出异常

### ISSUE THREAD

**Issue by CodePlayer** [alibaba/fastjson#263]
我使用的fastjson为最新的 1.2.3 (之前版本存在该问题，换到新版本也存在该问题) 。
使用 JSON.toJSONString(obj, SerializerFeature.DisableCircularReferenceDetect); 方法对Page对象进行JSON编码时出现循环递归栈溢出异常。部分异常代码如下：

java.lang.StackOverflowError
	at com.alibaba.fastjson.serializer.SerializerFeature.isEnabled(SerializerFeature.java:138)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.writeReference(JavaBeanSerializer.java:253)
	at Serializer_2.write1(Unknown Source)
	at Serializer_2.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:390)
	at Serializer_3.write1(Unknown Source)
	at Serializer_3.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:390)
	at Serializer_2.write1(Unknown Source)
	at Serializer_2.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:390)
	at Serializer_3.write1(Unknown Source)
	at Serializer_3.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:390)
	at Serializer_2.write1(Unknown Source)
	at Serializer_2.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:390)
	at Serializer_3.write1(Unknown Source)
	at Serializer_3.write(Unknown Source)

Page对象(数据分页对象)的结构如下(标准的Java Bean格式)：
int current
int size
int total
int pageCount
String orderBy
List list

其中 Page.list 存储的是多个 MessageTemplate 对象，其结构如下：
int id
MessageType type (MessageType是枚举类型，其中有一个私有的value属性)
String name
String content
User addUser (多个MessageTemplate对象的addUser属性是同一个对象)
Date addTime
int status

**Comment by wenshao** [comment]
没好办法，先关闭啦。如果你有想法再提issue.
