### ISSUE TITLE
ObjectDeserializer int value to enum not working

### ISSUE THREAD

**Issue by cotide** [alibaba/fastjson#2634]
## Protocal 

``` code
package io.github.test.protocal;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.annotation.JSONField;
import io.github.test.enums.MessageTypeu;
import io.github.test.enums.deser.MessageTypeuDeser;
import io.github.test.message.helper.CharsetHelper;
import lombok.Data; 

/**
 * 协议报文对象.
 */
@Data
public class Protocal
{  
 
	@JSONField(name = "f")
	protected String from;
 
	@JSONField(name = "t")
	protected String to;
 
	@JSONField(name = "ty",deserializeUsing = MessageTypeuDeser.class )
	protected MessageTypeu typeu; 

	@JSONField(name = "d")
	protected String dataContent;
	 
}
```

## IEnum

``` java
package io.github.test.enums.base;


import com.alibaba.fastjson.serializer.JSONSerializable;
import com.alibaba.fastjson.serializer.JSONSerializer;

import java.lang.reflect.Type;

public interface IEnum<T>  extends JSONSerializable {

    /**
     * 获取code值
     * @return
     */
    T getCode();

    /**
     * 获取描述
     * @return
     */
    String getDesc();

    /**
     * JSON 格式化规则
     * @param jsonSerializer
     * @param o
     * @param t
     * @param i
     */
    @Override
    default void write(JSONSerializer jsonSerializer, Object o, Type t, int i) {
        jsonSerializer.write(getCode());
    }
}
```

## MessageTypeu

``` java
package io.github.test.enums;

import io.github.test.enums.base.IEnum;
import lombok.Getter;

 
@Getter
public enum MessageTypeu implements IEnum<Integer> {


    None(-1,"未定义消息"),
    Content(0,"内容类消息"),
    Notice(1,"通知类消息"),
    Status(2,"状态类消息");
 
    private Integer code;
    private String desc;

    MessageTypeu(Integer code, String desc)
    {
        this.code = code;
        this.desc = desc;
    }
 
}

``` 

## MessageTypeuDeser

``` java
package io.github.test.enums.deser;

import com.alibaba.fastjson.parser.DefaultJSONParser;
import com.alibaba.fastjson.parser.JSONToken;
import com.alibaba.fastjson.parser.deserializer.ObjectDeserializer;
import io.github.test.enums.MessageTypeu;

import java.lang.reflect.Type;

public class MessageTypeuDeser implements ObjectDeserializer {

    @Override
    public MessageTypeu deserialze(DefaultJSONParser parser, Type type, Object fieldName) {
        Integer intValue = parser.parseObject(int.class);
        return  valueOf(intValue);
    }

    @Override
    public int getFastMatchToken() {
        return JSONToken.LITERAL_INT;
    }

    // region Helper

    private static MessageTypeu valueOf(int id) {
        switch (id)
        {
            case -1:
                return MessageTypeu.None;
            case 0:
                return MessageTypeu.Content;
            case 1:
                return MessageTypeu.Notice;
            case 2:
                return MessageTypeu.Status;
        }
        return null;
   }
   // endregion
}

``` 

## Tests

``` java

       // 指定JSON解析处理类
       ParserConfig.getGlobalInstance().putDeserializer(MessageTypeu.class, new MessageTypeuDeser());

        Protocal protocal = new Protocal(); 
        .... 对Protocal赋值  
        Protocal protocal1 = JSON.parseObject(JSON.toJSONString(protocal), Protocal.class);
```

成功运行MessageTypeuDeser的deserialze()方法，并且返回对应的枚举值 ，但FastJson报异常

``` code
com.alibaba.fastjson.JSONException: not match : - , info : pos 67, line 1, column 68

	at com.alibaba.fastjson.parser.JSONLexerBase.nextTokenWithChar(JSONLexerBase.java:394)
	at com.alibaba.fastjson.parser.JSONLexerBase.nextTokenWithColon(JSONLexerBase.java:376)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseExtra(DefaultJSONParser.java:1601)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:1203)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:850)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:288)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:687)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:378)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:282)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:555)
````

**Comment by cotide** [comment]
## 使用版本
``` code
  <dependency>
      <groupId>com.alibaba</groupId>
      <artifactId>fastjson</artifactId>
      <version>1.2.59</version>
  </dependency>
```

**Comment by cotide** [comment]
属性冲突导致的··
