### ISSUE TITLE
JSONArray.toJSONString(List<xxx>)出现java.lang.ArithmeticException错误，在新买的云服务器上出现的

### ISSUE THREAD

**Issue by zhudashi** [alibaba/fastjson#2653]
项目是springboot，jdk8，打包在线上部署开始都挺正常。
在我的开发机器，阿里云和百度云的机器上都没有出错。
今天跑clients.hostwinds.com买了个2核4G的服务器，放上去之后，运行到JSONArray.toJSONString(List<xxx>)的时候就开始报错。

fastjson-1.2.57.jar  和 fastjson-1.2.58jar 都尝试过了……
jdk用了jdk1.8.0_212 和 jdk1.8.0_221 都存在这个问题。

```
2019/08/26-10:32 [http-nio-9007-exec-7] ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]- Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.ArithmeticException: / by zero] with root cause
java.lang.ArithmeticException: / by zero
        at com.alibaba.fastjson.serializer.DateCodec.write(DateCodec.java:58) ~[fastjson-1.2.57.jar!/:na]
        at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:333) ~[fastjson-1.2.57.jar!/:na]
        at com.alibaba.fastjson.serializer.ASMSerializer_1_Store.write(Unknown Source) ~[na:na]
        at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:135) ~[fastjson-1.2.57.jar!/:na]
        at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:285) ~[fastjson-1.2.57.jar!/:na]
        at com.alibaba.fastjson.JSON.toJSONString(JSON.java:731) ~[fastjson-1.2.57.jar!/:na]
        at com.alibaba.fastjson.JSON.toJSONString(JSON.java:669) ~[fastjson-1.2.57.jar!/:na]
        at com.alibaba.fastjson.JSON.toJSONString(JSON.java:634) ~[fastjson-1.2.57.jar!/:na]
        at com.我的代码.club_web.controller.MIndexController.index(MIndexController.java:68) ~[classes!/:0.0.1-SNAPSHOT]

```

**Comment by wenshao** [comment]
升级到1.2.59就好了

**Comment by zhudashi** [comment]
> 升级到1.2.59就好了

谢谢，果然解决了问题。
