### ISSUE TITLE
JSON.parseObject("m123", String.class) 报错

### ISSUE THREAD

**Issue by jinkun2014** [alibaba/fastjson#2659]
代码
```
System.out.println(JSON.parseObject("1223", String.class));
System.out.println(JSON.parseObject("2.2", Double.class));
System.out.println(JSON.parseObject("m123", String.class));
```
输出结果
```
1223
2.2
Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2m123
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1474)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1360)
	at com.alibaba.fastjson.serializer.StringCodec.deserialze(StringCodec.java:105)
	at com.alibaba.fastjson.serializer.StringCodec.deserialze(StringCodec.java:87)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:689)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:378)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:282)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:555)
	at com.pickmestar.rds.config.RedisConf.main(RedisConf.java:153)
```

**Comment by luke-huang666** [comment]
```java
System.out.println(JSON.parseObject("m123", String.class));
```
中报错是正确的处理逻辑。

正确的写法应该是：
```java
System.out.println(JSON.parseObject("\"m123\"", String.class));
```
