### ISSUE TITLE
toJavaBean能支持 java.nio.ByteBuffer类型吗？

### ISSUE THREAD

**Issue by julyzd** [alibaba/fastjson#2665]
Exception in thread "main" com.alibaba.fastjson.JSONException: can not cast to : java.nio.ByteBuffer
	at com.alibaba.fastjson.util.TypeUtils.castToJavaBean(TypeUtils.java:1361)
	at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:927)
	at com.alibaba.fastjson.JSON.toJavaObject(JSON.java:1103)
	at Test.main(Test.java:37)

**Comment by julyzd** [comment]
is supported
