### ISSUE TITLE
Enumset反序列化出错

### ISSUE THREAD

**Issue by vongosling** [alibaba/fastjson#268]
代码：
版本：    compile group: 'com.alibaba', name: 'fastjson', version: '1.2.3'

   public static byte[] encode(Object content) {
        return JSONObject.toJSONString(content, config, sfeatures).getBytes();
    }

    public static <T> T decode(byte[] content,Class<T> clazz) {
        return JSON.parseObject(content, clazz,features);
    }
}
错误：
com.alibaba.fastjson.JSONException: class java.lang.Object not an enum
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:555)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:293)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:278)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:261)
	at com.creative.commons.utils.JsonCodec.decode(JsonCodec.java:28)
	at com.creative.commons.utils.CodecTest.jsonCodecTest(CodecTest.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.ClassCastException: class java.lang.Object not an enum
	at java.util.EnumSet.noneOf(EnumSet.java:110)
	at com.alibaba.fastjson.parser.deserializer.CollectionDeserializer.deserialze(CollectionDeserializer.java:48)
	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:33)
	at com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer.parseField(ASMJavaBeanDeserializer.java:74)
	at com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer$InnerJavaBeanDeserializer.parseField(ASMJavaBeanDeserializer.java:86)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:330)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:135)
	at com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer.deserialze(ASMJavaBeanDeserializer.java:29)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)
	... 33 more

**Comment by vongosling** [comment]
简单看了下，问题应该出现在这里，
if (type instanceof ParameterizedType) {
                itemType = ((ParameterizedType) type).getActualTypeArguments()[0];
            } else {
                itemType = Object.class;
            }

type这里是java.util.EnumSet,但是这块的逻辑走到else了，所以就把itemTYpe转换成Object了

**Comment by yakolee** [comment]
泛型反序列化，请使用下面的api：
  List<VO> list = JSON.parseObject("...", new TypeReference<List<VO>>() {});

下面例子中EnumSet的序列化和反序列化不会出问题：
public static void main(String[] args) {
        EnumSet<MyEnum> set = EnumSet.allOf(MyEnum.class);
        String json = JSONObject.toJSONString(set);
        System.out.println(json);
        EnumSet<MyEnum> set2 = JSON.parseObject(json, new TypeReference<EnumSet<MyEnum>>() {
        });
        System.out.println(set2);
    }

public enum MyEnum {
    BLACK, WHITE, RED, BLUR, GREEN, YELLOW
}

**Comment by vongosling** [comment]
不行，public static <T> T decode(byte[] content,Class<T> clazz) {
    return JSON.parseObject(content, clazz,features);
}
这个class里面，有很多种类型，不止枚举，泛型，时间戳，货币，很多其它类型，玩不转的

**Comment by wenshao** [comment]
让你久等了，将会在1.2.9和1.1.49.android版本支持这个功能。

**Comment by vongosling** [comment]
等的还好～
