### ISSUE TITLE
ParseObject Failed due to special character ":"

### ISSUE THREAD

**Issue by cxj110** [alibaba/fastjson#2738]
FastJSON version: 1.2.60

Read JSON String from some file, then parse the string as JSON Object.

JSON:
{
.......
              "RequestBody": "TestDemo:TestRequest"
......
}

Exception:
Caused by: com.alibaba.fastjson.JSONException: syntax error, pos 8, line 1, column 9TestDemo:TestRequest
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1474)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1363)
	at com.alibaba.fastjson.JSON.parse(JSON.java:170)
	at com.alibaba.fastjson.JSON.parse(JSON.java:180)
	at com.alibaba.fastjson.JSON.parse(JSON.java:149)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:241)
	at com.alibaba.fastjson.JSONObject.getJSONObject(JSONObject.java:127)
	at com.twinkle.framework.connector.http.endpoint.DefaultHttpRequest.configure(DefaultHttpRequest.java:53)
	at com.twinkle.framework.configure.component.ComponentFactory.loadGeneralComponent(ComponentFactory.java:63)
	at com.twinkle.framework.connector.http.endpoint.AbstractHttpEndpoint.configure(AbstractHttpEndpoint.java:72)
	at com.twinkle.framework.configure.component.ComponentFactory.loadComponent(ComponentFactory.java:114)
	... 17 common frames omitted

**Comment by cxj110** [comment]
My mistake, the content body for "RequestBody" should be an JSONObject.
