### ISSUE TITLE
fast 1.1.41 java.lang.ArrayIndexOutOfBoundsException: 160 仍现

### ISSUE THREAD

**Issue by leanjiang** [alibaba/fastjson#276]
程序里面如下：
```
        OutputStream out = outputMessage.getBody();
        OutputStreamWriter osw = new OutputStreamWriter(out, DEFAULT_CHARSET);
        JSON.writeJSONStringTo(o, osw, serializerFeature);
```
log如下：
```
java.lang.ArrayIndexOutOfBoundsException: 160
	at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:665)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeFieldValueStringWithDoubleQuote(SerializeWriter.java:1214)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeFieldValue(SerializeWriter.java:1182)
	at Serializer_4.write1(Unknown Source)
	at Serializer_4.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:398)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:376)
	at Serializer_3.write1(Unknown Source)
	at Serializer_3.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:398)
	at Serializer_1.write1(Unknown Source)
	at Serializer_1.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:369)
	at com.alibaba.fastjson.JSON.writeJSONStringTo(JSON.java:580)
	at com.xuebax.utils.MappingFastJsonHttpMessageConverter.writeInternal(MappingFastJsonHttpMessageConverter.java:73)
```

但是使用
```
        String jsonString = JSON.toJSONString(o, serializerFeature);
        OutputStream out = outputMessage.getBody();
        out.write(jsonString.getBytes(DEFAULT_CHARSET));
        out.flush();
```
是没有问题的。温少，您看看是否是使用Stream的方式没有一并修改？

**Comment by gm100861** [comment]
我也遇到这个问题了,楼上的朋友解决了吗?

     JSONObject jsonObject = CrawlerHttpClient.getInstance().formPost(url, map, "UTF-8");
                HuxiuResponseJsonModel jsonModel = JSON.parseObject(jsonObject.toJSONString(), HuxiuResponseJsonModel.class);
                System.out.println(jsonModel.getMsg());

    java.lang.ArrayIndexOutOfBoundsException: 160
	at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:868)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:602)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeString(SerializeWriter.java:1366)
	at com.alibaba.fastjson.serializer.StringCodec.write(StringCodec.java:49)
	at com.alibaba.fastjson.serializer.StringCodec.write(StringCodec.java:34)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:188)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:369)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:596)
	at com.plusnet.crawler.test.HuXiuSpiderTest.main(HuXiuSpiderTest.java:30)
org.apache.http.conn.ConnectTimeoutException: Connect to www.huxiu.com:80 [www.huxiu.com/101.201.170.135] failed: connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:143)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.plusnet.crawler.common.http.CrawlerHttpClient.formPost(CrawlerHttpClient.java:260)
	at com.plusnet.crawler.test.HuXiuSpiderTest.main(HuXiuSpiderTest.java:29)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	... 12 more

**Comment by wenshao** [comment]
问题已经修复了，请更新版本。先关闭啦，如果有问题再反馈。
