### ISSUE TITLE
使用fastjson序列化数据时，ASM报java.lang.NoSuchMethodError: com.alibaba.fastjson.serializer.JavaBeanSerializer.processValue

### ISSUE THREAD

**Issue by helloworldtang** [alibaba/fastjson#2780]
背景：
代码：一段几个月前的老代码
变更： 将fastjson从1.2.57升级到1.2.61

报错信息：
```java
java.lang.NoSuchMethodError: com.alibaba.fastjson.serializer.JavaBeanSerializer.processValue(Lcom/alibaba/fastjson/serializer/JSONSerializer;Lcom/alibaba/fastjson/serializer/BeanContext;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;Ljava/lang/Integer;
	at com.alibaba.fastjson.serializer.ASMSerializer_1_CurrentUserBO.writeNormal(Unknown Source) ~[na:na]
	at com.alibaba.fastjson.serializer.ASMSerializer_1_CurrentUserBO.write(Unknown Source) ~[na:na]
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:285) ~[fastjson-1.2.61.jar:na]
	at com.alibaba.fastjson.JSON.toJSONBytes(JSON.java:825) ~[fastjson-1.2.61.jar:na]
	at com.alibaba.fastjson.JSON.toJSONBytes(JSON.java:796) ~[fastjson-1.2.61.jar:na]
	at com.alibaba.fastjson.JSON.toJSONBytes(JSON.java:789) ~[fastjson-1.2.61.jar:na]
	at com.alibaba.fastjson.JSON.toJSONBytes(JSON.java:771) ~[fastjson-1.2.61.jar:na]
	at com.alibaba.fastjson.JSON.toJSONBytes(JSON.java:698) ~[fastjson-1.2.61.jar:na]
	at com.alibaba.fastjson.JSON.toJSONBytes(JSON.java:687) ~[fastjson-1.2.61.jar:na]
	at com.alibaba.fastjson.support.spring.GenericFastJsonRedisSerializer.serialize(GenericFastJsonRedisSerializer.java:24) ~[fastjson-1.2.61.jar:na]
	at org.springframework.data.redis.core.AbstractOperations.rawValue(AbstractOperations.java:117) ~[spring-data-redis-1.8.12.RELEASE.jar:na]
	at org.springframework.data.redis.core.DefaultValueOperations.set(DefaultValueOperations.java:180) ~[spring-data-redis-1.8.12.RELEASE.jar:na]
	at com.user.app.cache.impl.UserCacheServiceImpl.cacheCurrentLoginUser(UserCacheServiceImpl.java:48) ~[classes/:na]
	at com.user.app.service.impl.LoginServiceImpl.tokenLogin(LoginServiceImpl.java:112) ~[classes/:na]
	at com.user.app.service.impl.LoginServiceImpl.mobileLogin(LoginServiceImpl.java:86) ~[classes/:na]
	at com.user.app.service.impl.MobileLoginServiceImpl.login(MobileLoginServiceImpl.java:51) ~[classes/:na]
	at com.user.app.controller.AppUserController.login(AppUserController.java:130) ~[classes/:na]
	at com.user.app.controller.AppUserController$$FastClassBySpringCGLIB$$7dc4b154.invoke(<generated>) ~[classes/:na]
```

相关的java代码：
```java
    @Override
    public void cacheCurrentLoginUser(Integer userId, Integer sourceType, String mobile, Integer invoiceInfoId) {
        CurrentUserBO currentUserBO = new CurrentUserBO();
        currentUserBO.setMobile(mobile);
        currentUserBO.setInvoiceId(invoiceInfoId);
        String key = CacheKeyManager.fillKey(CURRENT_USER_KEY, userId, sourceType);
        redisTemplate.opsForValue().set(key, currentUserBO, COOKIE_MAX_AGE, TimeUnit.SECONDS); //此行代码报错
    }
```

RedisTemplate中FastJsonRedisSerializer的使用：
···java
    @Bean
    public RedisTemplate redisTemplate(RedisConnectionFactory redisConnectionFactory) {
        RedisTemplate<String, Object> redisTemplate = new RedisTemplate<>();
        GenericFastJsonRedisSerializer fastJsonRedisSerializer = new GenericFastJsonRedisSerializer();
        redisTemplate.setKeySerializer(new StringRedisSerializer());
        redisTemplate.setDefaultSerializer(fastJsonRedisSerializer);//设置默认的Serialize，包含 keySerializer & valueSerializer
        redisTemplate.setConnectionFactory(redisConnectionFactory);
        return redisTemplate;
    }
```
![image](https://user-images.githubusercontent.com/13701989/65650167-401fdb80-e03c-11e9-958f-29f16ed402b3.png)

**Comment by Omega-Ariston** [comment]
Duplicate of #2763

**Comment by kervin521** [comment]
同样问题

**Comment by zwy20034751** [comment]
同样问题

**Comment by zhaotingwen** [comment]
升级到1.2.62时还是会报这个错误呢。
java.lang.NoSuchMethodError: com.alibaba.fastjson.serializer.JavaBeanSerializer.processValue(Lcom/alibaba/fastjson/serializer/JSONSerializer;Lcom/alibaba/fastjson/serializer/BeanContext;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;Ljava/lang/Integer;
	at com.alibaba.fastjson.serializer.ASMSerializer_1_GetAvailabilityByFlightRequestBean.writeNormal(Unknown Source) ~[na:na]
	at com.alibaba.fastjson.serializer.ASMSerializer_1_GetAvailabilityByFlightRequestBean.write(Unknown Source) ~[na:na]
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:271) ~[fastjson-1.2.62.jar:na]
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:44) ~[fastjson-1.2.62.jar:na]
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:271) ~[fastjson-1.2.62.jar:na]
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:44) ~[fastjson-1.2.62.jar:na]
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:285) ~[fastjson-1.2.62.jar:na]

**Comment by helloworldtang** [comment]
@zhaotingwen 1.2.62还有这个问题.温少让Nameless·Ariston找我修过了。 
我这边环境的兼容性问题已修复。

**Comment by zhangxuexiang** [comment]
预计什么时候可以修复这个问题

**Comment by zwy20034751** [comment]
坐等发版

**Comment by kervin521** [comment]
+1

**Comment by kakukeme** [comment]
+1

**Comment by kasuo405** [comment]
+1

**Comment by yuhua1987113** [comment]
waiting...

**Comment by woodyDM** [comment]
在windows下会报这个错，在macOS 和 ubuntu下不会。

**Comment by oyl215** [comment]
升级到1.2.62版本仍然存在这个问题，老的版本不存在这个问题，期待这个问题的解决。

**Comment by 13438344431** [comment]
how to solve it.

**Comment by Liuliya503288309** [comment]
新版本怎么解决这个问题呢

**Comment by rainofflower** [comment]
> 在windows下会报这个错，在macOS 和 ubuntu下不会。

centos7也不会报错，windows10下确实报错

**Comment by Wanfashu** [comment]
@13438344431 return to 1.2.58
@Liuliya503288309 退回 1.2.58 ，我这边正常了。

**Comment by wang420979002** [comment]
1.2.62 win10报错，求下个版本解决

**Comment by hct7511** [comment]
1.2.58解决。。

**Comment by kervin521** [comment]
v1.2.60也是正常的

**Comment by HouChenggong** [comment]
<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.62</version>
        </dependency>
也报这个错

**Comment by helloworldtang** [comment]
> @13438344431 return to 1.2.58
> @Liuliya503288309 退回 1.2.58 ，我这边正常了。

1.2.58有漏洞哦

**Comment by helloworldtang** [comment]
> 1.2.58解决。。

1.2.58有漏洞哦

**Comment by helloworldtang** [comment]
> v1.2.60也是正常的

1.2.60有安全隐患哦

**Comment by Wanfashu** [comment]
@helloworldtang 只有等作者修复，换jackson代价太大了....

**Comment by gchhy** [comment]
the same question

**Comment by yechen2** [comment]
the same question

**Comment by lyyu1988** [comment]
the same question

**Comment by samuel072** [comment]
V1.2.60版本好， 但是以上的版本都不行。系统：mac V：10.15， 暂时还不知道在centos是否有问题。但是有的兄弟说这个版本不能在centos系统使用。

**Comment by llliuwenjie** [comment]
mac系统也报错 1.2.62

**Comment by 472827074** [comment]
mac系统也报错 1.2.62，看到有说win10,mac操作系统版本不同还报错的，好神奇

**Comment by qrqhuang** [comment]
same behaviour

**Comment by 412940226** [comment]
win10系统1.2.62有问题，修复了没有
java.lang.NoSuchMethodError: com.alibaba.fastjson.serializer.JavaBeanSerializer.processValue

**Comment by wmwmwmll** [comment]
how to solve

**Comment by 412940226** [comment]
> how to solve

Win10 still has problems

**Comment by 412940226** [comment]
> how to solve

Win10 still has problems

**Comment by zyong2004** [comment]
同样的问题，win10出问题

**Comment by faliny** [comment]
mark一下，等待修复

**Comment by xixia1wencun** [comment]
马一下，等待修复

**Comment by devfat** [comment]
也遇到了这个问题了，但是很奇怪过几天又可以了

**Comment by niaonao** [comment]
先降版本吧

**Comment by eyougo** [comment]
1.2.62，Mac系统，还是这个问题，求修复

**Comment by yushilin** [comment]
诺诺的问一句，还没有修复么？

**Comment by yguilai** [comment]
> 诺诺的问一句，还没有修复么？

我升到1.2.66 没报这个错了

**Comment by Miven666** [comment]
我升到1.2.66 也没报这个错了
Mac 10.15.3

**Comment by flibbertigibbet-Y** [comment]
So？？？要升级到1.2.66才行咯？？

**Comment by xctjtcc** [comment]
@zhaotingwen 1.2.62还有这个问题.温少让Nameless·Ariston找我修过了。
我这边环境的兼容性问题已修复。

能否分享下具体情况？是和什么发生冲突了呢，怎么解决的？

**Comment by yushilin** [comment]
邮件已经收到，谢谢！！！

**Comment by DayBreakOb** [comment]
'你好。已收到你的邮件，我会在假期结束后尽快处理。————————————这是来自QQ邮箱的自动回复邮件。'
