### ISSUE TITLE
自定义com.alibaba.fastjson.spi.Module处理同一类型所有子类序列化与反序列化方式异常

### ISSUE THREAD

**Issue by chendb** [alibaba/fastjson#2781]
我定义了一接口如下：
/**
 * 定义的一个基本类型接口，继续该接口的类型会被认为是基础类型
 */
public interface CodeType {
    /**
     * 属性值
     * @return 属性值
     * @author chendb
     * @date 2016年12月8日 下午11:44:20
     */
    String getValue();

    /**
     * 属性描述信息
     * @return 描述信息
     * @author chendb
     * @date 2016年12月8日 下午11:44:42
     */
    String getDescription();
}

我希望所有实现该接口对类序列化时，把它当前一个简单类型来序列化，如是我定义了：
public class CodeTypeModule implements  Module {
    @Override
    public ObjectDeserializer createDeserializer(ParserConfig parserConfig, Class aClass) {
        if(CodeType.class.isAssignableFrom(aClass)) {
            return new CodeTypeSerializer();
        }
        return null;
    }
    @Override
    public ObjectSerializer createSerializer(SerializeConfig serializeConfig, Class aClass) {
        if(CodeType.class.isAssignableFrom(aClass)) {
            return  new CodeTypeSerializer();
        }
        return null;
    }
}

全局配置如下：
    static {
        parserConfig.setAutoTypeSupport(true);
        parserConfig.register(new CodeTypeModule());
        serializeConfig.register(new CodeTypeModule());
    }

使用如下：
    public byte[] serialize(T t) {
        if (t == null) {
            return new byte[0];
        }
        JSONObject.DEFFAULT_DATE_FORMAT = "yyyy-MM-dd HH:mm:ss";
        return JSON.toJSONBytes(t,serializeConfig, new SerializerFeature[]{SerializerFeature.WriteDateUseDateFormat,SerializerFeature.WriteClassName});
      
    }

    public T deserialize(byte[] bytes) {
        if (bytes == null || bytes.length <= 0) {
            return null;
        }

        try {
            String str = new String(bytes, IOUtils.UTF8);
            if (clazz == null) {
                return JSON.parseObject(str, Object.class, parserConfig, new Feature[0]);
            } else {
                return JSON.parseObject(str, clazz, parserConfig, new Feature[0]);
            }
        } catch (Exception var3) {
            throw new SerializationException("Could not deserialize: " + var3.getMessage(), var3);
        }
    }

发现在序列化时出现异常：

com.alibaba.fastjson.JSONException: create asm serializer error, verson 1.2.60, class byte
	at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:260) ~[fastjson-1.2.60.jar:na]
	at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:120) ~[fastjson-1.2.60.jar:na]
	at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:788) ~[fastjson-1.2.60.jar:na]
	at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:432) ~[fastjson-1.2.60.jar:na]
	at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:523) ~[fastjson-1.2.60.jar:na]
	at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:432) ~[fastjson-1.2.60.jar:na]
	at com.alibaba.fastjson.serializer.JSONSerializer.getObjectWriter(JSONSerializer.java:410) ~[fastjson-1.2.60.jar:na]
	at com.alibaba.fastjson.serializer.ASMSerializer_3266_String.writeNormal(Unknown Source) ~[na:na]
	at com.alibaba.fastjson.serializer.ASMSerializer_3266_String.write(Unknown Source) ~[na:na]
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:333) ~[fastjson-1.2.60.jar:na]
	at com.alibaba.fastjson.serializer.ASMSerializer_3265_CacheMessage.writeNormal(Unknown Source) ~[na:na]
	at com.alibaba.fastjson.serializer.ASMSerializer_3265_CacheMessage.write(Unknown Source) ~[na:na]
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:285) ~[fastjson-1.2.60.jar:na]
	at com.alibaba.fastjson.JSON.toJSONBytes(JSON.java:825) ~[fastjson-1.2.60.jar:na]
	at com.alibaba.fastjson.JSON.toJSONBytes(JSON.java:796) ~[fastjson-1.2.60.jar:na]
	at com.alibaba.fastjson.JSON.toJSONBytes(JSON.java:789) ~[fastjson-1.2.60.jar:na]
	at com.alibaba.fastjson.JSON.toJSONBytes(JSON.java:764) ~[fastjson-1.2.60.jar:na]

**Comment by Omega-Ariston** [comment]
CodeTypeSerializer可以提供下吗
