### ISSUE TITLE
1.2.62也不兼容1.2.60以前的方法JavaBeanSerializer.processValue

### ISSUE THREAD

**Issue by zhaotingwen** [alibaba/fastjson#2802]
java.lang.NoSuchMethodError: com.alibaba.fastjson.serializer.JavaBeanSerializer.processValue(Lcom/alibaba/fastjson/serializer/JSONSerializer;Lcom/alibaba/fastjson/serializer/BeanContext;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;Ljava/lang/Integer;
at com.alibaba.fastjson.serializer.ASMSerializer_1_GetAvailabilityByFlightRequestBean.writeNormal(Unknown Source) ~[na:na]
at com.alibaba.fastjson.serializer.ASMSerializer_1_GetAvailabilityByFlightRequestBean.write(Unknown Source) ~[na:na]
at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:271) ~[fastjson-1.2.62.jar:na]
at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:44) ~[fastjson-1.2.62.jar:na]
at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:271) ~[fastjson-1.2.62.jar:na]
at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:44) ~[fastjson-1.2.62.jar:na]
at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:285) ~[fastjson-1.2.62.jar:na]

**Comment by zhangxuexiang** [comment]
What time can fix the Bug

**Comment by zwy20034751** [comment]
the same problem !!!

**Comment by yuhua1987113** [comment]
wating...

**Comment by hjki456789** [comment]
没人解决吗？

**Comment by zwy20034751** [comment]
急需 1.2.63 解决此问题，请温少尽快发版吧！

**Comment by 13207380653** [comment]
1.2.28 以后的版本没问题了

**Comment by xctjtcc** [comment]
请问最终这个问题怎么解决的呢？
