### ISSUE TITLE
1.2.62 自定义反序列化报错 not close json text, token : }

### ISSUE THREAD

**Issue by masterchengsheng** [alibaba/fastjson#2848]
自定义序列号和反序列化操作  序列化时OK 反序列化时 报错

**Comment by masterchengsheng** [comment]
```
@Data
public class Rule implements Serializable {
    @JSONField(serializeUsing = com.smartcall.common.dto.rule.serializable.RuleSerializable.class,
            deserializeUsing = com.smartcall.common.dto.rule.serializable.RuleDeserializable.class)
    private List<Stage> rules;
}
```


```
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Stage implements Serializable {

    private String stageName;

    private List<RuleNode> nodes;
}
```

```
@Data
@NoArgsConstructor
@AllArgsConstructor
public class RuleNode implements Serializable {

    private String nodeName;

    private List<LogicRule> logicRuleList;
}

```

```
@Data
@NoArgsConstructor
@AllArgsConstructor
public class LogicRule implements Serializable {

    /**
     * and or not 逻辑名称
     */
    private String logicName;

    /**
     * 子规则
     */
    private List<LogicRule> childrenRule;

    /**
     * 底层的规则
     */
    private List<RuleItem> items;
}
```

```

@Data
@AllArgsConstructor
@NoArgsConstructor
public class RuleItem implements Serializable {

    /**
     * in
     */
    private String target;

    /**
     *
     */
    private String desc;

    /**
     * input_text
     * context
     */
    private String category;


    public List<String> assList() {
        return Lists.newArrayList(this.target, this.desc, this.category);
    }

    public static RuleItem fillData(List<String> list) {
        if (CollectionUtils.isEmpty(list)) {
            return null;
        }
        if (list.size() != 3) {
            return null;
        }
        RuleItem item = new RuleItem();
        item.target = list.get(0);
        item.desc = list.get(1);
        item.category = list.get(2);
        return item;
    }
}

```

```

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.parser.DefaultJSONParser;
import com.alibaba.fastjson.parser.deserializer.ObjectDeserializer;
import com.google.common.collect.Lists;
import com.smartcall.common.dto.rule.LogicRule;
import com.smartcall.common.dto.rule.RuleItem;
import com.smartcall.common.dto.rule.RuleNode;
import com.smartcall.common.dto.rule.Stage;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Set;

public class RuleDeserializable implements ObjectDeserializer {
    @Override
    public List<Stage> deserialze(DefaultJSONParser defaultJSONParser, Type type, Object fieldName) {
        String input = defaultJSONParser.getInput();
        List<Stage> stages = new ArrayList<>();
        JSONObject jsonObject = JSONObject.parseObject(input);
        Set<String> set = jsonObject.keySet();
        if (set.contains("rules")) {
            Object rules = jsonObject.get("rules");
            if (Objects.isNull(rules)) {
                return Lists.newArrayList();
            }
            JSONObject rulesObj = (JSONObject) rules;
            Set<String> strings = rulesObj.keySet();
            for (String string : strings) {
                Object o = rulesObj.get(string);
                Stage stage = new Stage();
                stages.add(stage);
                stage.setStageName(string);
                if (Objects.isNull(o)) {
                    continue;
                }
                analysisHandler(stage, o);
            }
        } else {
            return Lists.newArrayList();
        }
        return stages;
    }

    public static final List<String> logicTarget = Lists.newArrayList("and", "or", "not");

    private void analysisHandler(Stage stage, Object obj) {
        JSONObject jsonObject = (JSONObject) obj;
        for (String key : jsonObject.keySet()) {
            JSONArray array = jsonObject.getJSONArray(key);
            analysisRuleNode(array, stage, key);
        }
    }

    private void analysisRuleNode(JSONArray array, Stage stage, String key) {
        RuleNode ruleNode = new RuleNode();
        if (stage.getNodes() == null) {
            stage.setNodes(Lists.newArrayList(ruleNode));
        } else {
            stage.getNodes().add(ruleNode);
        }
        ruleNode.setNodeName(key);
        List<Object> list = array.toJavaList(Object.class);
        List<RuleItem> ruleItems = Lists.newArrayList();
        List<LogicRule> logicRules = Lists.newArrayList();
        LogicRule logicRule = new LogicRule();
        ruleNode.setLogicRuleList(Lists.newArrayList(logicRule));
        logicRule.setItems(ruleItems);
        logicRule.setChildrenRule(logicRules);
        for (Object o : list) {
            if (o instanceof String) {
                logicRule.setLogicName(o.toString());
            } else {
                List<String> list1 = (List<String>) o;
                String s = list1.get(0);
                if (logicTarget.contains(s)) {
                    LogicRule lr = analysisLogicRule((JSONArray) o);
                    if (Objects.nonNull(lr)) {
                        logicRules.add(lr);
                    }
                } else {
                    RuleItem item = RuleItem.fillData(list1);
                    if (Objects.isNull(item)) {
                        continue;
                    }
                    ruleItems.add(item);
                }
            }
        }
    }

    private LogicRule analysisLogicRule(JSONArray array) {
        LogicRule logicRule = new LogicRule();
        List<RuleItem> ruleItems = Lists.newArrayList();
        List<LogicRule> logicRules = Lists.newArrayList();
        logicRule.setItems(ruleItems);
        logicRule.setChildrenRule(logicRules);
        List<Object> list = array.toJavaList(Object.class);
        for (Object o : list) {
            if (o instanceof String) {
                logicRule.setLogicName(o.toString());
            } else {
                List<String> list1 = (List<String>) o;
                String s = list1.get(0);
                if (logicTarget.contains(s)) {
                    LogicRule lr = analysisLogicRule((JSONArray) o);
                    if (Objects.nonNull(lr)) {
                        logicRules.add(lr);
                    }
                } else {
                    RuleItem item = RuleItem.fillData(list1);
                    if (Objects.isNull(item)) {
                        continue;
                    }
                    ruleItems.add(item);
                }
            }
        }
        return logicRule;
    }


    @Override
    public int getFastMatchToken() {
        return 0;
    }
}

```

```

import com.alibaba.fastjson.serializer.JSONSerializer;
import com.alibaba.fastjson.serializer.ObjectSerializer;
import com.google.common.collect.Lists;
import com.smartcall.common.dto.rule.LogicRule;
import com.smartcall.common.dto.rule.RuleItem;
import com.smartcall.common.dto.rule.RuleNode;
import com.smartcall.common.dto.rule.Stage;
import org.apache.commons.collections.CollectionUtils;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class RuleSerializable implements ObjectSerializer {


    @Override
    public void write(JSONSerializer jsonSerializer, Object o, Object fieldName, Type type, int i) throws IOException {
        List<Stage> stages = (List<Stage>) o;
        Map<String, Map<String, List<Object>>> map = new LinkedHashMap<>();
        for (Stage stage : stages) {
            String stageName = stage.getStageName();
            List<RuleNode> nodes = stage.getNodes();
            Map<String, List<Object>> innerMap = new LinkedHashMap();
            if (CollectionUtils.isEmpty(nodes)) {
                map.put(stageName, innerMap);
                continue;
            }
            for (RuleNode node : nodes) {
                String nodeName = node.getNodeName();
                List<LogicRule> logicRuleList = node.getLogicRuleList();
                if (CollectionUtils.isEmpty(logicRuleList)) {
                    innerMap.put(nodeName, Lists.newArrayList());
                    continue;
                }
                List<Object> list = new ArrayList<>();
                for (LogicRule logicRule : logicRuleList) {
                    String logicName = logicRule.getLogicName();
                    List<RuleItem> items = logicRule.getItems();
                    List<LogicRule> children = logicRule.getChildrenRule();
                    list.add(logicName);
                    if (CollectionUtils.isNotEmpty(items)) {
                        for (RuleItem item : items) {
                            list.add(item.assList());
                        }
                    }
                    if (CollectionUtils.isNotEmpty(children)) {
                        recursionAnalysis(children, list);
                    }
                }
                innerMap.put(nodeName, list);
            }
            map.put(stageName, innerMap);
        }
        jsonSerializer.write(map);
    }


    private void recursionAnalysis(List<LogicRule> children, List<Object> list) {
        if (CollectionUtils.isEmpty(children)) {
            return;
        }
        for (LogicRule child : children) {
            String logicName = child.getLogicName();
            List<RuleItem> items = child.getItems();
            List<LogicRule> childrenRuleList = child.getChildrenRule();
            List<Object> subList = new ArrayList<>();
            subList.add(logicName);
            if (CollectionUtils.isNotEmpty(items)) {
                for (RuleItem item : items) {
                    subList.add(item.assList());
                }
            }
            if (CollectionUtils.isNotEmpty(childrenRuleList)) {
                recursionAnalysis(childrenRuleList, subList);
            }
            list.add(subList);
        }
    }
}

```

**Comment by masterchengsheng** [comment]
```
    public static void main(String[] args) {
        Stage stage = new Stage();
        stage.setStageName("stage_0");
        List<RuleNode> nodes = new ArrayList<>();
        stage.setNodes(nodes);
        RuleNode ruleNode = new RuleNode();
        nodes.add(ruleNode);
        ruleNode.setNodeName("p_59_0_0");
        List<LogicRule> logicRules = new ArrayList<>();
        ruleNode.setLogicRuleList(logicRules);
        LogicRule rule = new LogicRule();
        logicRules.add(rule);
        rule.setLogicName("or");
        rule.setItems(Lists.newArrayList(new RuleItem("in", "你好", "input_text"), new RuleItem("in", "真的", "input_text")));

        LogicRule children = new LogicRule();
        children.setLogicName("and");
        children.setItems(Lists.newArrayList(new RuleItem("in", "有", "input_text"), new RuleItem("in", "电话", "input_text")));
        rule.setChildrenRule(Lists.newArrayList(children));

        Rule rule1 = new Rule();
        rule1.setRules(Lists.newArrayList(stage));
        System.out.println(JSONObject.toJSONString(rule1));
}
```
获得JSON：{"rules":{"stage_0":{"p_59_0_0":["or",["in","你好","input_text"],["in","真的","input_text"],["and",["in","有","input_text"],["in","电话","input_text"]]]}}}
 然后那这个反序列化时   
```
 Rule rule = JSONObject.parseObject(json, Rule.class);
```

```
Exception in thread "main" com.alibaba.fastjson.JSONException: not close json text, token : }
	at com.alibaba.fastjson.parser.DefaultJSONParser.close(DefaultJSONParser.java:1526)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:387)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:287)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:560)
	at com.smartcall.common.dto.rule.Rule.main(Rule.java:88)

Process finished with exit code 1


```

**Comment by ChunC-Wu** [comment]
![image](https://user-images.githubusercontent.com/22518637/68183102-5a06f380-ffd6-11e9-85f2-986fccb55544.png)
        String z = "{\"rules\":{\"stage_0\":{\"p_59_0_0\":[\"or\",[\"in\",\"你好\",\"input_text\"],[\"in\",\"真的\",\"input_text\"],[\"and\",[\"in\",\"有\",\"input_text\"],[\"in\",\"电话\",\"input_text\"]]]}}}";
        JSONObject jo = JSON.parseObject(z);
直接反序列化你的json，未复现问题啊

**Comment by masterchengsheng** [comment]
我处理的时候 就一直报not close json text, token : } 难道是环境问题？
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: ChunC-Wu <notifications@github.com>
发送时间: Tuesday, November 5, 2019 2:15:14 PM
收件人: alibaba/fastjson <fastjson@noreply.github.com>
抄送: 程胜 <chengshengsyxy@live.cn>; Author <author@noreply.github.com>
主题: Re: [alibaba/fastjson] 1.2.62 自定义反序列化报错 not close json text, token : } (#2848)


[image]<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F22518637%2F68183102-5a06f380-ffd6-11e9-85f2-986fccb55544.png&data=02%7C01%7C%7C4efe5c3f9ca3423a47c108d761b78744%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637085313181572747&sdata=5VLH3UkFXT4ecMBXZz1jJPmTlwzNEi6y5BSoq4e7q7M%3D&reserved=0>
String z = "{"rules":{"stage_0":{"p_59_0_0":["or",["in","你好","input_text"],["in","真的","input_text"],["and",["in","有","input_text"],["in","电话","input_text"]]]}}}";
JSONObject jo = JSON.parseObject(z);
直接反序列化你的json，未复现问题啊

―

**Comment by ChunC-Wu** [comment]
贴一下反序列化怎么写的

**Comment by masterchengsheng** [comment]
Rule rule = JSONObject.parseObject(json, Rule.class);   就直接拿这个来反序列化  上面那个main方法里序列化对应的json 然后反序列化就抛异常了
