### ISSUE TITLE
enum 枚举解析报错

### ISSUE THREAD

**Issue by yangsen198945** [alibaba/fastjson#2854]
@JSONType(serializeEnumAsJavaBean = true)
public enum LevelFeeRateEnum {

    ONE(1, BigDecimal.ZERO),
    TWO(2, new BigDecimal("0.75")),
    THREE(3, new BigDecimal("0.75")),
    FOUR(4, new BigDecimal("0.75")),
    FIVE(5, new BigDecimal("0.75"));

    private final int level;
    private final BigDecimal feeRate;

    LevelFeeRateEnum(int level, BigDecimal feeRate) {
        this.level = level;
        this.feeRate = feeRate;
    }

    public int getLevel() {
        return level;
    }

    public BigDecimal getFeeRate() {
        return feeRate;
    }
}

测试
 System.out.println(JSON.parseObject("{\"feeRate\":0,\"level\":1}", LevelFeeRateEnum.class));

报错
com.alibaba.fastjson.JSONException: parse enum com.weibi.app.trade.model.core.match.LevelFeeRateEnum error, value : {"level":1,"feeRate":0}

	at com.alibaba.fastjson.parser.deserializer.EnumDeserializer.deserialze(EnumDeserializer.java:104)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:626)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:348)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:252)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:471)
	at J2SETest.testLevelFeeRateEnum(J2SETest.java:213)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by sunshaobin** [comment]
> @JSONType(serializeEnumAsJavaBean = true)
> public enum LevelFeeRateEnum {
> 
> ```
> ONE(1, BigDecimal.ZERO),
> TWO(2, new BigDecimal("0.75")),
> THREE(3, new BigDecimal("0.75")),
> FOUR(4, new BigDecimal("0.75")),
> FIVE(5, new BigDecimal("0.75"));
> 
> private final int level;
> private final BigDecimal feeRate;
> 
> LevelFeeRateEnum(int level, BigDecimal feeRate) {
>     this.level = level;
>     this.feeRate = feeRate;
> }
> 
> public int getLevel() {
>     return level;
> }
> 
> public BigDecimal getFeeRate() {
>     return feeRate;
> }
> ```
> 
> }
> 
> 测试
> System.out.println(JSON.parseObject("{"feeRate":0,"level":1}", LevelFeeRateEnum.class));
> 
> 报错
> com.alibaba.fastjson.JSONException: parse enum com.weibi.app.trade.model.core.match.LevelFeeRateEnum error, value : {"level":1,"feeRate":0}
> 
> ```
> at com.alibaba.fastjson.parser.deserializer.EnumDeserializer.deserialze(EnumDeserializer.java:104)
> at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:626)
> at com.alibaba.fastjson.JSON.parseObject(JSON.java:348)
> at com.alibaba.fastjson.JSON.parseObject(JSON.java:252)
> at com.alibaba.fastjson.JSON.parseObject(JSON.java:471)
> at J2SETest.testLevelFeeRateEnum(J2SETest.java:213)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
> at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
> at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
> at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
> ```
也遇到这个问题了，大佬找到解决方案了吗
