### ISSUE TITLE
BigDecimal成员变量转换失败，改成基础类型double转换成功

### ISSUE THREAD

**Issue by robinhoo2010** [alibaba/fastjson#2873]
com.alibaba.fastjson.JSONException: Invalid int: "49b6b6b733e292360be0-6041-4f8a-b1b7-95afc0eb8cbb.pngpngxT3ybXkv1rNlTHwAAACMAAQED&zoom=originala6d0cbf3e8f25e24.jpg/132��������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������"
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:687)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:383)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:351)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:314)
        at xxx.util.NetUtils.getResult(NetUtils.java:1060)
        at xxx$12.onResponse(ReserveAddActivity.java:576)
        at xxx$12.onResponse(ReserveAddActivity.java:573)
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:67)
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:30)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5765)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
     Caused by: java.lang.NumberFormatException: Invalid int: "49b6b6b733e292360be0-6041-4f8a-b1b7-95afc0eb8cbb.pngpngxT3ybXkv1rNlTHwAAACMAAQED&zoom=originala6d0cbf3e8f25e24.jpg/132��������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������"
        at java.lang.Integer.invalidInt(Integer.java:138)
        at java.lang.Integer.parse(Integer.java:410)
        at java.lang.Integer.parseInt(Integer.java:367)
        at java.lang.Integer.parseInt(Integer.java:334)
        at java.math.BigDecimal.<init>(BigDecimal.java:336)
        at java.math.BigDecimal.<init>(BigDecimal.java:390)
        at com.alibaba.fastjson.parser.JSONLexerBase.scanFieldDecimal(JSONLexerBase.java:3711)
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:573)
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:288)
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:284)
        at com.alibaba.fastjson.parser.deserializer.ArrayListTypeFieldDeserializer.parseArray(ArrayListTypeFieldDeserializer.java:177)
    	at com.alibaba.fastjson.parser.deserializer.ArrayListTypeFieldDeserialize

**Comment by Omega-Ariston** [comment]
能提供个简单的复现用例吗 :)

**Comment by youngking28** [comment]
> 能提供个简单的复现用例吗 :)

这个我也遇到了，是在安卓环境下。转换到bigdecimal会有问题。我用的1.2.62

**Comment by oujianqin** [comment]
这个问题我也遇到过，只在Android上这样，这种情况是实体类的所有成员类型都是BigDecimal的情况才会这样。
