### ISSUE TITLE
不支持Queue的反序列化

### ISSUE THREAD

**Issue by revanforthis** [alibaba/fastjson#2914]
之前有Issue说1.2.55版本已经修复，但实际使用发现依然不支持Queue的反序列化。

自定义类如下：
public class Complex {

    private Queue<String> blockQueue;

    public static Complex init() {
        Complex complex = new Complex();

        complex.blockQueue = new ArrayBlockingQueue<String>(5);
        complex.blockQueue.offer("BlockQueue 1");
        complex.blockQueue.offer("BlockQueue 2");
        complex.blockQueue.offer("BlockQueue 3");
        return complex;
    }

    public Queue<String> getBlockQueue() {
        return blockQueue;
    }

    public void setBlockQueue(Queue<String> blockQueue) {
        this.blockQueue = blockQueue;
    }
}

调用方法：
    public static void main(String[] args) {
        Complex complex = Complex.init();
        String jsonString = JSON.toJSONString(complex);
        System.out.println(jsonString);
        JSON.parseObject(jsonString, Complex.class);
        System.out.println();
    }

输出内容：
{"blockQueue":["BlockQueue 1","BlockQueue 2","BlockQueue 3"]}
Exception in thread "main" com.alibaba.fastjson.JSONException: java.util.Queue
	at com.alibaba.fastjson.parser.JSONScanner.newCollectionByType(JSONScanner.java:1245)
	at com.alibaba.fastjson.parser.JSONScanner.scanFieldStringArray(JSONScanner.java:1266)
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_1_Complex.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:284)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:687)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:383)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:287)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:560)
	at com.revan.file.TestComplex.main(TestComplex.java:14)
Caused by: java.lang.InstantiationException: java.util.Queue
	at java.lang.Class.newInstance(Class.java:427)
	at com.alibaba.fastjson.parser.JSONScanner.newCollectionByType(JSONScanner.java:1242)
	... 8 more
Caused by: java.lang.NoSuchMethodException: java.util.Queue.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 9 more

查看到对应报错类：
    public Collection<String> newCollectionByType(Class<?> type){
        if (type.isAssignableFrom(HashSet.class)) {
            HashSet<String> list = new HashSet<String>();
            return list;
        } else if (type.isAssignableFrom(ArrayList.class)) {
            ArrayList<String> list2 = new ArrayList<String>();
            return list2;
        } else {
            try {
                Collection<String> list = (Collection<String>) type.newInstance();
                return list;
            } catch (Exception e) {
                throw new JSONException(e.getMessage(), e);
            }
        }
    }
发现的确不支持Queue的类型

**Comment by juliuszhang** [comment]
根据你提供的例子 我在1.2.55版本queue的反序列化正常执行，复现不出来错误

**Comment by revanforthis** [comment]
再次验证，完全起了一个新环境，依然复现。jdk 6-8

**Comment by revanforthis** [comment]
同时找同事也验证了一次，同样的结果。我们之间有什么环境不一样吗？

**Comment by hulog** [comment]
@juliuszhang 俺也一样，没有问题
```java
JSON.toJSONString(complex)
// {"blockQueue":["BlockQueue 1","BlockQueue 2","BlockQueue 3"]}
JSON.parseObject(jsonString, Complex.class)
//com.alibaba.fastjson.deserializer.issue2914.Issue2914Test$Complex@3d3fcdb0
```

**Comment by revanforthis** [comment]
[fastjson.zip](https://github.com/alibaba/fastjson/files/3914473/fastjson.zip)
上传了测试demo，使用方式应该没问题的吧。

**Comment by hulog** [comment]
好像是喔，莫非作者上传错jar了？

**Comment by dsying** [comment]
private Queue<Integer> blockQueue;
是可以的

**Comment by revanforthis** [comment]
是的，Queue<Integer>可以，但是String不行，走的逻辑不一样，String会走到JSONScanner的newCollectionByType(Class<?> type)方法，但是Integer的不会

**Comment by dsying** [comment]
> 是的，Queue可以，但是String不行，走的逻辑不一样，String会走到JSONScanner的newCollectionByType(Class<?> type)方法，但是Integer的不会

![image](https://user-images.githubusercontent.com/33724768/70609415-b647dd80-1c3c-11ea-9556-fc16687df016.png)

![image](https://user-images.githubusercontent.com/33724768/70609571-fd35d300-1c3c-11ea-8752-4c81d2f09f43.png)

**Comment by kimmking** [comment]
确认bug，fix soon

**Comment by kimmking** [comment]
https://github.com/alibaba/fastjson/pull/2936
