### ISSUE TITLE
com.alibaba.fastjson.JSONException: create asm serializer error, verson 1.2.62

### ISSUE THREAD

**Issue by hyzhangit** [alibaba/fastjson#2976]
# 报错信息
```java
com.alibaba.fastjson.JSONException: create asm serializer error, verson 1.2.62
at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:264)
	at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:120)
	at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:792)
	at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:436)
	at com.alibaba.fastjson.serializer.JSONSerializer.getObjectWriter(JSONSerializer.java:416)
	at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:128)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:285)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:745)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:683)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:648)
        ...
Caused by: java.lang.NullPointerException
	at com.alibaba.fastjson.serializer.ASMSerializerFactory.createJavaBeanSerializer(ASMSerializerFactory.java:151)
	at com.alibaba.fastjson.serializer.SerializeConfig.createASMSerializer(SerializeConfig.java:92)
	at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:248)
	... 48 more
```
# 问题定位
## 查看代码
代码摘自`com.alibaba.fastjson.serializer.ASMSerializerFactory#createJavaBeanSerializer`
```java
141	        Package pkg = ASMSerializerFactory.class.getPackage();
142	        if (pkg != null) {
143	            String packageName = pkg.getName();
144	            classNameType = packageName.replace('.', '/') + "/" + className;
145	            classNameFull = packageName + "." + className;
146	        } else {
147	            classNameType = className;
148	            classNameFull = className;
149	        }
150	
151	        String packageName = ASMSerializerFactory.class.getPackage().getName();
```
## 问题如下
> 1. 141行已经定义了变量pkg`Package pkg = ASMSerializerFactory.class.getPackage();`，151行在使用时没有进行复用(String packageName = `ASMSerializerFactory.class.getPackage()`.getName();)
> 2. 142行在使用pkg变量时进行了判空，但是151没有判空保护，所以导致了后面的空指针
> 3.  实际上151行代码定义的变量packageName在后续并没有使用到

# 尝试解决
删除151行代码后重新编译，替换class，问题解决

**Comment by MVP2142** [comment]
估计是修复issue [#1652](https://github.com/alibaba/fastjson/issues/1652)时，少删了一行代码，对应[commit](https://github.com/alibaba/fastjson/commit/677aa67ee9c9bab76446b15e7309264ee0dce15e#diff-322b80afb97f66a8b42f64a007ac148a)。

我的情况是，在Idea中，使用MavenHelper插件，单元测试使用Mockito，代码中调用JSONObject.toJSONString(obj)时，在插件的Run Maven模式下运行正常，但是在插件的Debug Maven模式下会抛NPE。
