### ISSUE TITLE
有属性为BigDecimal的类,没有办法被解析请教下各位大佬

### ISSUE THREAD

**Issue by ZyqChina** [alibaba/fastjson#2977]
实体类:
public class AssetEntity implements Serializable {
    private static final long serialVersionUID = 1L;

    private Long id;

    private Long userId;

    private BigDecimal cwf;

    private BigDecimal uuk;

    private Date createTime;

}

测试用例:
public class bigDecimal {

    public static void main(String[] args) {

        String a = "[{\"cwf\":9999.999900,\"createTime\":\"2020-01-06 14:09:45\",\"uuk\":9999.999000,\"id\":1,\"userId\":662700059}]";
        AssetEntity assetEntity = JSONArray.parseObject(a, AssetEntity.class,Feature.UseBigDecimal);

    }
}

错误:
Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error, expect {, actual [, pos 0, fastjson-version 1.2.45
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:451)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:1267)
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_1_AssetEntity.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:267)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:661)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:633)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:315)
	at bigDecimal.main(bigDecimal.java:23)

Process finished with exit code 1

请教下我这个如何解决,或者如何正确使用

**Comment by kiddingYang** [comment]
这个json是一个数组,所以需要转成一个List

`String a = "[{\"cwf\":9999.999900,\"createTime\":\"2020-01-06 14:09:45\",\"uuk\":9999.999000,\"id\":1,\"userId\":662700059}]";
        List<AssetEntity> assetEntities = JSONArray.parseArray(a, AssetEntity.class);`

像这样就可以了.
