### ISSUE TITLE
autoType is not support. org.springframework.jdbc.UncategorizedSQLException

### ISSUE THREAD

**Issue by hellojamie** [alibaba/fastjson#2999]
测试代码如下，求解（100%复现）
public class TestMain {
	public static void main(String[] args) {
		ParserConfig.getGlobalInstance().setAutoTypeSupport(true);
		String param = "{\"@type\":\"org.springframework.jdbc.UncategorizedSQLException\"}";
		JSONObject resJson = JSON.parseObject(param);
		System.out.println(resJson);
	}
}

报错信息：
Exception in thread "main" com.alibaba.fastjson.JSONException: autoType is not support. org.springframework.jdbc.UncategorizedSQLException
	at com.alibaba.fastjson.parser.ParserConfig.checkAutoType(ParserConfig.java:1023)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:316)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1367)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1333)
	at com.alibaba.fastjson.JSON.parse(JSON.java:155)
	at com.alibaba.fastjson.JSON.parse(JSON.java:165)
	at com.alibaba.fastjson.JSON.parse(JSON.java:134)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:226)
	at com.TestMain.main(TestMain.java:13)

使用依赖
<dependency>
	   <groupId>com.alibaba</groupId>
	   <artifactId>fastjson</artifactId>
	   <version>1.2.53</version>
</dependency>

**Comment by xiantang** [comment]
I found a solution
```java 
ParserConfig.getGlobalInstance().setAutoTypeSupport(true);
String param = "{\"@type\":\"org.springframework.jdbc.UncategorizedSQLException\"}";
JSONObject resJson = JSON.parseObject(param,DisableSpecialKeyDetect);
System.out.println(resJson);
```
