### ISSUE TITLE
反序列化问题

### ISSUE THREAD

**Issue by kaizen84** [alibaba/fastjson#3014]
代码如下
**deserializer类**
`
import com.alibaba.fastjson.JSONArray;
import com.howhan.cloud.e.spring.autoconfigure.exception.GeometryFormatException;
import com.howhan.cloud.e.spring.autoconfigure.utils.GeometryUtil;
import com.vividsolutions.jts.geom.Geometry;

public class PolygonDeserializer extends AbstractGeometryDeserializer {
    @Override
    protected Geometry produce(Object value) {
        if (value instanceof JSONArray){
            /*
             * 最后一个点和初始点一致 形成闭环
             * */
            JSONArray array = (JSONArray)value;
            try{
                /*
         * 最后一个点和初始点一致 形成闭环
         * */
        if (
            !points.get(0)[0] .equals(points.get(points.size()-1)[0]) ||
            !points.get(0)[1] .equals(points.get(points.size()-1)[1])
        ){
            points.add(points.get(0));
        }

        Coordinate[] coordinates = points.stream().map(
            point -> new Coordinate(point[0], point[1])
        ).toArray(Coordinate[]::new);

        GeometryFactory factory = factory = new GeometryFactory(newPrecisionModel(PrecisionModel.FLOATING), 4326);

        return  factory.createPolygon(coordinates);
            }catch (Exception e){
                e.printStackTrace();
            }
        }
        throw new GeometryFormatException("错误的格式");
    }
}
`
**测试代码**
`
@Test
    public void deserializer(){
        String value = "{\"id\":4,\"name\":\"浦东新区\",\"telephone\":\"123456\",\"address\":\"上海浦东\",\"location\":[[121.62456900000001,31.278098],[121.616569,31.278098],[121.616569,31.271098000000002],[121.62456900000001,31.271098000000002]]}";
        JSONObject jsonObject = JSONObject.parseObject(value);
        ParserConfig globalInstance = ParserConfig.getGlobalInstance();
        globalInstance.putDeserializer(Polygon.class,new PolygonDeserializer());
        CustomerDoorVO customerDoorVO = jsonObject.toJavaObject(CustomerDoorVO.class, globalInstance, 0);
        System.out.println(1);
    }
`

**Comment by kaizen84** [comment]
```java
import com.alibaba.fastjson.JSONArray;
import com.howhan.cloud.e.spring.autoconfigure.exception.GeometryFormatException;
import com.howhan.cloud.e.spring.autoconfigure.utils.GeometryUtil;
import com.vividsolutions.jts.geom.Geometry;

public class PolygonDeserializer extends AbstractGeometryDeserializer {
    @Override
    protected Geometry produce(Object value) {
        if (value instanceof JSONArray){
            /*
             * 最后一个点和初始点一致 形成闭环
             * */
            JSONArray array = (JSONArray)value;
            try{
                /*
         * 最后一个点和初始点一致 形成闭环
         * */
        if (
            !points.get(0)[0] .equals(points.get(points.size()-1)[0]) ||
            !points.get(0)[1] .equals(points.get(points.size()-1)[1])
        ){
            points.add(points.get(0));
        }

        Coordinate[] coordinates = points.stream().map(
            point -> new Coordinate(point[0], point[1])
        ).toArray(Coordinate[]::new);

        GeometryFactory factory = factory = new GeometryFactory(newPrecisionModel(PrecisionModel.FLOATING), 4326);

        return  factory.createPolygon(coordinates);
            }catch (Exception e){
                e.printStackTrace();
            }
        }
        throw new GeometryFormatException("错误的格式");
    }
}
 ```

**Comment by kaizen84** [comment]
**异常信息**
```
com.alibaba.fastjson.JSONException: not close json text, token : [

	at com.alibaba.fastjson.util.TypeUtils.castToJavaBean(TypeUtils.java:1378)
	at com.alibaba.fastjson.JSONObject.toJavaObject(JSONObject.java:611)
	at CTest.deserializer(CTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.alibaba.fastjson.JSONException: not close json text, token : [
	at com.alibaba.fastjson.parser.DefaultJSONParser.close(DefaultJSONParser.java:1526)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:387)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:287)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:560)
	at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:1069)
	at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:1134)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.createInstance(JavaBeanDeserializer.java:1421)
	at com.alibaba.fastjson.util.TypeUtils.castToJavaBean(TypeUtils.java:1376)
	... 24 more
```

**Comment by kaizen84** [comment]
**数据格式是正确的**
