### ISSUE TITLE
osgi项目使用fastjson报错

### ISSUE THREAD

**Issue by zhaihailong** [alibaba/fastjson#3018]
karaf-osgi项目，pom文件引入fastjson没有问题，使用后运行出错，有没有人遇到过，知道一下；

org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=netconfig; type=karaf.feature; version="[1.0.0,1.0.0]"; filter:="(&(osgi.identity=netconfig)(type=karaf.feature)(version>=1.0.0)(version<=1.0.0))" [caused by: Unable to resolve netconfig/1.0.0: missing requirement [netconfig/1.0.0] osgi.identity; osgi.identity=com.netconfig.service.operatelog; type=osgi.bundle; version="[1.0.0,1.0.0]"; resolution:=mandatory [caused by: Unable to resolve com.netconfig.service.operatelog/1.0.0: missing requirement [com.netconfig.service.operatelog/1.0.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.netconfig.net.devices)(version>=1.0.0)(!(version>=2.0.0)))" [caused by: Unable to resolve com.netconfig.net.devices/1.0.0: missing requirement [com.netconfig.net.devices/1.0.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.netconfig.addressing)(version>=1.0.0)(!(version>=2.0.0)))" [caused by: Unable to resolve com.netconfig.net.util/1.0.0: missing requirement [com.netconfig.net.util/1.0.0] osgi.wiring.package; filter:="(osgi.wiring.package=com.alibaba.fastjson)"]]]]
	at org.apache.felix.resolver.ResolutionError.toException(ResolutionError.java:42)[9:org.apache.karaf.features.core:4.0.8]
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:389)[9:org.apache.karaf.features.core:4.0.8]
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:375)[9:org.apache.karaf.features.core:4.0.8]
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:347)[9:org.apache.karaf.features.core:4.0.8]
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:216)[9:org.apache.karaf.features.core:4.0.8]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:263)[9:org.apache.karaf.features.core:4.0.8]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1176)[9:org.apache.karaf.features.core:4.0.8]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1074)[9:org.apache.karaf.features.core:4.0.8]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[:1.8.0_231]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_231]

**Comment by BoyuanYan** [comment]
请问最后解决了吗？遇到同样问题了。。。
