### ISSUE TITLE
不能正确处理一些Unicode字符

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/fastjson#304]
测试代码：
```java
		JSONObject o = new JSONObject();
		o.put("test", "Intki_E96? Build");
		System.err.println(o.toJSONString());
		Object object = JSON.parse(o.toJSONString());
		System.err.println(object);
```
异常：
```java
Exception in thread "main" com.alibaba.fastjson.JSONException: unclosed single-quote string
	at com.alibaba.fastjson.parser.JSONLexerBase.scanStringSingleQuote(JSONLexerBase.java:2677)
	at com.alibaba.fastjson.parser.JSONLexerBase.nextToken(JSONLexerBase.java:144)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:470)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1236)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1205)
	at com.alibaba.fastjson.JSON.parse(JSON.java:108)
	at com.alibaba.fastjson.JSON.parse(JSON.java:99)
```

**Comment by hengyunabc** [comment]
那个字符串粘到github上被干掉了。。貌似最新版修复了这个问题。1.1.35有问题。
但是最新版处理这个还是有问题：
```java
		String ss = "{'a':'Intki_E96?\u001A Build'}";
		System.err.println(ss);
		Object sss = JSON.parse(ss);
```

这个\u001A 貌似是个合法的Unicode字符，历史遗留物。

http://stackoverflow.com/questions/17024436/what-is-the-unicode-u001a-character-aka-0x1a

**Comment by wenshao** [comment]
bug fixed. included in 1.2.9 & 1.1.49.android.
