### ISSUE TITLE
JSON.parseObject发生异常

### ISSUE THREAD

**Issue by easysg** [alibaba/fastjson#306]
使用版本为1.1.27, 异常如下：
```java
com.alibaba.fastjson.JSONException
 at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:475)
 at com.alibaba.fastjson.JSON.parseObject(JSON.java:211)
 at com.alibaba.fastjson.JSON.parseObject(JSON.java:171)
 at com.alibaba.fastjson.JSON.parseObject(JSON.java:292)
...
Caused by: java.lang.NullPointerException
 at com.alibaba.fastjson.parser.SymbolTable.addSymbol(SymbolTable.java:74)
 at com.alibaba.fastjson.parser.JSONScanner.scanSymbol(JSONScanner.java:1690)
 at com.alibaba.fastjson.parser.JSONScanner.scanSymbol(JSONScanner.java:1550)
 at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:164)
 at com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer.deserialze(ASMJavaBeanDeserializer.java:31)

```

**Comment by wenshao** [comment]
重写了SymbolTable，不会再有这个问题啦

**Comment by caiqq1989** [comment]
@wenshao 具体在哪个版本中体现？
