### ISSUE TITLE
反序列化超大JSON数组时，报索引越界的错误

### ISSUE THREAD

**Issue by lipeng1234** [alibaba/fastjson#307]
// 测试代码如下：
public static void read2() throws FileNotFoundException {
		JSONReader reader = new JSONReader(new FileReader("D://huge2.json"));
		reader.startArray();
		while (reader.hasNext()) {
			User user = reader.readObject(User.class);
			System.out.println(user.getId());
		}
		reader.endArray();
		reader.close();
	}

每次都是在循环读取到第286个User对象的时候报错，
错误信息如下：
Exception in thread "main" com.alibaba.fastjson.JSONException: -1
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:555)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:523)
	at com.alibaba.fastjson.JSONReader.readObject(JSONReader.java:204)
	at com.sexycat.lipeng.HugeTest.read2(HugeTest.java:77)
	at com.sexycat.lipeng.HugeTest.main(HugeTest.java:86)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at com.alibaba.fastjson.parser.JSONReaderScanner.charAt(JSONReaderScanner.java:126)
	at com.alibaba.fastjson.parser.JSONLexerBase.longValue(JSONLexerBase.java:2919)
	at com.alibaba.fastjson.serializer.LongCodec.deserialze(LongCodec.java:65)
	at Fastjson_ASM_User_1.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)
	... 4 more

**Comment by dongritengfei** [comment]
我也偶尔碰到了这种情况，应该是fastjson的reader.readObject(User.class);方法里面有问题。如果你改成如下的代码就ok了：
```java
public static void read2() throws FileNotFoundException {
    JSONReader reader = new JSONReader(new FileReader("D://huge2.json"));
    reader.startArray();
    while (reader.hasNext()) {
        String str = reader.readString();
        User user = JSONObject.parse(str, User.class);
        System.out.println(user.getId());
    }
    reader.endArray();
    reader.close();
}
```

fastjson的开发同学可以仔细查一下JSONObject.parse和JSONReader.readObject里面的feature设置有何不同，导致这个bug

**Comment by lipeng1234** [comment]
感谢楼上高手解答，不过你有一个笔误，不应该是“JSONObject.parse(str, User.class);”，我跑到你博客上看到应该是“JSONObject.parseObject(str, User.class);”这样才对。
