### ISSUE TITLE
序列化timestamp字段时，指定SerializerFeature.UseISO8601DateFormat, 当nanos为9位数值时，报ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by murphyzeng** [alibaba/fastjson#3088]
fastjson version：1.2.67

stack trace:
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 29
	at com.alibaba.fastjson.util.IOUtils.getChars(IOUtils.java:279)
	at com.alibaba.fastjson.serializer.DateCodec.write(DateCodec.java:159)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:285)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:745)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:679)
	at com.ctrip.gs.dest.common.util.JsonUtility.toJsonString(JsonUtility.java:83)
	at com.ctrip.gs.dest.common.util.JsonUtility.toString(JsonUtility.java:24)
	at com.ctrip.gs.dest.common.app.App.main(App.java:36)

test code:
```java
public class JsonTest {
    public static void main(String[] args){
        Timestamp ts = new Timestamp(Calendar.getInstance().getTimeInMillis());
        String json = toJsonString(ts);

        System.out.println(json);
    }

    private static <T> String toJsonString(T obj) {
        ArrayList<SerializerFeature> allFeatures = new ArrayList<>();
        allFeatures.add(SerializerFeature.UseISO8601DateFormat);

        return JSON.toJSONString(obj, allFeatures.toArray(new SerializerFeature[0]));
    }
}
```

cause:
DateCodec.java
```if (nanos > 0) {
                buf = "0000-00-00 00:00:00.000000000".toCharArray();
                int nanoSize = IOUtils.stringSize(nanos);
                IOUtils.getChars(nanos, 30 - (9 - nanoSize), buf);
                IOUtils.getChars(second, 19, buf);
                IOUtils.getChars(minute, 16, buf);
                IOUtils.getChars(hour, 13, buf);
                IOUtils.getChars(day, 10, buf);
                IOUtils.getChars(month, 7, buf);
                IOUtils.getChars(year, 4, buf);
            }
```

buf的长度是29, IOUtils.getChars(nanos, 30 - (9 - nanoSize), buf)，当nanoSize=9的时候， IOUtils.getChars里的buf[--p] = DigitOnes[r]这行回报数组越界，因为--p=29。

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson/releases/tag/1.2.68
问题已修复，请用新版本

**Comment by murphyzeng** [comment]
谢谢。
