### ISSUE TITLE
反序列化Map<key, value>裡的key值如果有冒號會出問題, 中文字碼會造成混亂?

### ISSUE THREAD

**Issue by unoya** [alibaba/fastjson#313]
**作業系統:** win7 - 64bit
**Java SDK:** 1.7.0_75-b13
**編程環境:** Eclipse Luna Service Release 2 (4.4.2)
**Fastjson:** fastjson-1.2.5
我是MinecraftForge的編程者, 有一份json資料如下:

    {
    	"OreMsgData":{
    		"minecraft:gold_ore":{
    			"ChName":"金礦",
    			"FontColor":14
    		},
    		"minecraft:iron_ore":{
    			"ChName":"鐵礦",
    			"FontColor":6
    		}
    	}
    }
在eclipse runtime環境下不會出任何問題, 但實際在Minecraft運行時卻報出語法錯誤的問題, 一直找不出答案, 然後我在fastjson的GitHub裡的 Issues #296 看到有其他人回報類似這樣子的問題, 我在想或許跟我也有關係, 初步研判在建立Json格式方面沒問題, 出問題在於反序列化json格式方面 , 請幫忙查核, 謝謝.

主程序(Main):

    JsonOreMsgColor jomc = new JsonOreMsgColor();
    jomc.add("minecraft:gold_ore", "金礦", 14);
    jomc.add("minecraft:iron_ore", "鐵礦", 6);
    String orecolorstr = JSON.toJSONString(jomc, SerializerFeature.PrettyFormat);
    try {
    	OutputStreamWriter outputSW = new OutputStreamWriter(new FileOutputStream(new File("test.json")), "UTF-8");
    	outputSW.write(orecolorstr);
    	outputSW.close();
    } catch (IOException e) {
    	e.printStackTrace();
    }

JsonOreMsgColor.class

    public Map<String, ColorInfo> OreMsgData = new HashMap<String, ColorInfo>();
    public JsonOreMsgColor(){}
    public JsonOreMsgColor(String oreID, String cname, int colorcode){
    		if(!this.OreMsgData.containsKey(oreID)){
    			this.OreMsgData.put(oreID, new ColorInfo(cname, colorcode));
    		}
    }

ColorInfo.class

    @JSONField(name="ChName", ordinal=1)
    private String cname;
    @JSONField(name="FontColor", ordinal=2)
    private int color;
    
    public ColorInfo(){}
    public ColorInfo(String name, int fcolor){
	    this.cname = name;
    	this.color = fcolor;
    }
    
    @JSONField(name="ChName")
    public void setName(String name){
    	this.cname = name.trim();
    }
    
    @JSONField(name="FontColor")
    public void setColor(int color){
    	this.color = color;
    }
    
    @JSONField(name="ChName")
    public String getName(){
    	return this.cname;
    }
    
    @JSONField(name="FontColor")
    public int getColor(){
    	return this.color;
    }

	
CfgFileProcess.class

	    public static JsonOreMsgColor oremsgcolor = new JsonOreMsgColor();
    	public void reload_OreMsgColor(){
    		try {
    			JSONReader reader = new JSONReader(new FileReader(new File("test.json")));
    			this.oremsgcolor = reader.readObject(JsonOreMsgColor.class);
    			reader.close();
    		} catch (FileNotFoundException e) {
    			e.printStackTrace();
    		}
    	}

報錯資訊檔內容:

    com.alibaba.fastjson.JSONException: syntax error, unexpect token error
    	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:350)
    	at com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer.parseRest(ASMJavaBeanDeserializer.java:100)
    	at Fastjson_ASM_ColorInfo_10.deserialze(Unknown Source)
    	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)
    	at com.alibaba.fastjson.parser.deserializer.MapDeserializer.parseMap(MapDeserializer.java:164)
    	at com.alibaba.fastjson.parser.deserializer.MapDeserializer.deserialze(MapDeserializer.java:58)
    	at com.alibaba.fastjson.parser.deserializer.MapDeserializer.deserialze(MapDeserializer.java:44)
    	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:33)
    	at com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer.parseField(ASMJavaBeanDeserializer.java:74)
    	at com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer$InnerJavaBeanDeserializer.parseField(ASMJavaBeanDeserializer.java:86)
    	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:330)
    	at com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer.parseRest(ASMJavaBeanDeserializer.java:100)
    	at Fastjson_ASM_JsonOreMsgColor_9.deserialze(Unknown Source)
    	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)
    	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:523)
    	at com.alibaba.fastjson.JSONReader.readObject(JSONReader.java:200)
    	at svc.CfgFileProcess.reload_OreMsgColor(CfgFileProcess.java:258)

備註: 我另外實驗了一個方式, 把原本json內容改成如下, 在處理程序上只是將冒號符號replace"<>"而已, 但一樣會抛出錯誤, 錯誤代碼一樣是 "syntax error, unexpect token error", 看來似乎是fastjson對中文字不相容.

    {
    	"OreMsgData":{
    		"minecraft<>iron_ore":{
    			"color":6,
    			"name":"鐵礦"
    		},
    
    		"minecraft<>gold_ore":{
    			"color":14,
    			"name":"金礦"
    		}
    	}
    }

**Comment by shellj** [comment]
我用你的代码在我这里跑了一下，结果没问题。
fastjson版本：
```xml
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.1.36</version>
        </dependency>
```
java代码：
```java
public static void main(String[] args) throws Exception {
        JsonOreMsgColor oremsgcolor;
        JSONReader reader = new JSONReader(new FileReader(new File("hello.json")));
        oremsgcolor = reader.readObject(JsonOreMsgColor.class);
        reader.close();
        for (String key : oremsgcolor.OreMsgData.keySet()) {
            ColorInfo colorInfo = oremsgcolor.OreMsgData.get(key);
            System.out.println("key:[" + key + "] ,ChName:[" + colorInfo.getName() + "] ,FontColor:[" + colorInfo.getColor() + "]");
        }
    }
```
json文件内容：
```json
{"OreMsgData":{"minecraft:gold_ore":{"ChName":"金礦","FontColor":14},"minecraft:iron_ore":{"ChName":"鐵礦","FontColor":6}}}
```
结果：
```html
key:[minecraft:gold_ore] ,ChName:[金礦] ,FontColor:[14]
key:[minecraft:iron_ore] ,ChName:[鐵礦] ,FontColor:[6]
```
不知你用的那个版本。

**Comment by unoya** [comment]
非常感謝幫我測試, 我自己後來一直在想字元碼的問題, 我把主程序(Main)改成如下:
主程序(Main):

    JsonOreMsgColor jomc = new JsonOreMsgColor();
	jomc.add("minecraft:gold_ore", "\u91d1\u7926", 14); // 把金礦改成Unicode
	jomc.add("minecraft:iron_ore", "\u9435\u7926", 6); // 把鐵礦改成Unicode
    String orecolorstr = JSON.toJSONString(jomc, SerializerFeature.PrettyFormat);
    try {
    	OutputStreamWriter outputSW = new OutputStreamWriter(new FileOutputStream(new File("test.json"))); // 我把UTF-8拿掉
    	outputSW.write(orecolorstr);
    	outputSW.close();
    } catch (IOException e) {
    	e.printStackTrace();
    }

這樣子就沒再出現那個錯誤訊息, 我也搞不懂到底問題點是什麼, 因為我這個程序是由 MinecraftForge 在跑的, 不是直接 java 去 run 的, 所以我也無法得知問題徵結點在哪.
至少, 現在知道我用的這版FastJson沒問題, 我就能安心使用了.
再次非常感謝實測.
