### ISSUE TITLE
循环引用bug，某些用法下有循环引的会报错

### ISSUE THREAD

**Issue by buzilong** [alibaba/fastjson#3149]
版本：1.2.68
场景：有循环引用的bean，在调用getJSONArray后，调用jsonArray的getJSONObject 方法
错误信息：
Exception in thread "main" java.lang.StackOverflowError
	at com.alibaba.fastjson.parser.ParserConfig.isPrimitive2(ParserConfig.java:1072)
	at com.alibaba.fastjson.JSON.toJSON(JSON.java:1096)
	at com.alibaba.fastjson.JSON.toJSON(JSON.java:1064)
	at com.alibaba.fastjson.JSON.toJSON(JSON.java:1108)
	at com.alibaba.fastjson.JSON.toJSON(JSON.java:1064)
	at com.alibaba.fastjson.JSON.toJSON(JSON.java:1108)
	at com.alibaba.fastjson.JSON.toJSON(JSON.java:1064)
	at com.alibaba.fastjson.JSON.toJSON(JSON.java:1108)
	at com.alibaba.fastjson.JSON.toJSON(JSON.java:1064)
	at com.alibaba.fastjson.JSON.toJSON(JSON.java:1108)
	at com.alibaba.fastjson.JSON.toJSON(JSON.java:1064)

附件是会报错的代码
[TEST.java.txt](https://github.com/alibaba/fastjson/files/4597572/TEST.java.txt)

**Comment by buzilong** [comment]
为什么没有回复呢

**Comment by Tloops** [comment]
请问有人正在处理这个问题吗？我对这个issue挺感兴趣的，我想在最近的几个月内尝试处理这个bug
