### ISSUE TITLE
同一个请求，原始字符串请求不能转成对象，字符串换行后【美化】能正常请求；

### ISSUE THREAD

**Issue by gardenerHan** [alibaba/fastjson#3183]
同一个请求，原始字符串不能转成对象，字符串换行后【美化】能正常请求；
原始字符串为：
{"pubRequest":{"token":"21323123124545","sign":"","signType":""},"body":{"accountNo":"57677686756576","button":[{"appid":"","media_id":"","menuNo":"","msgText":"","msgType":"","name":"2323434","pagepath":"","priority":0,"richMsgList":"","subButton":[{"appid":"","media_id":"","menuNo":"","msgText":"","msgType":"","name":"23423434234","pagepath":"","priority":2,"richMsgList":"","subButton":[],"type":"URL","url":"http://wxm.pmpsys.cn/2342342342342/mine.jspx","richMsgs":[{"priority":0,"msgTitle":"","msgImgUrl":"","msgDes":"","msgUrl":""},{"priority":1,"msgTitle":"","msgImgUrl":"","msgDes":"","msgUrl":""}]},{"appid":"","media_id":"","menuNo":"","msgText":"","msgType":"","name":"2342342343","pagepath":"","priority":1,"richMsgList":"","subButton":[],"type":"URL","url":"http://wxm.2342342343.cn/wx-07600c96-01ce/index.jspx","richMsgs":[{"priority":0,"msgTitle":"","msgImgUrl":"","msgDes":"","msgUrl":""},{"priority":1,"msgTitle":"","msgImgUrl":"","msgDes":"","msgUrl":""}]}],"type":"","url":"","richMsgs":[{"priority":0,"msgTitle":"","msgImgUrl":"","msgDes":"","msgUrl":""},{"priority":1,"msgTitle":"","msgImgUrl":"","msgDes":"","msgUrl":""}]},{"appid":"","media_id":"","menuNo":"","msgText":"","msgType":"","name":"线圈","pagepath":"","priority":1,"richMsgList":"","subButton":[{"appid":"","media_id":"","menuNo":"24324","msgText":"","msgType":"","name":"23423423434","pagepath":"","priority":2,"richMsgList":"","subButton":[],"type":"MSG","url":"","richMsgs":[{"priority":0,"msgTitle":"","msgImgUrl":"","msgDes":"","msgUrl":""},{"priority":1,"msgTitle":"","msgImgUrl":"","msgDes":"","msgUrl":""}]},{"appid":"","media_id":"","menuNo":"","msgText":"","msgType":"","name":"我的线圈","pagepath":"","priority":1,"richMsgList":"","subButton":[],"type":"URL","url":"http://wxm.pmpsys.cn/32423-23423423-01ce/mxq.jspx","richMsgs":[{"priority":0,"msgTitle":"","msgImgUrl":"","msgDes":"","msgUrl":""},{"priority":1,"msgTitle":"","msgImgUrl":"","msgDes":"","msgUrl":""}]}],"type":"","url":"","richMsgs":[{"priority":0,"msgTitle":"","msgImgUrl":"","msgDes":"","msgUrl":""},{"priority":1,"msgTitle":"","msgImgUrl":"","msgDes":"","msgUrl":""}]},{"appid":"","media_id":"","menuNo":"nothing","msgText":"","msgType":"","name":"更多...","pagepath":"","priority":2,"richMsgList":"","subButton":[],"type":"MSG","url":"","richMsgs":[{"priority":0,"msgTitle":"","msgImgUrl":"","msgDes":"","msgUrl":""},{"priority":1,"msgTitle":"","msgImgUrl":"","msgDes":"","msgUrl":""}]}]}}

换行后字符串【美化】:

Content-Type: application/json

{
  "pubRequest": {
    "token": "21323123124545",
    "sign": "",
    "signType": ""
  },
  "body": {
    "accountNo": "57677686756576",
    "button": [
      {
        "appid": "",
        "media_id": "",
        "menuNo": "",
        "msgText": "",
        "msgType": "",
        "name": "2323434",
        "pagepath": "",
        "priority": 0,
        "richMsgList": "",
        "subButton": [
          {
            "appid": "",
            "media_id": "",
            "menuNo": "",
            "msgText": "",
            "msgType": "",
            "name": "23423434234",
            "pagepath": "",
            "priority": 2,
            "richMsgList": "",
            "subButton": [],
            "type": "URL",
            "url": "http://wxm.pmpsys.cn/2342342342342/mine.jspx",
            "richMsgs": [
              {
                "priority": 0,
                "msgTitle": "",
                "msgImgUrl": "",
                "msgDes": "",
                "msgUrl": ""
              },
              {
                "priority": 1,
                "msgTitle": "",
                "msgImgUrl": "",
                "msgDes": "",
                "msgUrl": ""
              }
            ]
          },
          {
            "appid": "",
            "media_id": "",
            "menuNo": "",
            "msgText": "",
            "msgType": "",
            "name": "2342342343",
            "pagepath": "",
            "priority": 1,
            "richMsgList": "",
            "subButton": [],
            "type": "URL",
            "url": "http://wxm.2342342343.cn/wx-07600c96-01ce/index.jspx",
            "richMsgs": [
              {
                "priority": 0,
                "msgTitle": "",
                "msgImgUrl": "",
                "msgDes": "",
                "msgUrl": ""
              },
              {
                "priority": 1,
                "msgTitle": "",
                "msgImgUrl": "",
                "msgDes": "",
                "msgUrl": ""
              }
            ]
          }
        ],
        "type": "",
        "url": "",
        "richMsgs": [
          {
            "priority": 0,
            "msgTitle": "",
            "msgImgUrl": "",
            "msgDes": "",
            "msgUrl": ""
          },
          {
            "priority": 1,
            "msgTitle": "",
            "msgImgUrl": "",
            "msgDes": "",
            "msgUrl": ""
          }
        ]
      },
      {
        "appid": "",
        "media_id": "",
        "menuNo": "",
        "msgText": "",
        "msgType": "",
        "name": "线圈",
        "pagepath": "",
        "priority": 1,
        "richMsgList": "",
        "subButton": [
          {
            "appid": "",
            "media_id": "",
            "menuNo": "24324",
            "msgText": "",
            "msgType": "",
            "name": "23423423434",
            "pagepath": "",
            "priority": 2,
            "richMsgList": "",
            "subButton": [],
            "type": "MSG",
            "url": "",
            "richMsgs": [
              {
                "priority": 0,
                "msgTitle": "",
                "msgImgUrl": "",
                "msgDes": "",
                "msgUrl": ""
              },
              {
                "priority": 1,
                "msgTitle": "",
                "msgImgUrl": "",
                "msgDes": "",
                "msgUrl": ""
              }
            ]
          },
          {
            "appid": "",
            "media_id": "",
            "menuNo": "",
            "msgText": "",
            "msgType": "",
            "name": "我的线圈",
            "pagepath": "",
            "priority": 1,
            "richMsgList": "",
            "subButton": [],
            "type": "URL",
            "url": "http://wxm.pmpsys.cn/32423-23423423-01ce/mxq.jspx",
            "richMsgs": [
              {
                "priority": 0,
                "msgTitle": "",
                "msgImgUrl": "",
                "msgDes": "",
                "msgUrl": ""
              },
              {
                "priority": 1,
                "msgTitle": "",
                "msgImgUrl": "",
                "msgDes": "",
                "msgUrl": ""
              }
            ]
          }
        ],
        "type": "",
        "url": "",
        "richMsgs": [
          {
            "priority": 0,
            "msgTitle": "",
            "msgImgUrl": "",
            "msgDes": "",
            "msgUrl": ""
          },
          {
            "priority": 1,
            "msgTitle": "",
            "msgImgUrl": "",
            "msgDes": "",
            "msgUrl": ""
          }
        ]
      },
      {
        "appid": "",
        "media_id": "",
        "menuNo": "nothing",
        "msgText": "",
        "msgType": "",
        "name": "更多...",
        "pagepath": "",
        "priority": 2,
        "richMsgList": "",
        "subButton": [],
        "type": "MSG",
        "url": "",
        "richMsgs": [
          {
            "priority": 0,
            "msgTitle": "",
            "msgImgUrl": "",
            "msgDes": "",
            "msgUrl": ""
          },
          {
            "priority": 1,
            "msgTitle": "",
            "msgImgUrl": "",
            "msgDes": "",
            "msgUrl": ""
          }
        ]
      }
    ]
  }
}

错误日志：

12:56:08.035 [http-nio-8080-exec-1] ERROR com.alibaba.fastjson.JSONException: syntax error, expect {, actual string, pos 237
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:370) ~[fastjson-1.2.32.jar:?]
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:1070) ~[fastjson-1.2.32.jar:?]
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_3_WxMenuDto.deserialze(Unknown Source) ~[?:?]
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:211) ~[fastjson-1.2.32.jar:?]
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_2_WxMenuSaveReqDto.deserialze(Unknown Source) ~[?:?]
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:211) ~[fastjson-1.2.32.jar:?]
	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:71) ~[fastjson-1.2.32.jar:?]
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:888) ~[fastjson-1.2.32.jar:?]
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:633) ~[fastjson-1.2.32.jar:?]
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:215) ~[fastjson-1.2.32.jar:?]
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:211) ~[fastjson-1.2.32.jar:?]
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:642) ~[fastjson-1.2.32.jar:?]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:354) ~[fastjson-1.2.32.jar:?]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:322) ~[fastjson-1.2.32.jar:?]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:285) ~[fastjson-1.2.32.jar:?]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:385) ~[fastjson-1.2.32.jar:?]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:467) ~[fastjson-1.2.32.jar:?]
	at com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter.read(FastJsonHttpMessageConverter.java:211) ~[fastjson-1.2.32.jar:?]
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:204) ~[spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:157) ~[spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:130) ~[spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:126) ~[spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:166) ~[spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134) ~[spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) ~[spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:151) [spring-session-core-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:81) [spring-session-core-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by diaodiaofly** [comment]
看错误信息fastjson版本是：1.3.32，我在jdk1.8的环境下测试了下，没有出现问题,转换正常！
![777777](https://user-images.githubusercontent.com/17794120/84045300-31673200-a9db-11ea-9415-90ea18b5c878.png)
