### ISSUE TITLE
请问spring使用的是jackson, 为啥我有些服务会走到fastjson里面的一些action呢。这次开启safeMode后spring授理请求报错。

### ISSUE THREAD

**Issue by berekqu** [alibaba/fastjson#3216]
备注：JSONObject里面实现了ObjectInputStream的resolveClass。开始safemode后，spring的异常如下：
Caused by: org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is com.alibaba.fastjson.JSONException: safeMode not support autoType : java.util.HashMap
        at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:78)
        at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:36)
        at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.deserialize(JdkSerializationRedisSerializer.java:80)
        ... 10 common frames omitted
Caused by: com.alibaba.fastjson.JSONException: safeMode not support autoType : java.util.HashMap
        at com.alibaba.fastjson.parser.ParserConfig.checkAutoType(ParserConfig.java:1244)
        at com.alibaba.fastjson.JSONObject$SecureObjectInputStream.resolveClass(JSONObject.java:574)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1819)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1986)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2231)
        at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:552)
        at com.alibaba.fastjson.JSONObject.readObject(JSONObject.java:503)
        at sun.reflect.GeneratedMethodAccessor694.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2122)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2231)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2155)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2231)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2155)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
        at org.springframework.core.serializer.DefaultDeserializer.deserialize(DefaultDeserializer.java:70)
        at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:73)
        ... 12 common frames omitted

**Comment by fangjinuo** [comment]
你需要这个：
https://github.com/fangjinuo/easyjson

**Comment by qqxx6661** [comment]
mark
