### ISSUE TITLE
json字符串判断异常？

### ISSUE THREAD

**Issue by kervin521** [alibaba/fastjson#3225]
com.alibaba.fastjson.JSONException: error : 1
	at com.alibaba.fastjson.JSONValidator.error(JSONValidator.java:319) ~[fastjson-1.2.68.jar:?]
	at com.alibaba.fastjson.JSONValidator.any(JSONValidator.java:148) ~[fastjson-1.2.68.jar:?]
	at com.alibaba.fastjson.JSONValidator.validate(JSONValidator.java:45) ~[fastjson-1.2.68.jar:?]

**Comment by kervin521** [comment]
原始代码：
```java

                                    Object data = value;
                                    if (JSON.isValid(value)) {
                                       if(JSON.isValidArray(value)) {
                                           data = JSON.parseArray(value,JSONObject.class);
                                       }else {
                                           data = JSON.parseObject(value, JSONObject.class);
                                       }
                                    }
```
改造后代码：
```java
                                   Object data = value;
                                    if (JSONValidator.from(value).validate()) {
                                       if(JSON.isValidArray(value)) {
                                           data = JSON.parseArray(value,JSONObject.class);
                                       }else {
                                           data = JSON.parseObject(value, JSONObject.class);
                                       }
                                    }
```

**Comment by AlanSune** [comment]
在**1.2.68（包含）**版本之前，**JSONValidator** 在验证失败后会抛出异常，并不会返回 **false**。
我也没搞懂为啥这样写，**validate()** 的返回值没有任何意义。
在 **1.2.68** 之后，才能根据返回值判断是否验证通过。
参考 **JSONValidator.java** 各版本变化。

**Comment by bigruid** [comment]
1.2.73校验失败也是直接抛异常....
