### ISSUE TITLE
fastjson 因漏洞升级到最新版本1.2.70导致（JSONArray）序列化失败（紧急）

### ISSUE THREAD

**Issue by wcyzhengzhou** [alibaba/fastjson#3253]
fastjson 因漏洞升级到最新版本1.2.70 通过json反序列化为map时｛'dd':‘ee’,tt： ['33']｝，tt类型为JSONArray，导致再次进行调用ejb服务序列化的时候失败，报错信息如下：
Caused by: java.io.InvalidClassException: ; enum descriptor has non-zero serialVersionUID: 1256758970417157
	at java.io.ObjectStreamClass.readNonProxy(ObjectStreamClass.java:636)
	at java.io.ObjectInputStream.readClassDescriptor(ObjectInputStream.java:809)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1565)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1496)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1732)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1329)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1947)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:480)
	at com.alibaba.fastjson.JSONArray.readObject(JSONArray.java:478)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:974)

**Comment by wcyzhengzhou** [comment]
jdk版本1.6

**Comment by wenshao** [comment]
原来是什么版本?

**Comment by wcyzhengzhou** [comment]
1.2.47

**Comment by shiqiangTang** [comment]
是不是两边的字段或者什么不一致哦

**Comment by wcyzhengzhou** [comment]
怎么可能jsonstr转map，然后进行ejb调用，参数为map，map中其中一个节点的数据类型是JSONArray在readObject方法报错了，ejb服务端就没有收到数据。并且我把数据那改改成｛'dd':‘ee’,tt： ｛'ww':'33'｝｝   反序列化map后tt的类型为JSONObject在进行ejb服务就没有问题，说白了JSONArray的readObject对list序列化会报错，这让我们系统的调整多少地方啊，能不能解决啊，工作都快丢了

**Comment by wcyzhengzhou** [comment]
大神，你这漏洞的坑多少人啊，我们全系统在升级，好几个系统都有这问题，安全监控很严的，在搞不定要失业了。

**Comment by wenshao** [comment]
@wcyzhengzhou 先用1.2.48.sec10修复吧，这个是因为java反序列化不兼容导致的。
https://repo.maven.apache.org/maven2/com/alibaba/fastjson/1.2.48.sec10/

**Comment by wcyzhengzhou** [comment]
1.2.48这个版本没有安全漏洞把，目前我们这边安全检查要求跟当时官网公布的版本要一则，这要回退到老版本，这个版本做什么调整了，可否告知

**Comment by wenshao** [comment]
1.2.48.sec10已修复已知漏洞

**Comment by wcyzhengzhou** [comment]
好的，多谢，请问最新版本会解决此兼容问题吗？如果解决会在那个版本进行解决？谢谢
