### ISSUE TITLE
java.lang.IncompatibleClassChangeError fasejson 1.2.71

### ISSUE THREAD

**Issue by Lee-Wang-Jing** [alibaba/fastjson#3295]
fasejson v1.2.71
`
java.lang.IncompatibleClassChangeError: Couldn't find l.e.bv
        at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
        at libcore.reflect.AnnotationAccess.annotationSetToAnnotations(AnnotationAccess.java:633)
        at libcore.reflect.AnnotationAccess.getDeclaredAnnotations(AnnotationAccess.java:161)
        at libcore.reflect.AnnotationAccess.getAnnotations(AnnotationAccess.java:111)
        at java.lang.Class.getAnnotations(Class.java:354)
        at com.alibaba.fastjson.util.TypeUtils.getAnnotation(TbsSdkJava:9)
        at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(TbsSdkJava:18)
        at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(TbsSdkJava:7)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(TbsSdkJava:227)
        at com.alibaba.fastjson.JSON.parseObject(TbsSdkJava:29)
        at com.alibaba.fastjson.JSON.parseObject(TbsSdkJava:19)
        at com.alibaba.fastjson.JSON.parseObject(TbsSdkJava:10)
        at com.qianfan.forum.base.retrofit.converter.FastJsonResponseBodyConvert.convert(TbsSdkJava:2)
        at com.qianfan.forum.base.retrofit.converter.FastJsonResponseBodyConvert.convert(TbsSdkJava:1)
        at retrofit2.OkHttpCall.parseResponse(TbsSdkJava:7)
        at retrofit2.OkHttpCall$1.onResponse(TbsSdkJava:1)
        at okhttp3.RealCall$AsyncCall.execute(TbsSdkJava:3)
        at okhttp3.internal.NamedRunnable.run(TbsSdkJava:3)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
`

**Comment by wenshao** [comment]
看不懂这个堆栈。。。
