### ISSUE TITLE
无法反序列化带Class数组字段的对象

### ISSUE THREAD

**Issue by vssq** [alibaba/fastjson#336]
实现远程过程调用时，无法正确的反序列化Spring的RemoteInvocation对象，fastjson版本是1.2.5，JDK1.7，错误信息：

Exception in thread "main" com.alibaba.fastjson.JSONException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:555)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:250)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:226)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:185)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:303)
	at cc.xstyle.framework.data.Jsons.main(Jsons.java:49)
Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
	at com.alibaba.fastjson.parser.deserializer.ArrayDeserializer.deserialze(ArrayDeserializer.java:62)
	at Fastjson_ASM_RemoteInvocation_1.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)
	... 5 more

测试样例参考代码：
```java
RemoteInvocation remoteInvocation = new RemoteInvocation();
remoteInvocation.setMethodName("test");
remoteInvocation.setParameterTypes(new Class[] { int.class, Date.class,
		String.class });
remoteInvocation.setArguments(new Object[] { 1, new Date(),
		"this is a test" });
String json = JSON.toJSONString(remoteInvocation);
remoteInvocation = JSON.parseObject(json, RemoteInvocation.class);
System.out.println(remoteInvocation);
```

**Comment by vssq** [comment]
加SerializerFeature.WriteClassName也没用

**Comment by vssq** [comment]
项目是无人维护了么，这么多BUG，既不回复，也不更新

**Comment by wenshao** [comment]
很抱歉，没有及时回复问题已经修复，请等待1.2.9版本
