### ISSUE TITLE
OOM : OutOfMemoryError

### ISSUE THREAD

**Issue by KimHu01** [alibaba/fastjson#3400]
烦请查看一下：
version:1.2.70

Caused by: java.lang.OutOfMemoryError: Java heap space 
	at com.alibaba.fastjson.serializer.SerializeWriter.expandCapacity(SerializeWriter.java:308) 
	at com.alibaba.fastjson.serializer.SerializeWriter.write(SerializeWriter.java:249) 
	at com.alibaba.fastjson.serializer.ASMSerializer_11_KafkaOpsMsg.write(Unknown Source) 
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:285) 
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:758) 
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:696) 
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:661) 

![image](https://user-images.githubusercontent.com/18360996/90228094-39fb3f00-de48-11ea-8e9c-8cfb1b786010.png)

**Comment by ZivYan** [comment]
你这个日志体现出来的是当前这个 newValue 申请内存申请不了了，不是这里出了问题，建议分析 dump

**Comment by KimHu01** [comment]
好的，谢谢，不好意思~~
