### ISSUE TITLE
使用 SnakeCase 的 ParserConfig  时，无法反序列化含有非空 Map 字段的 Kotlin data class 

### ISSUE THREAD

**Issue by fanck0605** [alibaba/fastjson#3407]
设置 mutableMap 为可空类型，或者不使用下划线转驼峰功能可以暂时缓解

代码如下：
```kotlin
fun main(args: Array<String>) {
    val parserConfig = ParserConfig()
    parserConfig.propertyNamingStrategy = PropertyNamingStrategy.SnakeCase

    JSON.parseObject<Data>("""{ "mutable_map": { "key": "value" } }""", Data::class.java, parserConfig)
}

data class Data(
    var mutableMap: MutableMap<String, String>
)
```
异常信息：
```
Exception in thread "main" com.alibaba.fastjson.JSONException: create instance error, [Ljava.lang.String;@5ae50ce6, public Data(java.util.Map<java.lang.String, java.lang.String>)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:1042)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:300)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:692)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:395)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:358)
	at TestKt.main(Test.kt:9)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:1038)
	... 5 more
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method Data.<init>, parameter mutableMap
	at Data.<init>(Test.kt)
	... 10 more
```

**Comment by fanck0605** [comment]
java 测试代码如下
```java
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.PropertyNamingStrategy;
import com.alibaba.fastjson.parser.ParserConfig;
import kotlin.Metadata;
import kotlin.jvm.internal.Intrinsics;

import java.util.Map;

public class Test {

    public static void main(String[] args) {
        ParserConfig parserConfig = new ParserConfig();
        parserConfig.propertyNamingStrategy = PropertyNamingStrategy.SnakeCase;

        Data data = JSON.parseObject("{ \"mutable_map\": { \"key\": \"value\" } }", Data.class, parserConfig);
    }

    @Metadata() // 使 fastjson 认为该类是 kotlin
    public static final class Data {
        private Map<String, String> mutableMap;

        public Data(Map<String, String> mutableMap) {
            Intrinsics.checkNotNullParameter(mutableMap, "mutableMap");
            this.mutableMap = mutableMap;
        }
    }
}
```
