### ISSUE TITLE
[bug] JSONPath.extract(str, "$.result[0,2].puid")解析异常

### ISSUE THREAD

**Issue by MaxSherry** [alibaba/fastjson#3493]
{
    "result": [
        {
            "puid": "21025318"
        },
        {
            "puid": "21482682"
        },
        {
            "puid": "21025345"
        }
    ],
    "state": 0
}

JSONPath.extract(str, "$.result[0,2].puid")报异常  
java.lang.UnsupportedOperationException
	at com.alibaba.fastjson.JSONPath$MultiIndexSegment.extract(JSONPath.java:2694)
	at com.alibaba.fastjson.JSONPath.extract(JSONPath.java:179)
	at com.alibaba.fastjson.JSONPath.extract(JSONPath.java:698)
	at com.alibaba.fastjson.JSONPath.extract(JSONPath.java:704)

使用JSONPath.eval(jsonObject, "$.result[0,2].puid") 正常

**Comment by zhangshun2** [comment]
报的错是不支持这个操作啊.没实现的不算是bug把
