### ISSUE TITLE
IntegerCodec报错ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by hellobabygogo** [alibaba/fastjson#3494]
版本：1.2.58
报错：
java.lang.ArrayIndexOutOfBoundsException: -19922328
        at com.alibaba.fastjson.util.IOUtils.getChars(IOUtils.java:288)
        at com.alibaba.fastjson.serializer.SerializeWriter.writeInt(SerializeWriter.java:536)
        at com.alibaba.fastjson.serializer.IntegerCodec.write(IntegerCodec.java:51)

**Comment by harkue** [comment]
> 版本：1.2.58
> 报错：
> java.lang.ArrayIndexOutOfBoundsException: -19922328
> at com.alibaba.fastjson.util.IOUtils.getChars(IOUtils.java:288)
> at com.alibaba.fastjson.serializer.SerializeWriter.writeInt(SerializeWriter.java:536)
> at com.alibaba.fastjson.serializer.IntegerCodec.write(IntegerCodec.java:51)

你应该提供下你的测试数据或者测试代码？不然别人怎么复现呢？
