### ISSUE TITLE
JavaBean中存在MultipartFile属性时，调用JSONObject.toJSONString(javaBean)导致异常

### ISSUE THREAD

**Issue by IAMchengge** [alibaba/fastjson#3505]
## JavaBean
```java
@Data
public class User {
    private int id;
    private MultipartFile file;
}
```

## 调用
JSONObject.toJSONString(user)

## 异常
```java
Exception in thread "main" com.alibaba.fastjson.JSONException: write javaBean error, fastjson version 1.2.73, class com.charon.springlearn.entity.MyFile, fieldName : file, write javaBean error, fastjson version 1.2.73, class org.springframework.web.multipart.MultipartFileResource, fieldName : resource
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:539)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:149)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:360)
	at com.alibaba.fastjson.serializer.ASMSerializer_1_User.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:312)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:769)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:707)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:672)
	at com.charon.springlearn.SpringLearnApplicationTests.main(SpringLearnApplicationTests.java:26)
Caused by: com.alibaba.fastjson.JSONException: write javaBean error, fastjson version 1.2.73, class org.springframework.web.multipart.MultipartFileResource, fieldName : resource
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:539)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:149)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:320)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:470)
	... 8 more
Caused by: java.io.FileNotFoundException: MultipartFile resource [null] cannot be resolved to absolute file path
	at org.springframework.core.io.AbstractResource.getFile(AbstractResource.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alibaba.fastjson.util.FieldInfo.get(FieldInfo.java:564)
	at com.alibaba.fastjson.serializer.FieldSerializer.getPropertyValueDirect(FieldSerializer.java:145)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:282)
	... 11 more
```

**Comment by IAMchengge** [comment]
## debug了代码，发现了原因
1. fastjson在打印JSON字符串时，会通过反射得到一个object的所有getter方法，然后取其值，最后拼装成一个JSON字符串。

2. MultipartFile对象有一个 Resource getResource() 方法

```
default Resource getResource() {
    return new MultipartFileResource(this);
}
```

3. fastjson在得到Resource后，会继续对Resource对象进行遍历

4. Resource是一个接口，其中有个 getFile 方法

```
File getFile() throws IOException;
```

4. MultipartFileResource本身并没有对 getFile 进行重写

5. 查看父类中的 getFile 方法
```
public File getFile() throws IOException {
    throw new FileNotFoundException(this.getDescription() + " cannot be resolved to absolute file path");
}
```

6. 解惑！

**Comment by Guanyong-Liang** [comment]
所以楼主是怎么解决的

**Comment by EricFengFuuuu** [comment]
解决了嘛?

**Comment by LSL1618** [comment]
不建议对MultipartFile对象进行序列化/反序列化操作，加注解把它排除掉

**Comment by Liudiey** [comment]
我们这需要将MultipartFile文件通过dubbo传输，必须要将MultipartFile序列化，不然通不过dubbo协议，有什么好思路嘛，本来使用JSON.toJSONString()，但是会爆同上的错误

**Comment by LSL1618** [comment]
> 我们这需要将MultipartFile文件通过dubbo传输，必须要将MultipartFile序列化，不然通不过dubbo协议，有什么好思路嘛，本来使用JSON.toJSONString()，但是会爆同上的错误

User类中能否试试定义MultipartFile的实现类属性CommonsMultipartFile或者StandardMultipartFile

或者试试能否排除掉MultipartFile中的某个get方法，它没有属性好像没办法排除。
