### ISSUE TITLE
特殊字符<br/>导致     at com.alibaba.fastjson.JSON.toJSONString(JSON.java:402)失败

### ISSUE THREAD

**Issue by wangliangliang** [alibaba/fastjson#354]
write javaBean error
com.alibaba.fastjson.JSONException: write javaBean error
         at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:212)
         at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:369)
         at com.alibaba.fastjson.JSON.toJSONString(JSON.java:414)
         at com.alibaba.fastjson.JSON.toJSONString(JSON.java:402)
Caused by: java.lang.ArrayIndexOutOfBoundsException
升级到最近1.2.5问题依旧。

问题描述
对象A，包含Map<String,String>..
当调用JSON.toJSONString(A)，出现如上错误。maven1.2.6暂时无法引用，用1.2.5测试。

**Comment by wenshao** [comment]
能否提供重现问题的testcase代码？

**Comment by wangliangliang** [comment]
能给我留个邮箱吗？我把测试的源码发你。谢谢

**Comment by wangliangliang** [comment]
已发你gmail邮箱

**Comment by wenshao** [comment]
bug fixed.
