### ISSUE TITLE
Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2str

### ISSUE THREAD

**Issue by wuguanyu** [alibaba/fastjson#3542]
public static void main(String[] args) {
        ParserConfig.getGlobalInstance().setAutoTypeSupport(true);
        JSONObject jsonObject = JSONObject.parseObject(
                "{\n" +
                "       \"received\":1605254288.828,\n" +
                "        \"_meta\":{\n" +
                "            \"autoCommit\":{\n" +
                "                \"\":{\n" +
                "                    \"err\":[\n" +
                "                        \"invalid_attribute\"\n" +
                "                    ]\n" +
                "                }\n" +
                "            },\n" +
                "            \"dataSourceName\":{\n" +
                "                \"\":{\n" +
                "                    \"err\":[\n" +
                "                        \"invalid_attribute\"\n" +
                "                    ]\n" +
                "                }\n" +
                "            },\n" +
                "            \"@type\":{\n" +
                "                \"\":{\n" +
                "                    \"err\":[\n" +
                "                        \"invalid_attribute\"\n" +
                "                    ]\n" +
                "                }\n" +
                "            }\n" +
                "        },\n" +
                "        \"level\":\"error\",\n" +
                "        \"project\":154,\n" +
                "        \"key_id\":\"154\",\n" +
                "        \"@type\":null\n" +
                "  \n" +
                "}");
        System.out.println(jsonObject);

**Comment by wuguanyu** [comment]
不识别 字段中还有@符号

**Comment by wuguanyu** [comment]
![Uploading image.png…]()

**Comment by wuguanyu** [comment]
1.2.60.sec10

**Comment by wuguanyu** [comment]
Exception in thread "main" com.alibaba.fastjson.JSONException: expect ':' at 406, name :{
                    
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:232)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:577)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1417)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1383)
	at com.alibaba.fastjson.JSON.parse(JSON.java:182)
	at com.alibaba.fastjson.JSON.parse(JSON.java:192)
	at com.alibaba.fastjson.JSON.parse(JSON.java:148)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:253)
	at com.shuidihuzhu.devops.alarm.biz.alarm.SentryMsgBiz.main(SentryMsgBiz.java:398)

**Comment by Certseeds** [comment]
1.2.77_preview_01
``` java
package com.alibaba.json.bvt.issue_3500;

import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.parser.ParserConfig;
import org.junit.Test;

public class Issue3542 {
    private static final String test_str_1 = "{\n" +
            "   \"level\":\"error\",\n" +
            "   \"key_id\":\"154\",\n" +
            "   \"_meta\":{\n" +
            "      \"autoCommit\":{\n" +
            "         \"\":{\n" +
            "            \"err\":[\n" +
            "               \"invalid_attribute\"\n" +
            "            ]\n" +
            "         }\n" +
            "      },\n" +
            "      \"dataSourceName\":{\n" +
            "         \"\":{\n" +
            "            \"err\":[\n" +
            "               \"invalid_attribute\"\n" +
            "            ]\n" +
            "         }\n" +
            "      },\n" +
            "      \" @type \":{\n" +
            "         \"\":{\n" +
            "            \"err\":[\n" +
            "               \"invalid_attribute\"\n" +
            "            ]\n" +
            "         }\n" +
            "      }\n" +
            "   },\n" +
            "   \"project\":154,\n" +
            "   \"received\":1605254288.828\n" +
            "}";

    @Test
    public void test_for_issue1() {
        ParserConfig.getGlobalInstance().setAutoTypeSupport(true);
        JSONObject jsonObject = JSONObject.parseObject(test_str_1);
        System.out.println(jsonObject);
    }
    @Test
    public void test_for_issue2() {
        JSONObject jsonObject = JSONObject.parseObject(test_str_1);
        System.out.println(jsonObject);
    }
}
```
没有异常输出.
