### ISSUE TITLE
com.alibaba.fastjson.JSONException: can not cast to Date, value : -568108800000

### ISSUE THREAD

**Issue by zhai02** [alibaba/fastjson#3595]
无法反序列化1970年以前的日期， -568108800000 为1952年1月1日，反序列化就失败了

com.alibaba.fastjson.JSONException: can not cast to Date, value : -568108800000
        at com.alibaba.fastjson.util.TypeUtils.castToJavaBean(TypeUtils.java:1035)
        at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:685)
        at com.alibaba.fastjson.JSON.toJavaObject(JSON.java:928)

**Comment by wenshao** [comment]
我测试过1.2.75版本是好的，请升级最新版本
