### ISSUE TITLE
@JSONField 枚举序列化 栈溢出

### ISSUE THREAD

**Issue by linxinqiang90** [alibaba/fastjson#3601]
版本:1.2.72,1.2.73,1.2.75
枚举中只有一个值，并且被@JSONField，序列化时溢出
枚举2个值以上，序列化正常。

```java
@Data
public class TestEntity {
    private TestEnum testEnum;
    private String testName;
}
```

```java
public enum TestEnum {
    @JSONField(name = "xx")
    test1("1");
//    @JSONField(name = "xx2")
//    test2("2");
    private String title;

    private TestEnum(String title) {
        this.title = title;
    }

}
```

```java
   public static void main(String[] args) {
        TestEntity testEntity = new TestEntity();
        testEntity.setTestName("xxxx");
        testEntity.setTestEnum(TestEnum.test1);
        System.out.println(JSON.toJSONString(testEntity));
    }
```
```
Exception in thread "main" java.lang.StackOverflowError
	at com.alibaba.fastjson.JSON.getMixInAnnotations(JSON.java:1384)
	at com.alibaba.fastjson.serializer.SerializeConfig.get(SerializeConfig.java:878)
	at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:444)
	at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:440)
	at com.alibaba.fastjson.serializer.JSONSerializer.getObjectWriter(JSONSerializer.java:448)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:309)
	at com.alibaba.fastjson.serializer.EnumSerializer.write(EnumSerializer.java:58)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:312)
	at com.alibaba.fastjson.serializer.EnumSerializer.write(EnumSerializer.java:58)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:312)
```

**Comment by github-ganyu** [comment]
I fixed the bug and it has been merged into the master:
https://github.com/alibaba/fastjson/pull/3606/commits/2fa8ee07e55b476f778a63633f556bbf6b023ab7
