### ISSUE TITLE
循环引用反序列化报错

### ISSUE THREAD

**Issue by fuqile** [alibaba/fastjson#3624]
Java代码如下，业务上需要使用到循环引用，所以不配置DisableCircularReferenceDetect。
使用JSONObject序列化是ok的，但是使用对象序列化就报错了。

`public class TestFastJsonReference {

    public static void main(String[] args) {
        // 序列化
        Person person = new Person();
        person.setName("Jack");
        PersonManage personManage = new PersonManage();
        Map<String,Map<String,Person>> cityNameMap = new HashMap<String, Map<String, Person>>();
        Map<String,Person> nameMap = new HashMap<String, Person>();
        nameMap.put("Jack",person);
        cityNameMap.put("Hangzhou",nameMap);
        personManage.setNameMap(nameMap);
        personManage.setCityNameMap(cityNameMap);
        String personManageString = JSON.toJSONString(personManage);
        System.out.println(personManageString);

        // JSONObject 反序列化
        JSONObject jsonObject = JSON.parseObject(personManageString);
        System.out.println(jsonObject.getJSONObject("nameMap").getString("Jack"));

        // 对象反序列化
        System.out.println(JSON.parseObject(personManageString, PersonManage.class));

    }

    @Data
    static class Person {
        private String name;
    }

    @Data
    static class PersonManage {
        private Map<String,Person> nameMap;
        private Map<String, Map<String,Person>> cityNameMap;
    }

}`

输出：

`{"cityNameMap":{"Hangzhou":{"Jack":{"name":"Jack"}}},"nameMap":{"$ref":"$.cityNameMap.Hangzhou"}}
{"name":"Jack"}
Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error,except start with { or [,but actually start with string
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:678)
	at com.alibaba.fastjson.parser.deserializer.MapDeserializer.parseMap(MapDeserializer.java:198)
	at com.alibaba.fastjson.parser.deserializer.MapDeserializer.deserialze(MapDeserializer.java:65)
	at com.alibaba.fastjson.parser.deserializer.MapDeserializer.deserialze(MapDeserializer.java:43)
	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:85)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:822)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:288)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:680)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:383)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:287)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:560)
	at TestFastJsonReference.main(TestFastJsonReference.java:33)

Process finished with exit code 1`

**Comment by Ryyyc** [comment]
使用JSONObject序列化的时候结果就不对呀，正确的结果是
{"cityNameMap":{"Hangzhou":{"Jack":{"name":"Jack"}}},"nameMap":{"Jack":{"name":"Jack"}}}

因为你的 Person 引用了同一个对象，Jack。

可以通过 关闭引用检测 来解决这个对象重复引用的问题：
   JSON.toJSONString 方法输入第二个参数  SerializerFeature.DisableCircularReferenceDetect

也就是
String personManageString = JSON.toJSONString(personManage);
这一行改成
String personManageString = JSON.toJSONString(personManage,SerializerFeature.DisableCircularReferenceDetect);
