### ISSUE TITLE
String index out of range: 3问题

### ISSUE THREAD

**Issue by lliioollcn** [alibaba/fastjson#3628]
读取这样的json会引发以下问题:
`{"admin":3483706632,"admins":[],"black":{"blackList":[]},"enable":true,"messages":{"adminChangeDown":"[mirai:at:%target%] 被撤销了管理~","adminChangeUp":"恭喜 [mirai:at:%target%] 被升为管理员~","blacelist":"[mirai:at:%target%]你被加入此群黑名单,不允许你进入本群","clearnScreen":"清屏ing~~~\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n清屏完毕~~~","join":"欢迎 [mirai:at:%target%] 进入本群~","kick":"[mirai:at:%target%] 被 [mirai:at:%operator%] 踢出本群","leave":"很遗憾, [mirai:at:%target%] 离开了本群","mute":"[mirai:at:%target%] 被 [mirai:at:%operator%] 禁言 %time%","talkative":"恭喜 [mirai:at:%target%] 成为本群龙王!","title":"恭喜 [mirai:at:%target%] 获得群主授予的 %title% 头衔!","unmute":"[mirai:at:%target%] 被 [mirai:at:%operator%] 解除禁言","warn":""},"requestConfig":{"keyWordRegex":"SINGLE","keyWords":["栗子"],"type":"PASS"},"select":{"adminChange":true,"autoParseRequest":true,"join":true,"kick":true,"leave":true,"mute":true,"talkative":true,"title":true,"unmute":true},"warn":{"count":10,"countBlack":30,"warnList":[{"count":-9999,"id":123456}]}}`

`Caused by: com.alibaba.fastjson.JSONException: String index out of range: 3
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:705)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:395)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:299)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:572)
	at cn.lliiooll.lbots.config.ConfigBridge.getConfig(ConfigBridge.java:51)
	at cn.lliiooll.lbots.listeners.MessageListener.group(MessageListener.java:18)
	... 12 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 3
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at com.alibaba.fastjson.util.JavaBeanInfo.build(JavaBeanInfo.java:767)
	at com.alibaba.fastjson.parser.ParserConfig.createJavaBeanDeserializer(ParserConfig.java:1002)
	at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:888)
	at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:593)
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_1_GroupConfig.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:296)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:700)
	... 17 more`
`GroupConfig ob = JSON.parseObject(FileUtils.readFileToString(file, StandardCharsets.UTF_8),GroupConfig.class);`

版本1.2.75

**Comment by Ryyyc** [comment]
能否把相关的 class 贴一下？
