### ISSUE TITLE
无法反序列化带Class数组字段的对象

### ISSUE THREAD

**Issue by ghost** [alibaba/fastjson#363]
实现远程过程调用时，无法正确的反序列化Spring的RemoteInvocation对象，fastjson版本是1.2.5，JDK1.7，错误信息：

Exception in thread "main" com.alibaba.fastjson.JSONException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
    at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:555)
    at com.alibaba.fastjson.JSON.parseObject(JSON.java:250)
    at com.alibaba.fastjson.JSON.parseObject(JSON.java:226)
    at com.alibaba.fastjson.JSON.parseObject(JSON.java:185)
    at com.alibaba.fastjson.JSON.parseObject(JSON.java:303)
    at cc.xstyle.framework.data.Jsons.main(Jsons.java:49)
Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
    at com.alibaba.fastjson.parser.deserializer.ArrayDeserializer.deserialze(ArrayDeserializer.java:62)
    at Fastjson_ASM_RemoteInvocation_1.deserialze(Unknown Source)
    at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)
    ... 5 more

测试样例参考代码：

``` java
RemoteInvocation remoteInvocation = new RemoteInvocation();
remoteInvocation.setMethodName("test");
remoteInvocation.setParameterTypes(new Class[] { int.class, Date.class,
        String.class });
remoteInvocation.setArguments(new Object[] { 1, new Date(),
        "this is a test" });
String json = JSON.toJSONString(remoteInvocation);
remoteInvocation = JSON.parseObject(json, RemoteInvocation.class);
System.out.println(remoteInvocation);
```

**Comment by LQZYC** [comment]
我是在java1.8的环境下运行的 没有发现这个问题啊  打印出来的是RemoteInvocation: method name 'test'; parameter types [int, java.util.Date, java.lang.String]

**Comment by vssq** [comment]
什么版本的fastjson？

**Comment by vssq** [comment]
最新的1.2.6依然不行啊

**Comment by LQZYC** [comment]
我就是最新的 我的测试代码就是copy你的

**Comment by LQZYC** [comment]
你注意换jdk1.8  我是1.8的jdk

**Comment by vssq** [comment]
就是1.8啊

**Comment by LQZYC** [comment]
额这个我就很难解决了 因为我这边运行了几次 结果都是这样的 没有出错误 我稍后在别人的机器上跑一跑看会不会出错误吧

**Comment by vssq** [comment]
我的是Mac OS操作系统

**Comment by LQZYC** [comment]
我也是mac  java运行在虚拟机上面 跟mac 或者windows应该没有什么影响吧

**Comment by wenshao** [comment]
测试过，问题已经解决，请等待1.2.9版本吧

**Comment by fulus06** [comment]
**v1.2.33**  还是有这个错误但是使用v**1.2.17**就没问题，其他版本没试

**Comment by wenshao** [comment]
我测试了有没问题哈？

**Comment by wenshao** [comment]
我先关闭啦，如果有问题再提新的issue
