### ISSUE TITLE
反序列化java.sql.Time有bug

### ISSUE THREAD

**Issue by StephenShang** [alibaba/fastjson#3637]
出现如下错误：
com.alibaba.fastjson.JSONException: can not cast to Timestamp, value : 01:00:00
	at com.alibaba.fastjson.util.TypeUtils.castToSqlTime(TypeUtils.java:617)
	at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:1126)
	at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:1251)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.createInstance(JavaBeanDeserializer.java:1439)

1.2.68
我看JSONScanner没有针对这样的字符串做处理，还是会强制判断yyyyMMdd。

**Comment by lethal233** [comment]
请问有人正在处理这个问题吗，我对这个issue感兴趣，我将在最近的几个月内尝试处理这个bug。
