### ISSUE TITLE
父类中get方法返回值是Object，子类重写后返回String，有时会导致WriteNullStringAsEmpty功能不生效

### ISSUE THREAD

**Issue by yingjianhua** [alibaba/fastjson#3655]
![image](https://user-images.githubusercontent.com/20136079/108935668-15024700-7689-11eb-9d48-e3f6f8a16c75.png)
在TypeUtils的computeGetters方法中
![image](https://user-images.githubusercontent.com/20136079/108937542-a5408c00-7689-11eb-8b7c-44eabe830642.png)
这里的clazz.getMethods()，不能保证子类的get方法在父类的get方法之后，就可能导致父类的get方法覆盖子类的get方法，使字段信息中获取到的字段类型为Object，导致WriteNullStringAsEmpty不能生效。

**Comment by Certseeds** [comment]
```
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.serializer.SerializerFeature;
import org.junit.Test;

public class Issue3655 {
    @Test
    public void test1() {
        B b = new B(null);
        System.out.println(JSON.toJSONString(b, SerializerFeature.WriteNullListAsEmpty));
    }

    public static abstract class A {
        public abstract Object getData();
    }

    public static class B extends A {
        private String data;

        public B(String data) {
            this.data = data;
        }

        public String getData() {
            return this.data;
        }

        public void setData(String data) {
            this.data = data;
        }
    }
}
```
1.2.75 存在此问题

**Comment by Certseeds** [comment]
@hotaru555 , i guess you have time to solve this issue.

**Comment by hotaru555** [comment]
> @hotaru555 , i guess you have time to solve this issue.

Yes, I'd like to work on this issue.

**Comment by wenshao** [comment]
使用 SerializerFeature.WriteNullStringAsEmpty

**Comment by yingjianhua** [comment]
> 使用 SerializerFeature.WriteNullStringAsEmpty

这个问题关闭掉，意思是不解决吗？

**Comment by yingjianhua** [comment]
@wenshao 这个问题关闭掉，是不解决吗？

**Comment by Certseeds** [comment]
我之前发的TestCase确实是错误的，写成`WriteNullListsAsEmpty`了.
但是问题确实是存在的

``` java
package com.alibaba.json.bvt.issue_3600;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONException;
import com.alibaba.fastjson.serializer.SerializerFeature;
import junit.framework.TestCase;
import org.junit.Assert;

public class Issue3655 extends TestCase {

    public void test1() {
        B b = new B(null);
        String left = "";
        left = JSON.toJSONString(b, SerializerFeature.WriteNullStringAsEmpty);
        Assert.assertEquals(left, "{}");
    }

    public void test2() {
        B b = new B(null);
        String left = "";
        try {
            left = JSON.toJSONString(b, SerializerFeature.WriteNullStringAsEmpty);
            Assert.assertNotEquals(left, "{}");
        } catch (java.lang.AssertionError assertionError) {
            System.out.println(left);
            throw new JSONException("Not Equal!");
        }
    }

    public static class B extends A {
        private final String data;

        public B(String data) {
            this.data = data;
        }

        public String getData() {
            return this.data;
        }
    }
    public static abstract class A {
        public abstract Object getData();
    }
}
```
testcase 1pass
testcase 2输出

``` log
{}
com.alibaba.fastjson.JSONException: Not Equal!

	at com.alibaba.json.bvt.issue_3600.Issue3655.test2(Issue3655.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	...etc
```

**Comment by Certseeds** [comment]
我之前发的TestCase确实是错误的，写成`WriteNullListsAsEmpty`了.
但是问题确实是存在的

``` java
package com.alibaba.json.bvt.issue_3600;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.serializer.SerializerFeature;
import junit.framework.TestCase;
import lombok.AllArgsConstructor;
import org.junit.Assert;

import java.util.Random;

public class Issue3655 extends TestCase {

    public void test1() {
        B b = new B(null, null, null, null, null);
        String left = JSON.toJSONString(b, SerializerFeature.WriteNullStringAsEmpty);
        System.out.println(left);
        Assert.assertEquals("{\"data\":\"\",\"data2\":\"\",\"data3\":\"\",\"data4\":\"\",\"data5\":\"\"}", left);

    }

    public static class B extends A {
        private String data;
        private String data2;
        private String data3;
        private String data4;
        private String data5;

        public String getData() {
            return data;
        }

        public String getData2() {
            return data;
        }

        public String getData3() {
            return data;
        }

        public String getData4() {
            return data;
        }

        public String getData5() {
            return data;
        }

        public void setData(String data) {
            this.data = data;
        }

        public void setData2(String data2) {
            this.data2 = data2;
        }

        public void setData3(String data3) {
            this.data3 = data3;
        }

        public void setData4(String data4) {
            this.data4 = data4;
        }

        public void setData5(String data5) {
            this.data5 = data5;
        }
        public B(String data, String data2, String data3, String data4, String data5) {
            this.data = data;
            this.data2 = data2;
            this.data3 = data3;
            this.data4 = data4;
            this.data5 = data5;
        }
    }

    public static abstract class A {
        public abstract Object getData();

        public abstract Object getData2();

        public abstract Object getData3();

        public abstract Object getData4();

        public abstract Object getData5();
    }

}
```
重复几次testcase可以发现，基本上每次的输出都不同，并且testcase大概率不通过.

比如输出：

``` log
org.junit.ComparisonFailure: 
预期:{"data":"","data2":"","data3":"","data4":"","data5":""}
实际:{"data":"","data3":"","data4":"","data5":""}
```

问题就出在那个`clazz.getMethods()`,getMethods()不保证顺序-
在一般实现里就是地址顺序.
因为`Object`自带10+方法，所以只有一个字段的对象，带上字段的getter,setter也就十几个方法，子类的get方法在父类的get方法之后概率还挺高，一旦字段多起来概率就下去了.

**Comment by Certseeds** [comment]
@wenshao

**Comment by wmxl** [comment]
我也发现了， 集成的子类  某个字段是null， 但是依然输出的是‘null' 而不是’‘
