### ISSUE TITLE
java.lang.StackOverflowError: null

### ISSUE THREAD

**Issue by dlinka** [alibaba/fastjson#3687]
序列化如下类结构:
![image](https://user-images.githubusercontent.com/4274041/112122120-ea110180-8bfa-11eb-9af6-187afd17e98d.png)

**ERROR**

        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:28) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]
        at com.alibaba.fastjson.serializer.SerialContext.toString(SerialContext.java:31) ~[fastjson-1.2.75.jar!/:na]

**Comment by dlinka** [comment]
已定位
