### ISSUE TITLE
(JSONObject) JSON.parse(param) 偶发性 出现 java.lang.NullPointerException

### ISSUE THREAD

**Issue by GdHuni** [alibaba/fastjson#3736]
同一个正常的json格式字符串 在进行 (JSONObject) JSON.parse(param) 偶发性 出现 java.lang.NullPointerException（xxl 定时任务执行的，大概有个是执行了几十次 出现了一次，参数没有变化过）

java.lang.NullPointerException
        at com.alibaba.fastjson.parser.SymbolTable.addSymbol(SymbolTable.java:144)
        at com.alibaba.fastjson.parser.JSONScanner.addSymbol(JSONScanner.java:154)
        at com.alibaba.fastjson.parser.JSONLexerBase.scanSymbol(JSONLexerBase.java:797)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:214)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:425)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1184)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1153)
        at com.alibaba.fastjson.JSON.parse(JSON.java:102)
        at com.alibaba.fastjson.JSON.parse(JSON.java:93)
        at com.leyoujia.job.handler.AnalysisJobHandler.execute(AnalysisJobHandler.java:76)
        at com.leyoujia.job.core.thread.JobThread.run(JobThread.java:152)

**Comment by GdHuni** [comment]
版本1.1.35
