### ISSUE TITLE
JSON.parseObject   com.alibaba.fastjson.JSONException: 1

### ISSUE THREAD

**Issue by 721806280** [alibaba/fastjson#3774]
```
public class Demo {
    public static void main(String[] args) throws JsonProcessingException {
        // 构建node列表   TreeNode来自hutool
        List<TreeNode<String>> nodeList = CollUtil.newArrayList();

        nodeList.add(new TreeNode<>("1", "0", "系统管理", 5));
        nodeList.add(new TreeNode<>("11", "1", "用户管理", 222222));
        nodeList.add(new TreeNode<>("111", "11", "用户添加", 0));
        nodeList.add(new TreeNode<>("2", "0", "店铺管理", 1));
        nodeList.add(new TreeNode<>("21", "2", "商品管理", 44));
        nodeList.add(new TreeNode<>("221", "2", "商品管理2", 2));

        // 0表示最顶层的id是0
        List<Tree<String>> treeList = TreeUtil.build(nodeList, "0");


        String json = JSON.toJSONString(treeList);

        // hutool的JSONUtil没问题
        List<Tree<String>> trees = JSONUtil.toBean(json, new TypeReference<List<Tree<String>>>() {
        }, true);

        // jackson 没问题
        ObjectMapper objectMapper = new ObjectMapper();
        List<Tree<String>> trees2 = objectMapper.readValue(json, new com.fasterxml.jackson.core.type.TypeReference<List<Tree<String>>>() {
        });

        // fastJson 报错 com.alibaba.fastjson.JSONException: 1
        List<Tree<String>> trees3 = JSON.parseObject(json, new com.alibaba.fastjson.TypeReference<List<Tree<String>>>(){});
    }
}

错误信息如下：

Exception in thread "main" com.alibaba.fastjson.JSONException: 1
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:713)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:394)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:362)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:276)
	at com.healthy.Demo.main(Demo.java:42)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.alibaba.fastjson.parser.deserializer.MapDeserializer.deserialze(MapDeserializer.java:66)
	at com.alibaba.fastjson.parser.deserializer.MapDeserializer.deserialze(MapDeserializer.java:43)
	at com.alibaba.fastjson.parser.deserializer.ContextObjectDeserializer.deserialze(ContextObjectDeserializer.java:9)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:795)
	at com.alibaba.fastjson.serializer.CollectionCodec.deserialze(CollectionCodec.java:126)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:708)
	... 4 more
```

**Comment by vipcxj** [comment]
我觉得你至少得把序列化的结果给出来吧~ 毕竟你不能指望别人特意去搞个hutool

**Comment by RLin2015New** [comment]
“ // fastJson 报错 com.alibaba.fastjson.JSONException: 1
    List<Tree<String>> trees1 = JSON.parseObject(json, new com.alibaba.fastjson.TypeReference<List<Tree<String>>>(){});”
    这里的问题，你应该用 
      List<Tree> trees2 = JSON.parseArray(json,
                Tree.class);  这种写法。因为你TreeUtil.build()出来的是hutool的Tree节点，toJSONString也是Tree的内容（它有children节点，TreeNode是parent节点）。（这里一个比较有意思的点是，Tree里面实际内容是以Map和parent的结构存储，但是通过Node接口实现了所需的几个get、set方法，所以正向和逆向也都可以正常操作）
                再者你字符串转输出应该用parseArray而不是parseObject
