### ISSUE TITLE
特定数量字段的类反序列化时,java.lang.VerifyError或EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by fognullex** [alibaba/fastjson#3793]
[#2858](2858) 似乎并未完全修复 [#2779](2779) 的bug
###
环境:
jdk 11
fastjson 1.2.73(1.2.76)
###
问题:
项目遇到反序列化一个类的时候，提示java.lang.VerifyError异常 或者 EXCEPTION_ACCESS_VIOLATION  jvm直接退出。
经过分析和测试，发现只要字段是96个的时候就会出现这个问题。(128的时候demo抽象不出来，另外字段不能是基础类型或者com.alibaba.fastjson.parser.ParserConfig已定义的类型)。
疑似生成的字节码跳转地址再次出现负数。
```
if_icmpne -17541
```
###
现象:
```
Exception in thread "main" java.lang.VerifyError: (class: com/alibaba/fastjson/parser/deserializer/FastjsonASMDeserializer_1_T96, method: deserialze signature: (Lcom/alibaba/fastjson/parser/DefaultJSONParser;Ljava/lang/reflect/Type;Ljava/lang/Object;I)Ljava/lang/Object;) Illegal target of jump or branch
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.getConstructor(Class.java:2151)
	at com.alibaba.fastjson.parser.deserializer.ASMDeserializerFactory.createJavaBeanDeserializer(ASMDeserializerFactory.java:90)
	at com.alibaba.fastjson.parser.ParserConfig.createJavaBeanDeserializer(ParserConfig.java:1082)
	at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:888)
	at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:593)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:685)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:395)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:299)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:572)
	at com.example.demo.DemoApplication.main(DemoApplication.java:8)
```
###
复现方法:
[demo.zip](https://github.com/alibaba/fastjson/files/6573292/demo.zip)
运行demo
###
生成的FastjsonASMDeserializer_1_T96.class和字节码
[FastjsonASMDeserializer_1_T96.zip](https://github.com/alibaba/fastjson/files/6573458/FastjsonASMDeserializer_1_T96.zip)

**Comment by fognullex** [comment]
if_icmpne 还是变成的负数

**Comment by fognullex** [comment]
if_icmpne     -17541

[FastjsonASMDeserializer_1_T96.zip](https://github.com/alibaba/fastjson/files/6573401/FastjsonASMDeserializer_1_T96.zip)
