### ISSUE TITLE
反序列化Set出错！！！

### ISSUE THREAD

**Issue by zwqlive** [alibaba/fastjson#383]
```java
package test.fastjson;

import java.util.HashSet;
import java.util.Set;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.serializer.SerializerFeature;

public class FastjsonTest {

    public static void main(String[] args) {
        TestClass ts = new TestClass();
        ts.getHashSet().add(1);
        ts.getHashSet().add(4);
        ts.getMember().getHashSet().add(10);
        ts.getMember().getHashSet().add(15);
        String jsonStr = JSON.toJSONString(ts, new SerializerFeature[]{
                SerializerFeature.WriteClassName, SerializerFeature.DisableCircularReferenceDetect
        });
        System.out.println(jsonStr);
        ts = JSON.parseObject(jsonStr, TestClass.class);
        for (Integer val : ts.getHashSet()) {
            System.out.println(val);
        }
    }


    public static class TestClass {

        private Set<Integer> hashSet = new HashSet<Integer>();
        private Member member = new Member();

        public TestClass() {
        }

        public Set<Integer> getHashSet() {
            return hashSet;
        }

        public void setHashSet(Set<Integer> hashSet) {
            this.hashSet = hashSet;
        }

        public Member getMember() {
            return member;
        }

        public void setMember(Member member) {
            this.member = member;
        }
    }

    public static class Member{
        private Set<Integer> hashSet = new HashSet<Integer>();

        public Member() {
        }

        public Set<Integer> getHashSet() {
            return hashSet;
        }

        public void setHashSet(Set<Integer> hashSet) {
            this.hashSet = hashSet;
        }
    }
}
```
最新版本1.2.6，之前也反馈过这个问题
输出及报错详细信息
``` java
{"@type":"test.fastjson.FastjsonTest$TestClass","hashSet":Set[1,4],"member":{"hashSet":Set[10,15]}}
Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error, expect {, actual Set, pos 58
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:232)
	at com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer.parseRest(ASMJavaBeanDeserializer.java:100)
	at Fastjson_ASM_TestClass_1.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:250)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:226)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:185)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:303)
	at test.fastjson.FastjsonTest.main(FastjsonTest.java:21)
```

如果你写的代码没这个，请拷贝我上述提供的代码
当我将类TestClass 的访问属性public去掉,即变成 static class TestClass的时候，报了另外一个错误信息
``` java
{"@type":"test.fastjson.FastjsonTest$TestClass","hashSet":Set[1,4],"member":{"hashSet":Set[10,15]}}
Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error, expect {, actual Set, pos 87, fieldName member
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:232)
	at com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer.parseRest(ASMJavaBeanDeserializer.java:100)
	at Fastjson_ASM_Member_1.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:33)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:420)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:330)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:135)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:250)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:226)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:185)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:303)
	at test.fastjson.FastjsonTest.main(FastjsonTest.java:21)
```

**Comment by qifanyang** [comment]
这个问题是生成反序列化的ASM代码有问题, 在JDK8上开启asm效率不一定会提高.

使用:ParserConfig.getGlobalInstance().setAsmEnable(false);关闭asm.

你的代码在反序列化之前设置个全局的吧,也可以设置局部的.即可解决
:ParserConfig.getGlobalInstance().setAsmEnable(false);
 ts = JSON.parseObject(jsonStr, TestClass.class);

**Comment by huashanyu** [comment]
使用:ParserConfig.getGlobalInstance().setAsmEnable(false);关闭asm.即可解决

反序列化是没有问题了，但是 json 的格式还是有问题啊

**Comment by wenshao** [comment]
bug fixed. it will include in 1.2.9.
