### ISSUE TITLE
ASMUtils.isAndroid调用java.lang.System.getProperty,多线程需要加锁,性能损失惨重!

### ISSUE THREAD

**Issue by yuankui** [alibaba/fastjson#394]
版本`1.2.4`

```
     at java.util.Hashtable.get(Hashtable.java:433)
        - waiting to lock <0x00000007600056a0> (a java.util.Properties)
        at java.util.Properties.getProperty(Properties.java:951)
        at java.lang.System.getProperty(System.java:711)
        at com.alibaba.fastjson.util.ASMUtils.isAndroid(ASMUtils.java:28)
        at com.alibaba.fastjson.parser.JSONScanner.subString(JSONScanner.java:179)
        at com.alibaba.fastjson.parser.JSONScanner.stringVal(JSONScanner.java:172)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:394)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1236)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1205)
        at com.alibaba.fastjson.JSON.parse(JSON.java:108)
        at com.alibaba.fastjson.JSON.parse(JSON.java:99)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:170)
```

**Comment by wenshao** [comment]
已合并代码
