### ISSUE TITLE
 1.2.4 版本序列化java.awt里面类出现异常

### ISSUE THREAD

**Issue by wzhonggo** [alibaba/fastjson#399]
https://github.com/alibaba/fastjson/wiki/Android%E7%89%88%E6%9C%AC   这个链接上面说Android版本的出掉了awt相关类序列化和反序列化的支持， 我不知道我使用是不是标准版的fastjson，如果不是的，请告诉我标准版的fastjson在哪里下载。

 下面是我的maven配置。
```xml
   <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.4</version>
   </dependency>
```

下面是测试出错的Java代码

```java
 Dimension d = new Dimension();
 d.setSize(1.1, 1.2);
 System.out.println(JSON.toJSONString(d));
```

出现的异常
```java
java.lang.StackOverflowError
	at com.alibaba.fastjson.serializer.JSONSerializer.containsReference(JSONSerializer.java:174)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.writeReference(JavaBeanSerializer.java:259)
	at Serializer_1.write1(Unknown Source)
	at Serializer_1.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:390)
	at Serializer_1.write1(Unknown Source)
	at Serializer_1.write(Unknown Source)
```

**Comment by qifanyang** [comment]
Dimension该类getSize方法忽略即可
```java

public class Bug_for_399 extends TestCase {

	public void test_0() {
		Dimension d = new Dimension();
		d.setSize(1.1, 1.2);
		System.out.println(JSON.toJSONString(d, new PropertyPreFilter() {
			public boolean apply(JSONSerializer serializer, Object source, String name) {
				if ("size".equals(name)) {
					return false;
				}
				return true;
			}
		}));
	}

}
```

**Comment by wzhonggo** [comment]
谢谢， 上面的测试我测试已经可以了。
