### ISSUE TITLE
json-path can not be null or empty

### ISSUE THREAD

**Issue by zhangyangx** [alibaba/fastjson#3999]
**fastjson版本：** 1.2.73
 **代码：**
`JSONObject jsonObject = JSON.parseObject(JSON.toJSONString(swagger));`
**json字符串：**
`{
  "basePath": "/",
  "host": "localhost:8080",
  "info": {
    "contact": {
      "email": "userDTO.getEmail()"
    },
    "description": "同一后端服务源API批量导出",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "termsOfService": "http://swagger.io/terms/",
    "title": "xxxxxxxx",
    "version": "1.0.0"
  },
  "paths": {
    "/v2/pet/{id}": {
      "get": {
        "description": "get请求带参数",
        "operationId": "",
        "parameters": [
          {
            "default": "",
            "description": "",
            "in": "path",
            "name": "id",
            "required": true,
            "type": "string"
          }
        ],
        "produces": "application/json",
        "responses": {
          "default": {
            "description": "{}"
          }
        },
        "summary": "get请求带参数",
        "tags": []
      }
    },
    "/v2/pet": {
      "post": {
        "description": "post请求",
        "operationId": "",
        "parameters": [
          {
            "default": "",
            "description": "",
            "in": "body",
            "name": "Body Param",
            "required": true,
            "schema": {
              "$ref": ""
            }
          }
        ],
        "produces": "application/json",
        "responses": {
          "default": {
            "description": "{}"
          }
        },
        "summary": "post请求",
        "tags": []
      }
    }
  },
  "schemes": [
    "http"
  ],
  "swagger": "2.0"
}`
**报错信息：**
`com.alibaba.fastjson.JSONPathException: json-path can not be null or empty
	at com.alibaba.fastjson.JSONPath.<init>(JSONPath.java:62)
	at com.alibaba.fastjson.JSONPath.<init>(JSONPath.java:57)
	at com.alibaba.fastjson.JSONPath.compile(JSONPath.java:666)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:444)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:571)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1232)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:520)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:571)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:571)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:571)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1407)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1373)`

**Comment by zhangyangx** [comment]
$ref对应的值为空字符串就会报错
