### ISSUE TITLE
array level > 512

### ISSUE THREAD

**Issue by wanglichao1** [alibaba/fastjson#4061]
Caused by: com.alibaba.fastjson.JSONException: array level > 512
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1171) ~[fastjson-1.2.70.jar:?]
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1394) ~[fastjson-1.2.70.jar:?]
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1367) ~[fastjson-1.2.70.jar:?]
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseExtra(DefaultJSONParser.java:1623) ~[fastjson-1.2.70.jar:?]
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:1230) ~[fastjson-1.2.70.jar:?]
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:866) ~[fastjson-1.2.70.jar:?]
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:1576) ~[fastjson-1.2.70.jar:?]
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_17_RoomBaseInfoVo.deserialze(Unknown Source) ~[?:?]
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:284) ~[fastjson-1.2.70.jar:?]
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:775) ~[fastjson-1.2.70.jar:?]
	at com.alibaba.fastjson.serializer.CollectionCodec.deserialze(CollectionCodec.java:126) ~[fastjson-1.2.70.jar:?]
	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:85) ~[fastjson-1.2.70.jar:?]
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:838) ~[fastjson-1.2.70.jar:?]
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:288) ~[fastjson-1.2.70.jar:?]
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:686) ~[fastjson-1.2.70.jar:?]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:396) ~[fastjson-1.2.70.jar:?]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:364) ~[fastjson-1.2.70.jar:?]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:327) ~[fastjson-1.2.70.jar:?]

**Comment by softcyt** [comment]
大佬解决了吗 我今天也遇到这个问题了

**Comment by Seventysevendays** [comment]
+1
