### ISSUE TITLE
com.alibaba.fastjson.JSONException: create instance error, null, public com.test.TestA(com.test.TestB)

### ISSUE THREAD

**Issue by Melo15Zhang** [alibaba/fastjson#4072]
```
package com.test;

import lombok.Data;

@Data
public class TestA {

    private String id;
    private Long id2;

    public TestA(TestB testB) {
        this.id = testB.getId();
        this.id2 = testB.getId2();
    }
}
```

```
package com.test;

import lombok.Data;

@Data
public class TestB {

    private String id;
    private Long id2;
    private Long id3;

    public TestB(){

    }
}
```
```
//测试类
import com.alibaba.fastjson.JSON;

public class Test {

    public static void main(String[] args) {

        String json = "{\"id\":\"testId\",\"id3\":111222}";
        TestA testA = JSON.parseObject(json, TestA.class);
        System.out.println(testA);
    }
}
```

**Comment by Melo15Zhang** [comment]
异常信息如下
Exception in thread "main" com.alibaba.fastjson.JSONException: create instance error, null, public com.test.TestA(com.test.TestB)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:1043)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:291)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:703)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:394)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:298)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:588)
	at com.test.Test.main(Test.java:10)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:1039)
	... 6 more
Caused by: java.lang.NullPointerException
	at com.test.TestA.<init>(TestA.java:13)
	... 11 more
