### ISSUE TITLE
使用UseISO8601DateFormat报错

### ISSUE THREAD

**Issue by QRXqrx** [alibaba/fastjson#4105]
我在使用fastjson进行随机json字符串构建的时候发现了问题，当Date值较大且使用``SerializationFeature.UseISO8601DateFormat``时会产生ArrayIndexOutOfBounds错误，比如：

**Date值**
``[8800519659559150410]``
**Feature配置**
```
[QuoteFieldNames, UseSingleQuotes, UseISO8601DateFormat, WriteNullListAsEmpty, WriteNullStringAsEmpty, WriteNullNumberAsZero, SkipTransientField, WriteTabAsSpecial, PrettyFormat, BrowserCompatible, NotWriteRootClassName, NotWriteDefaultValue, IgnoreNonFieldGetter, WriteBigDecimalAsPlain]
```
**报错**
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 23
	at com.alibaba.fastjson.util.IOUtils.getChars(IOUtils.java:288)
	at com.alibaba.fastjson.serializer.DateCodec.write(DateCodec.java:179)
	at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:79)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:312)
	at com.alibaba.fastjson.JSON.toString(JSON.java:1091)
```

**测试用例**
```
    @Test
    public void trialOnAIBError() {
        Date date = new Date(8800519659559150410L);
        JSONObject jsonObject = new JSONObject();
        jsonObject.put("date", date);
        System.out.println(jsonObject); // OK
        System.out.println(jsonObject.toString(SerializerFeature.UseISO8601DateFormat));
    }
```
**输出结果**
```
{"date":8800519659559150410}

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 23

	at com.alibaba.fastjson.util.IOUtils.getChars(IOUtils.java:288)
	at com.alibaba.fastjson.serializer.DateCodec.write(DateCodec.java:179)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:271)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:44)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:312)
	at com.alibaba.fastjson.JSON.toString(JSON.java:1091)
```

**Comment by yechen17** [comment]
您好，我对这个问题有一些想法，请给我一些时间去解决
