### ISSUE TITLE
2.0.2版本调用JSONObject.getInteger时出错

### ISSUE THREAD

**Issue by Wzp-2008** [alibaba/fastjson#4106]
错误详情：
Exception in thread "main" java.lang.NoClassDefFoundError: com/alibaba/fastjson/util/IdentityHashMap
	at com.alibaba.fastjson.util.TypeUtils.addBaseClassMappings(TypeUtils.java:1329)
	at com.alibaba.fastjson.util.TypeUtils.<clinit>(TypeUtils.java:104)
	at com.alibaba.fastjson.JSONObject.getInteger(JSONObject.java:268)
	at cn.wzpmc.mybot.api.MyBotApi.getGroupBotInfo(MyBotApi.java:112)
	at cn.wzpmc.mybot.Bot.<init>(Bot.java:52)
	at cn.wzpmc.mybot.Main.start(Main.java:211)
	at cn.wzpmc.mybot.Main.main(Main.java:281)
Caused by: java.lang.ClassNotFoundException: com.alibaba.fastjson.util.IdentityHashMap
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 7 more
代码：
![image](https://user-images.githubusercontent.com/55318422/166959219-82ee6aef-562e-41e6-a0a9-46d02d4d7744.png)
JDK版本：openjdk-16
在之前使用1.2.80版本时调用无错误，但当升级2.0.2版本后便出现此问题

**Comment by CodeInDreams** [comment]
+1

**Comment by Wzp-2008** [comment]
我发现是新版本的包名com.alibaba.fastjson2和老版本的包名com.alibaba.fastjson不一致，而这个com.alibaba.fastjson的2.0.2版本只是一个依赖包
