### ISSUE TITLE
Timestamp 反序列化问题

### ISSUE THREAD

**Issue by tungSing** [alibaba/fastjson#414]
我在做timestamp类型日期的反序列化遇到一个问题，错误信息如下
```java
Exception in thread "main" com.alibaba.fastjson.JSONException: For input string: "2015-09-07"
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:555)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:250)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:226)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:185)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:303)
```
代码如下
```java
	public static void main(String[] args) {
		String jsonStr = "{publishedDate:\"2015-09-07\"}";
		TestEntity news = JSON.parseObject(jsonStr, TestEntity.class);
		System.out.println(news.getPublishedDate());
	}
```
```java
public class TestEntity {
	private Timestamp publishedDate;

	public Timestamp getPublishedDate() {
		return publishedDate;
	}
	public void setPublishedDate(Timestamp publishedDate) {
		this.publishedDate = publishedDate;
	}
}
```
1.通过设置全局日期格式可以解决，但这个业务格式要求和全局不一样，所以无法改变全局
```java
    JSON.DEFFAULT_DATE_FORMAT = "yyyy-MM-dd";
```
2.通过设置解析器也能解决
```java
TestEntity news = JSON.parseObject(jsonStr, TestEntity.class,Feature.AllowISO8601DateFormat);
```
问：如何设置全局的解析器，不用每次都要传递参数

3.我尝试用注解，没有成功，代码如下
```java
	@JSONField(format="yyyy-MM-dd",parseFeatures={Feature.AllowISO8601DateFormat})
	private Timestamp publishedDate;
```
问：注解能成功吗

**Comment by qifanyang** [comment]
String jsonStr = "{publishedDate:\"2015-09-07 00:00:00\"}";

你可以看下#401

**Comment by RishonLi** [comment]
不能被解决

**Comment by holdqv** [comment]
英文时间格式转化还有问题吧
