### ISSUE TITLE
1.2.83版本 反序列化“2022-05-25 17:23:34:782”时间格式失败

### ISSUE THREAD

**Issue by chenjingkang** [alibaba/fastjson#4151]
Caused by: java.lang.NumberFormatException: For input string: "2022-05-25 17:23:34:782"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at com.alibaba.fastjson.serializer.DateCodec.cast(DateCodec.java:339)
	at com.alibaba.fastjson.parser.deserializer.AbstractDateDeserializer.deserialze(AbstractDateDeserializer.java:184)
	at com.alibaba.fastjson.parser.deserializer.AbstractDateDeserializer.deserialze(AbstractDateDeserializer.java:16)
	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:88)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:1278)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:893)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:1624)
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_2_TradeNotifyBaseInfo.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:287)
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_1_TradeEventNotify.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:287)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:705)
	... 4 more

**Comment by wenshao** [comment]
这个格式不对吧

**Comment by chenjingkang** [comment]
就是毫秒值的问题，之前版本这个可以正常解析。这个版本不行。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月26日 00:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [alibaba/fastjson] 1.2.83版本 反序列化“2022-05-25 17:23:34:782”时间格式失败 (Issue #4151) |

这个格式不对吧，怎么来的

**Comment by acries** [comment]
可以把完整反序列代码发出来吗。
 String dateStr = "2022-05-25 17:23:34:782";
LocalDateTime localDateTime = LocalDateTime.parse(dateStr, DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss:SSS"));
序列化和发序列都是ok的。

**Comment by chenjingkang** [comment]
![image](https://user-images.githubusercontent.com/33819521/170395634-56c402b3-1209-48af-b6ee-22d0c7a34842.png)

**Comment by acries** [comment]
2022-05-25 17:23:34:782时间格式错了，应该是2022-05-25 17:23:34.782

**Comment by acries** [comment]
如果转成Date类型的，默认格式应该是yyyy-MM-dd HH:mm:ss.SSS

**Comment by j-tyuan** [comment]
格式错误，很明显
<img width="967" alt="image" src="https://user-images.githubusercontent.com/45758098/170406559-15a40bae-0728-4ecd-9633-cd094903ee05.png">

**Comment by chenjingkang** [comment]
不是错不错，而是支不支持，低版本支持这个格式，1.2.83不支持这个格式

**Comment by adamoo00o0o** [comment]
> 

别人毫秒前面是.  你用的:

**Comment by oday-xiexin** [comment]
这种错误的时间格式没必要兼容吧 包袱太重了  自己改业务代码吧
