### ISSUE TITLE
 无法反序列化Class<?>对象

### ISSUE THREAD

**Issue by Watson-Bao** [alibaba/fastjson#4170]
反序列化Class<?>对象时报错   JDK1.8  fastjson 2.0.3
Exception in thread "main" com.alibaba.fastjson2.JSONException: not support autoType : 
	at com.alibaba.fastjson2.reader.ObjectReaderImplClass.readObject(ObjectReaderImplClass.java:30)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:159)

测试样例：

```
HelloObject helloObject = new HelloObject();
Class<?> clazz= helloObject.getClass();
String s = JSON.toJSONString(clazz);
System.out.println(s);
Class<?> parse = JSON.parseObject(s, Class.class);
System.out.println(parse);
```

**Comment by Watson-Bao** [comment]
时fastjson2 的 问题， 1.2.x 版本没有这个问题
