### ISSUE TITLE
升级到1.2.83后解析$.ref出现cause:java.lang.NoSuchMethodError: com.alibaba.fastjson.parser.deserializer.FieldDeserializer.getOwnerClass()

### ISSUE THREAD

**Issue by a337928** [alibaba/fastjson#4214]
升级到1.2.83已经解析有引用的json时报一下错误
cause:java.lang.NoSuchMethodError: com.alibaba.fastjson.parser.deserializer.FieldDeserializer.getOwnerClass()Ljava/lang/Class;
	at com.alibaba.fastjson.parser.DefaultJSONParser.handleResovleTask(DefaultJSONParser.java:1624)
	at com.alibaba.fastjson.JSON.parse(JSON.java:183)
	at com.alibaba.fastjson.JSON.parse(JSON.java:191)
	at com.alibaba.fastjson.JSON.parse(JSON.java:147)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:252)	
**补充一下object to String 是1.2.70版本的fastjson，用1.2.83版本转回来就报错了**

![image](https://user-images.githubusercontent.com/3282482/175000224-c88fff3e-2c4e-486a-8f2d-d95acf2831f2.png)

**Comment by wenshao** [comment]
jar冲突了吧？

**Comment by a337928** [comment]
> jar冲突了吧？

jar 没冲突，看着应该是1.2.83转老版本的json数据到java对象的是时候，如果json里面有对象引用就会报错。想问下就没有什么解决方案，比如feature配个什么属性可以支持老版本
