### ISSUE TITLE
TypeUtils.castToDouble() 直接转换含分组符","串时失败

### ISSUE THREAD

**Issue by edrikL** [alibaba/fastjson#426]
Caused by: java.lang.NumberFormatException: For input string: "264,010,000.00"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1250)
	at java.lang.Double.parseDouble(Double.java:540)
	at com.alibaba.fastjson.util.TypeUtils.castToDouble(TypeUtils.java:254)
	at com.alibaba.fastjson.parser.deserializer.NumberDeserializer.deserialze(NumberDeserializer.java:70)
	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:33)
	at com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer.parseField(ASMJavaBeanDeserializer.java:74)
	at com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer$InnerJavaBeanDeserializer.parseField(ASMJavaBeanDeserializer.java:86)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:330)
	at com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer.parseRest(ASMJavaBeanDeserializer.java:100)
	at Fastjson_ASM_F10CompanyProfileElem_6.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:635)
	at com.alibaba.fastjson.parser.deserializer.CollectionDeserializer.deserialze(CollectionDeserializer.java:63)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)
	... 45 more

**Comment by dachuanz** [comment]
Java新的数字表达特性是使用_每三位做一次分割 改成264_010_000.00就好了
