### ISSUE TITLE
序列化失败可以更可读地输出原因吗

### ISSUE THREAD

**Issue by ming15** [alibaba/fastjson#427]
今天项目发生了一个重大问题，在JSON解析的时候抛出异常，
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 160
	at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:868)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:602)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeString(SerializeWriter.java:1366)
	at com.alibaba.fastjson.serializer.StringCodec.write(StringCodec.java:49)
	at com.alibaba.fastjson.serializer.StringCodec.write(StringCodec.java:34)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:369)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:430)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:418)
```
由于JSON对象里内容非常多，很难单纯从代码里来判断是哪里出的问题,而且由于没有对JSON序列化try catch，只能临时添加try catch到异常的时候调用对象的toString输出，然后重新打包部署，导致整个服务3个小时内不可用。。所以当序列化失败时可不可以给出一个更好的异常信息呢？

ps 不知道为什么刚开始有异常信息的时候是输出数组越界，到了后来就没有位置了，到了最后就只有jetty异常了，导致排查问题非常困难.

出现问题的字符串为
```
================================================
服务器名称：[FFFF00]N23-物华天宝 [-]
开服时间：[FFFF00]2015年10月16日11：00（周五）[-]
================================================
```

**Comment by wenshao** [comment]
很抱歉给你造成困扰，在最新版中没有重现你的问题。

**Comment by ming15** [comment]
后来找到原因了，是在解析的时候遇到了一个非法的空格, 服务器名称：[FFFF00]N23-物华天宝 [-]物华天宝后面跟的空格，不是我们常用的ascii码为32的空格，而是一个ascii码为160特殊的空格符,导致JSON序列化时失败.

**Comment by wenshao** [comment]
这个bug已经修正了的，请用新版本
