### ISSUE TITLE
Caused by: java.lang.OutOfMemoryError: null

### ISSUE THREAD

**Issue by zhangjijian265** [alibaba/fastjson#4313]
使用fastjson作为springboot的转换器  上传大文件时报错

Caused by: java.lang.OutOfMemoryError: null
	at com.alibaba.fastjson2.JSONWriterUTF16.ensureCapacity(JSONWriterUTF16.java:912)
	at com.alibaba.fastjson2.JSONWriterUTF16JDK8.writeString(JSONWriterUTF16JDK8.java:143)
	at com.alibaba.fastjson2.writer.ObjectWriter_181.write(Unknown Source)
	at com.alibaba.fastjson2.writer.ObjectWriter_180.write(Unknown Source)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:187)
	at com.alibaba.fastjson2.writer.ObjectWriter_113.write(Unknown Source)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:770)
	at com.ynet.inmanage.common.aspect.SysLogAspect.dataIntoRequestMethod(SysLogAspect.java:251)
	at com.ynet.inmanage.common.aspect.SysLogAspect.saveSysLog(SysLogAspect.java:135)
	at com.ynet.inmanage.common.aspect.SysLogAspect.around(SysLogAspect.java:85)
	at sun.reflect.GeneratedMethodAccessor250.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.ynet.inmanage.modules.system.controller.file.FileSystemManageController$$EnhancerBySpringCGLIB$$90c45ec7.fileOrInsertFileUpload(<generated>)
	at sun.reflect.GeneratedMethodAccessor4354.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
	... 69 common frames omitted

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/issues
请在这里提issue
