### ISSUE TITLE
当json末尾有\n的时候,反序列化抛异常 `com.alibaba.fastjson.JSONException: unclosed.str`

### ISSUE THREAD

**Issue by yuankui** [alibaba/fastjson#432]
Result.java

```
public final class Result {

    private boolean success;
    private String reason_code;

    public boolean isSuccess() {
        return success;
    }

    public void setSuccess(boolean success) {
        this.success = success;
    }

    public String getReason_code() {
        return reason_code;
    }

    public void setReason_code(String reason_code) {
        this.reason_code = reason_code;
    }
}
```

DemoTest.java
```
package xxxxxx;

import com.alibaba.fastjson.JSON;
import org.junit.Test;

public class DemoTest {
    @Test
    public void testJson() {
        String result = "{\"reason_code\":\"001\",\"success\":false}\n";
        JSON.parseObject(result, Result.class);
    }
}
```

抛异常

```
com.alibaba.fastjson.JSONException: unclosed.str
	at com.alibaba.fastjson.parser.JSONLexerBase.scanSymbol(JSONLexerBase.java:678)
	at com.alibaba.fastjson.parser.JSONLexerBase.scanSymbol(JSONLexerBase.java:624)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:241)
	at com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer.parseRest(ASMJavaBeanDeserializer.java:100)
	at Fastjson_ASM_Result_1.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:250)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:226)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:185)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:303)
	at xxxxxx.DemoTest.testJson(DemoTest.java:13)
```

**Comment by yuankui** [comment]
版本1.2.4,1.2.6都有这个问题.

**Comment by generalthink** [comment]
这个并不算是严格的json字符串吧

**Comment by yuankui** [comment]
@generalthink 末尾多一个空格算吗?

**Comment by generalthink** [comment]
@yuankui   是可以的
```java
String result = "{\"reason_code\":\"001\",\"success\":false}      ";
    String gString = JSON.parseObject(result, String.class);
    System.out.println(gString);

print: {"reason_code":"001","success":false}
```

**Comment by generalthink** [comment]
@yuankui   同理换成你自己的类也是可以的

**Comment by yuankui** [comment]
@generalthink 问题就在这里啊,为什么多了空格可以,多了换行不行?
有什么实质上的区别吗?

**Comment by generalthink** [comment]
\r标示回车，\n表示换行。
windows系统中\r\n标示新的一行。unix系统中\n标示新的一行

**Comment by our880tom** [comment]
觉得这个应该不算什么bug

**Comment by yuankui** [comment]
@our880tom 应该算是一个feature?

**Comment by wenshao** [comment]
bug fixed. it will include in 1.2.9 & 1.1.49.android

**Comment by dsz-nvxclouds** [comment]
String data = "{\"name\":\"\\n\\d\\r\\s\\/n\\dd222\",\"age\":6}";
请问如何正确发序列化上面的json。试了下所有的fastsjson，objectmapper都有JSONException。

**Comment by dsz-nvxclouds** [comment]
> String data = "{"name":"\n\d\r\s\/n\dd222","age":6}";
> 请问如何正确发序列化上面的json。试了下所有的fastsjson，objectmapper都有JSONException。

写错了，应该是发序列化。不好意思
