### ISSUE TITLE
parseObject反序列化导致OutOfMemoryError

### ISSUE THREAD

**Issue by jieyuwang** [alibaba/fastjson#4337]
224 java.lang.OutOfMemoryError: Java heap space
   225     at java.lang.String.substring(String.java:1957)
   226     at com.alibaba.fastjson.parser.JSONScanner.subString(JSONScanner.java:161)
   227     at com.alibaba.fastjson.parser.JSONScanner.stringVal(JSONScanner.java:144)
   228     at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:496)
   229     at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:581)
   230     at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1430)
   231     at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1390)
   232     at com.alibaba.fastjson.JSON.parse(JSON.java:181)
   233     at com.alibaba.fastjson.JSON.parse(JSON.java:191)
   234     at com.alibaba.fastjson.JSON.parse(JSON.java:244)
   235     at com.alibaba.fastjson.JSON.parseObject(JSON.java:248)

运行很久的程序，最近隔几天就一台机器oom，导致异常，请问下大家有遇到过么？
 <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.83_noneautotype</version>
        </dependency>

**Comment by wenshao** [comment]
用2.0.23试试看

**Comment by jieyuwang** [comment]
> 用2.0.23试试看
👌，目前改用gson了，暂时没问题了，再有问题我试试新版本

**Comment by miguanxiong** [comment]
参见这篇文章，JSON.parseObject(text，class），这方法有问题
https://www.cnblogs.com/liqipeng/p/11665889.html
