### ISSUE TITLE
List<Integer>属性JSONObject.toJSONString报错NPE

### ISSUE THREAD

**Issue by ivoikkk** [alibaba/fastjson#4368]
版本：2.0.20+
复现场景：
```java
@Getter
@Setter
public class Dto1 {
    private List<Dto2> dto2List;
}

@Getter
@Setter
public class Dto2 {
    private List<Integer> integerList;
}
```
```java
Dto1 dto1 = new Dto1();
List<Dto2> dto2List = new ArrayList<>();
for (int i = 0; i < 2; i++) {
    Dto2 dto2 = new Dto2();
    dto2.setIntegerList(Arrays.asList(1, 2, 3));
    dto2List.add(dto2);
}
dto1.setDto2List(dto2List);
System.out.println(JSONObject.toJSONString(dto1));
```
Caused by: java.lang.NullPointerException
	at com.alibaba.fastjson2.JSONWriter.setPath(JSONWriter.java:200)
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:223)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:1469)

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.28
问题已修复，请用新版本
