### ISSUE TITLE
升级版本到1.2.83后出现NPE异常

### ISSUE THREAD

**Issue by Force-King** [alibaba/fastjson#4410]
java.lang.NullPointerException
        at com.alibaba.fastjson.util.TypeUtils.getClass(TypeUtils.java:2457)
        at com.alibaba.fastjson.util.TypeUtils.optionalEmpty(TypeUtils.java:3412)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:679)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:394)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:362)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:325)

**Comment by wenshao** [comment]
升级到2.0.34版本试试看
