### ISSUE TITLE
java.lang.AbstractMethodError: Receiver class com.alibaba.fastjson.support.jaxrs.FastJsonAutoDiscoverable does not define or inherit an implementation of the resolved method 'abstract void configure(jakarta.ws.rs.core.FeatureContext)' of interface org.glassfish.jersey.internal.spi.AutoDiscoverable.

### ISSUE THREAD

**Issue by weixuehu** [alibaba/fastjson#4492]
java.lang.AbstractMethodError: Receiver class com.alibaba.fastjson.support.jaxrs.FastJsonAutoDiscoverable does not define or inherit an implementation of the resolved method 'abstract void configure(jakarta.ws.rs.core.FeatureContext)' of interface org.glassfish.jersey.internal.spi.AutoDiscoverable.
	at org.glassfish.jersey.model.internal.CommonConfig.configureAutoDiscoverableProviders(CommonConfig.java:615)
	at org.glassfish.jersey.server.ResourceConfig.configureAutoDiscoverableProviders(ResourceConfig.java:819)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:339)
	at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:310)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:309)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:274)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:338)
	at jakarta.servlet.GenericServlet.init(GenericServlet.java:178)
	at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:107)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:944)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:901)
	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:649)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by weixuehu** [comment]
请问这个怎么解决
