### ISSUE TITLE
fastjson-1.2.6 parse NullPointerException

### ISSUE THREAD

**Issue by tyronecai** [alibaba/fastjson#500]
非常简单的一个json串，多线程解析程序在启动时偶尔会报 NullPointerException 错，后面又不出现了，在 https://github.com/alibaba/fastjson/issues/306 也提到同样问题，是什么原因？

java.lang.NullPointerException
        at com.alibaba.fastjson.parser.SymbolTable.addSymbol(SymbolTable.java:144)
        at com.alibaba.fastjson.parser.JSONScanner.addSymbol(JSONScanner.java:157)
        at com.alibaba.fastjson.parser.JSONLexerBase.scanSymbol(JSONLexerBase.java:826)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:220)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1236)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1205)
        at com.alibaba.fastjson.JSON.parse(JSON.java:108)
        at com.alibaba.fastjson.JSON.parse(JSON.java:99)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:170)

**Comment by wenshao** [comment]
有点奇怪了

**Comment by caiqq1989** [comment]
我使用的是1.1.40版本，目前在多线程情况下也会偶尔报这个错误，请问何解？

**Comment by caiqq1989** [comment]
@wenshao 我使用的是1.1.40版本，目前在多线程情况下也会偶尔报这个错误，请问何解？

**Comment by wenshao** [comment]
升级到最新版本1.2.8看看

**Comment by wenshao** [comment]
1.2.9重写了SymbolTable，不会再有这个问题啦

**Comment by hzl0820** [comment]
我们升级至1.2.9后，多线程转换时出现了新的异常，重新运行问题解决：
Caused by: java.lang.NullPointerException
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:206) ~[fastjson-1.2.9.jar:?]
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:477) ~[fastjson-1.2.9.jar:?]
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:201) ~[fastjson-1.2.9.jar:?]
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:477) ~[fastjson-1.2.9.jar:?]
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:338) ~[fastjson-1.2.9.jar:?]
