### ISSUE TITLE
NoSuchMethodError: java.lang.reflect.Method.getParameterCount() 更新到snapshot报错

### ISSUE THREAD

**Issue by bwzhang2011** [alibaba/fastjson#516]
@wenshao, 更新到最新snapshot编译打包重新测试报错（rocketmq中的RemotingCommand的序列化）

Caused by: java.lang.NoSuchMethodError: java.lang.reflect.Method.getParameterCount()I
	at com.alibaba.fastjson.util.FieldInfo.<init>(FieldInfo.java:87)
	at com.alibaba.fastjson.util.FieldInfo.<init>(FieldInfo.java:59)
	at com.alibaba.fastjson.util.TypeUtils.computeGetters(TypeUtils.java:1161)
	at com.alibaba.fastjson.serializer.ASMSerializerFactory.createJavaBeanSerializer(ASMSerializerFactory.java:126)
	at com.alibaba.fastjson.serializer.SerializeConfig.createASMSerializer(SerializeConfig.java:96)
	at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:134)
	... 7 more

原1.2.8是没有报错的，请问是否新的版本（ASM方面的改写）是否去掉了一些方法

**Comment by wenshao** [comment]
合并了一个pull request，他使用了JDK 8的api。已经修复了，谢谢反馈

**Comment by CodePlayer** [comment]
不好意思，没注意 Method.getParameterCount() 是JDK 8的新增API。我本来是用的JDK 7 u45，但是checkout fastjson到本地后发现部分API不兼容，必须升级到JDK 8才能完全不报错，于是就重新安装了JDK 8 u73。Junit Test的时候也没出什么问题，就直接commit了。
