### ISSUE TITLE
JavaBean中包含BigDecimal类型字段的序列化和反序列化

### ISSUE THREAD

**Issue by blessyezi** [alibaba/fastjson#535]
public class TestPOJO
{
    private String a;
    private BigDecimal b;
    //getter and setter
}

public class Test
{
    public static void main(String[] args)
    {
        TestPOJO testPOJO = new TestPOJO();
        testPOJO.setA("a");
        testPOJO.setB(new BigDecimal("1234512312312312312312"));
        String s = JSON.toJSONString(testPOJO);
        System.out.println(s);

        JSON.parseObject(s, TestPOJO.class, Feature.UseBigDecimal);
    }
}

运行如下

{"a":"a","b":1234512312312312312312}
Exception in thread "main" com.alibaba.fastjson.JSONException: 1234512312312312312312
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:555)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:251)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:227)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:186)
	at Test.main(Test.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.NumberFormatException: 1234512312312312312312
	at com.alibaba.fastjson.parser.JSONLexerBase.longValue(JSONLexerBase.java:2946)
	at com.alibaba.fastjson.serializer.BigDecimalCodec.deserialze(BigDecimalCodec.java:64)
	at com.alibaba.fastjson.serializer.BigDecimalCodec.deserialze(BigDecimalCodec.java:57)
	at Fastjson_ASM_TestPOJO_1.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)
	... 9 more

请问这种应该怎么处理啊？

**Comment by wenshao** [comment]
这是一个bug，已经修复，请等待几天，等我发布1.2.9版本

**Comment by zuoliangliang** [comment]
![1](https://cloud.githubusercontent.com/assets/4179079/14634159/48614a7a-0653-11e6-9993-7e1d66f93417.png)
![2](https://cloud.githubusercontent.com/assets/4179079/14634161/4d139226-0653-11e6-912a-0a5745ae918f.png)

**Comment by zuoliangliang** [comment]
用的是1.2.9BigDecimal还有问题

**Comment by zuoliangliang** [comment]
换成Double就可以了

**Comment by zuoliangliang** [comment]
请问怎么取消默认都使用bigDecimal

**Comment by greenlaw110** [comment]
同样的问题：如何取消默认使用BigDecimal？
