### ISSUE TITLE
自1.1.48-android版本开始（最新版1.1.49-android也出错）基于共享的登录页面始终出错。

### ISSUE THREAD

**Issue by ctyytc** [alibaba/fastjson#553]
错误信息如下：

java.lang.ArrayIndexOutOfBoundsException: length=895; index=895
    at com.alibaba.fastjson.parser.JSONLexer.readString(JSONLexer.java:797)
    at com.alibaba.fastjson.parser.JSONLexer.scanStringValue(JSONLexer.java:1062)
    at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:414)
    at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:481)
    at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1307)
    at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1272)
    at com.alibaba.fastjson.JSON.parse(JSON.java:100)
    at com.alibaba.fastjson.JSON.parse(JSON.java:91)
    at com.alibaba.fastjson.JSON.parseObject(JSON.java:131)
    at com.ali.user.mobile.rpc.protocol.securityjson.SecurityDeserializer.parser(SecurityDeserializer.java:47)
    at com.ali.user.mobile.rpc.RpcInvocationHandler.invoke(RpcInvocationHandler.java:100)
    at java.lang.reflect.Proxy.invoke(Proxy.java:393)
    at $Proxy8.unifyLogin(Unknown Source)
    at com.ali.user.mobile.login.service.impl.UserLoginServiceImpl.unifyLoginWithTaobaoGW(UserLoginServiceImpl.java:54)
    at com.ali.user.mobile.login.biz.LoginBusiness.unifyLogin(LoginBusiness.java:761)
    at com.ali.user.mobile.login.biz.LoginBusiness.access$300(LoginBusiness.java:90)
    at com.ali.user.mobile.login.biz.LoginBusiness$2.doInBackground(LoginBusiness.java:344)
    at com.ali.user.mobile.login.biz.LoginBusiness$2.doInBackground(LoginBusiness.java:316)
    at android.os.AsyncTask$2.call(AsyncTask.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
com.ali.user.mobile.rpc.exception.RpcException: net work error
    at com.ali.user.mobile.rpc.protocol.securityjson.SecurityDeserializer.parser(SecurityDeserializer.java:75)
    at com.ali.user.mobile.rpc.RpcInvocationHandler.invoke(RpcInvocationHandler.java:100)
    at java.lang.reflect.Proxy.invoke(Proxy.java:393)
    at $Proxy8.unifyLogin(Unknown Source)
    at com.ali.user.mobile.login.service.impl.UserLoginServiceImpl.unifyLoginWithTaobaoGW(UserLoginServiceImpl.java:54)
    at com.ali.user.mobile.login.biz.LoginBusiness.unifyLogin(LoginBusiness.java:761)
    at com.ali.user.mobile.login.biz.LoginBusiness.access$300(LoginBusiness.java:90)
    at com.ali.user.mobile.login.biz.LoginBusiness$2.doInBackground(LoginBusiness.java:344)
    at com.ali.user.mobile.login.biz.LoginBusiness$2.doInBackground(LoginBusiness.java:316)
    at android.os.AsyncTask$2.call(AsyncTask.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)

**Comment by wenshao** [comment]
JSONLexer的代码行号797对不上，请问用的具体是哪个版本？

**Comment by ctyytc** [comment]
这个错误是1.1.48版本出现的log，1.1.49版本的错误日志我没有贴出来

**Comment by wenshao** [comment]
是因为存在\\\"这样字符串引起的，问题修复，等在1.1.50.android版本吧

**Comment by wenshao** [comment]
问题在1.1.50.android & 1.1.51.android中都已经修复，先关闭啦
