### ISSUE TITLE
bug in 1.2.10

### ISSUE THREAD

**Issue by edwardpro** [alibaba/fastjson#584]
Json String below:
"{\"AmIz0S69YpTC6xsCxaZgDcVYZXlZnSwqG8MQQpc9sK_7\":1,\"type\":\"2\",\"$ref\":\"$[0].msgAttrMap\",\"url\":\"xxxxxxxxxxxxxxxx\"}"

I just use "JSON.parseObject("{\"AmIz0S69YpTC6xsCxaZgDcVYZXlZnSwqG8MQQpc9sK_7\":1,\"type\":\"2\",\"$ref\":\"$[0].msgAttrMap\",\"url\":\"xxxxxxxxxxxxx\"}")"

it will catch Exception:

Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:388)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1286)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1252)
	at com.alibaba.fastjson.JSON.parse(JSON.java:110)
	at com.alibaba.fastjson.JSON.parse(JSON.java:101)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:172)
	at 

And if I use this:
"{\"AmIz0S69YpTC6xsCxaZgDcVYZXlZnSwqG8MQQpc9sK_7\":1,\"type\":\"2\",\"ref\":\"$[0].msgAttrMap\",\"url\":\"xxxxxxxxxxxxxxx\"}"

it will run well. So jsonObject can't be occour a "$" in json key.

**Comment by wenshao** [comment]
use DisableSpecialKeyDetect feature:
```java
JSON.parseObject(obj, Model.class, Feature.DisableSpecialKeyDetect);
```

**Comment by edwardpro** [comment]
Thanks
