### ISSUE TITLE
1.2.11 泛型子类序列化出错

### ISSUE THREAD

**Issue by luohoufu** [alibaba/fastjson#621]
Caused by: java.lang.VerifyError: (class: com/alibaba/fastjson/serializer/ASMSerializer_3_StringResult, method: writeAsArrayNonContext signature: (Lcom/alibaba/fastjson/serializer/JSONSerializer;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/reflect/Type;I)V) Incompatible argument to function

```
class StringResult extends Result<String>

 StringResult result = new StringResult();
        result.setRequestId(requestId);
        result.setCode(code);
        result.setMessage(message);
        return JSONObject.toJSONString(result, SerializerFeature.WriteMapNullValue);
```

at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.7.0_80]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2595) ~[?:1.7.0_80]
	at java.lang.Class.getConstructor0(Class.java:2895) ~[?:1.7.0_80]
	at java.lang.Class.newInstance(Class.java:354) ~[?:1.7.0_80]
	at com.alibaba.fastjson.serializer.ASMSerializerFactory.createJavaBeanSerializer(ASMSerializerFactory.java:438) ~[fastjson-1.2.11.jar:?]
	at com.alibaba.fastjson.serializer.SerializeConfig.createASMSerializer(SerializeConfig.java:99) ~[fastjson-1.2.11.jar:?]
	at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:137) ~[fastjson-1.2.11.jar:?]
	... 55 more

**Comment by wenshao** [comment]
谢谢反馈，已知问题，已经修正，请等待1.2.12版本，预计这个月底发布

**Comment by 88567free** [comment]
我使用1.1.51.android 也出现这个问题 请问有解决方法吗
