### ISSUE TITLE
A JSONField bug when parsing Date

### ISSUE THREAD

**Issue by Andecy** [alibaba/fastjson#627]
@JSONField(format="yyyy/MM/dd HH:mm:ss") will throw  but @JSONField(format="yyyy-MM-dd HH:mm:ss") is OK

        @JSONField(format="yyyy-MM-dd HH:mm:ss")
        public Date serverTime;

        @JSONField(format="yyyy/MM/dd HH:mm:ss")
        public Date publishTime;

this code in A class file

StackTrace:

 Caused by: java.lang.NumberFormatException: Invalid long: "2016/5/10 10:17:10"
     at java.lang.Long.invalidLong(Long.java:124)
     at java.lang.Long.parse(Long.java:363)
     at java.lang.Long.parseLong(Long.java:353)
     at java.lang.Long.parseLong(Long.java:321)
     at com.alibaba.fastjson.serializer.DateCodec.cast(DateCodec.java:298)
     at com.alibaba.fastjson.serializer.DateCodec.deserialze(DateCodec.java:240)
     at com.alibaba.fastjson.parser.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:39)
     at com.alibaba.fastjson.parser.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:774)
     at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:636)
     at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:97)
     at com.alibaba.fastjson.parser.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:39)
     at com.alibaba.fastjson.parser.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:774)
     at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:636)
     at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:97)
     at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:682)

I can read Chinese
我能够阅读中文

**Comment by wenshao** [comment]
原来没有实现parse对JSONField(format="xxxx")的支持，谢谢你的反馈，1.2.12版本将会支持，预计发布在这个月22日

**Comment by Andecy** [comment]
非常开心能及时收到回复！

对新版本可以支持这种用法表示期待(¯﹃¯)

再次感谢你的付出和努力！
