### ISSUE TITLE
Android6.0 解析Json报错，用的最新的包

### ISSUE THREAD

**Issue by hellotiger** [alibaba/fastjson#629]
W/System.err﹕ java.lang.ArithmeticException: error:0f06707b:elliptic curve routines:EC_GROUP_new_by_curve_name:UNKNOWN_GROUP
 W/System.err﹕ at java.math.NativeBN.BN_new(Native Method)
 W/System.err﹕ at java.math.BigInt.makeValid(BigInt.java:51)
 W/System.err﹕ at java.math.BigInt.putULongInt(BigInt.java:85)
 W/System.err﹕ at java.math.BigInteger.<init>(BigInteger.java:103)
 W/System.err﹕ at java.math.BigInteger.valueOf(BigInteger.java:373)
 W/System.err﹕ at java.math.BigDecimal.getUnscaledValue(BigDecimal.java:2893)
 W/System.err﹕ at java.math.BigDecimal.toString(BigDecimal.java:2196)
 W/System.err﹕ at com.alibaba.fastjson.JSONObject.getString(JSONObject.java:268)

**Comment by hellotiger** [comment]
急，求大神看看

**Comment by wenshao** [comment]
有点奇怪了，这个BigDecimal是啥值啊，toString都会报错。。。。

**Comment by hellotiger** [comment]
我用getDoubleValue，getString都会报错，后台返回确实是double类型；
但是第一次请求解析json会报错，接下来再请求就不会报错了，
现在try catch 报错再解析一遍，目前我只能这么解决。

**Comment by wenshao** [comment]
能否提供重现问题的case，你这样反馈找不到原因

**Comment by zhaozepeng** [comment]
温少，解决了么？这个问题貌似是 "android 6.0 new BigInteger(byte[])函数会崩溃"的问题，可否定位一下？

**Comment by wenshao** [comment]
没有定位，能否给出重现问题的case，好让我下个版本解决

**Comment by benniaobuguai** [comment]
6.0的系统，在使用BigDecimal好多问题呀，(new BigDecimal("50").divide(new BigDecimal("2"), 0)).intValue()，其它版本都正常。。。都正常。。。

**Comment by 362750493** [comment]
反序列化的问题很多，特别是在24的sdk下
