### ISSUE TITLE
数据长度大，序列化不了

### ISSUE THREAD

**Issue by xysoko** [alibaba/fastjson#681]
[2016-06-18 15:54:26 ERROR][ServerHeartTimer]com.alibaba.fastjson.JSONException: create asm serializer error, class class com.game.player.structs.Player
com.alibaba.fastjson.JSONException: create asm serializer error, class class com.game.player.structs.Player
	at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:170)
	at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:117)
	at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:504)
	at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:320)
	at com.alibaba.fastjson.serializer.JSONSerializer.getObjectWriter(JSONSerializer.java:318)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:261)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:547)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:536)
	at com.game.player.Manager.PlayerManager.makeRoleBeanByPlayer(PlayerManager.java:335)
	at com.game.player.Manager.PlayerManager.timingSavePlayer(PlayerManager.java:1013)
	at com.game.Server.Timer.ServerHeartTimer.action(ServerHeartTimer.java:38)
	at game.core.net.thread.ServerThread.run(ServerThread.java:110)
Caused by: java.lang.ClassFormatError: Invalid method Code length 68840 in class file com/alibaba/fastjson/serializer/ASMSerializer_57_Player
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at com.alibaba.fastjson.util.ASMClassLoader.defineClassPublic(ASMClassLoader.java:174)
	at com.alibaba.fastjson.serializer.ASMSerializerFactory.createJavaBeanSerializer(ASMSerializerFactory.java:396)
	at com.alibaba.fastjson.serializer.SerializeConfig.createASMSerializer(SerializeConfig.java:95)
	at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:163)

用最新1.2.12 序列化出错， 用1.2.5序列化OK的， 做游戏的， 这个类数据很大

**Comment by xysoko** [comment]
类结构很大，整个游戏玩家个体的所有数据都在这个类中

**Comment by wenshao** [comment]
多少个字段？

**Comment by xysoko** [comment]
一个字段
