### ISSUE TITLE
final字段反系列化出错

### ISSUE THREAD

**Issue by taoweiji** [alibaba/fastjson#698]
`Caused by: com.alibaba.fastjson.JSONException: set property error, TAG
                                                                   at com.alibaba.fastjson.parser.deserializer.FieldDeserializer.setValue(FieldDeserializer.java:89)
                                                                   at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:641)
                                                                   at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:97)
                                                                   at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:682)
                                                                   at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:655)
                                                                   at com.alibaba.fastjson.JSON.parseObject(JSON.java:216)
                                                                   at com.alibaba.fastjson.JSON.parseObject(JSON.java:188)
                                                                   at com.alibaba.fastjson.JSON.parseObject(JSON.java:147)
                                                                   at com.alibaba.fastjson.JSON.parseObject(JSON.java:252)`

> public static final String TAG = UserInfo.class.getSimpleName();
版本：compile 'com.alibaba:fastjson:1.1.52.android'

**Comment by githublaohu** [comment]
反序列化，final，
依据java语言特性，final 应该是不支持反序列化。一定要序列化 final字段，违反了设计原则，语言原则。

**Comment by wenshao** [comment]
没处理好static和final，将会尽快修正，谢谢反馈

**Comment by wenshao** [comment]
已修复问题，将会尽快发布新版本1.1.53.android
