### ISSUE TITLE
map cpu 100%

### ISSUE THREAD

**Issue by Aliece** [alibaba/fastjson#713]
java.lang.Thread.State: RUNNABLE
	at java.util.HashMap.getEntry(HashMap.java:465)
	at java.util.HashMap.get(HashMap.java:417)
	at com.alibaba.fastjson.JSONObject.get(JSONObject.java:99)

普通的单线程put，get操作什么情况会出现这样死循环呢 不好排查 用的是1.2.7 版本 求大拿@wenshao帮忙

**Comment by Aliece** [comment]
自己使用错误导致
