### ISSUE TITLE
fastjson和加密算法有冲突？

### ISSUE THREAD

**Issue by lmm1990** [alibaba/fastjson#714]
java.lang.SecurityException: JCE cannot authenticate the provider BC
        at javax.crypto.Cipher.getInstance(Cipher.java:657)
        at javax.crypto.Cipher.getInstance(Cipher.java:596)
        at ssp.asyncTask.service.utils.Cryptography.AES256.encrypt(AES256.java:60)
        at ssp.asyncTask.service.utils.Cryptography.AES256.encrypt(AES256.java:48)
        at ssp.asyncTask.service.utils.Cryptography.ADXPriceCrypt.encrypt(ADXPriceCrypt.java:22)
        at ssp.asyncTask.service.classHandler.task.DSPUserRechargeTask$1.run(DSPUserRechargeTask.java:38)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.jar.JarException: file:/opt/serviceList/ssp.asyncTask.service/ssp.asyncTask.service-jar-with-dependencies.jar has unsigned entries - com/alibaba/fastjson/annotation/JSONCreator.class

**Comment by lmm1990** [comment]
Cipher cipher= Cipher.getInstance("AES/ECB/PKCS7Padding", "BC");
这句报错

**Comment by wenshao** [comment]
这个和fastjson没关系吧
