### ISSUE TITLE
字符串"yyyy-MM-dd HH:mm"发序列化成Date类型出错

### ISSUE THREAD

**Issue by aaronhuang** [alibaba/fastjson#729]
日期字符串如“2016-07-15 15:53”, 在反序列化的成Date类型的时候，报错如下。

字段上配置如下
@JSONField(format = "yyyy-MM-dd HH:mm")
public Date startTime;

版本：fastjson-1.1.52.android.jar

Exception in thread "main" com.alibaba.fastjson.JSONException: For input string: "2016-07-18 14:01"
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:686)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:655)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:216)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:188)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:147)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:252)
	at SerializeTest.main(SerializeTest.java:21)
Caused by: java.lang.NumberFormatException: For input string: "2016-07-18 14:01"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Long.parseLong(Unknown Source)
	at java.lang.Long.parseLong(Unknown Source)
	at com.alibaba.fastjson.serializer.DateCodec.cast(DateCodec.java:298)
	at com.alibaba.fastjson.serializer.DateCodec.deserialze(DateCodec.java:240)
	at com.alibaba.fastjson.parser.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:39)
	at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:595)
	at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:97)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:682

附上简单测试：

```java
import java.io.Serializable;
import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

public class Person implements Serializable {

	public String name;

	@JSONField(format = "yyyy-MM-dd HH:mm")
	public Date startTime;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getStartTime() {
		return startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Override
	public String toString() {
		return "Person [name=" + name + ", startTime=" + startTime + "]";
	}

}


import java.util.Date;

import com.alibaba.fastjson.JSON;

public class SerializeTest {

	public static void main(String[] args) {
		Person person = new Person();
		person.setName("bob");
		person.setStartTime(new Date());

		String result = JSON.toJSONString(person);
		System.out.println(result);
		Person person2 = JSON.parseObject(result, Person.class);
		System.out.println(person2.toString());

	}

}
```

**Comment by wenshao** [comment]
谢谢反馈，问题已解决，这个问题在标准版1.2.14上不存在，但在1.1.52.android上存在。下一个android版本将会解决此问题，预计在周末发布。
