### ISSUE TITLE
【解析错误】

### ISSUE THREAD

**Issue by CodeYouth** [alibaba/fastjson#742]
使用JSON.toJSONString序列化写入writeLine文件中，读取文件反序列化就出现解析错误

```
com.alibaba.fastjson.JSONException: not match : - p
	at com.alibaba.fastjson.parser.JSONLexerBase.nextTokenWithChar(JSONLexerBase.java:388)
	at com.alibaba.fastjson.parser.JSONLexerBase.nextTokenWithColon(JSONLexerBase.java:370)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseExtra(DefaultJSONParser.java:1460)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:655)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:564)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:783)
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_1_CrawledWord.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:185)
	at com.alibaba.fastjson.parser.deserializer.ArrayListTypeFieldDeserializer.parseArray(ArrayListTypeFieldDeserializer.java:118)
	at com.alibaba.fastjson.parser.deserializer.ArrayListTypeFieldDeserializer.parseField(ArrayListTypeFieldDeserializer.java:52)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:543)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:189)
	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:47)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:543)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:189)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:185)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:614)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:339)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:243)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:456)
	at com.alibaba.fastjson.JSON$parseObject.call(Unknown Source)
```

错误提示不是很清晰，希望高手帮忙解决一下

**Comment by CodeYouth** [comment]
重启应用后，又能正常解析了-_-||| 版本 `1.2.14`

**Comment by wenshao** [comment]
应该是格式错乱了，非法的JSON字符串

**Comment by CodeYouth** [comment]
写跟读的过程没有修改过文件，格式为什么会乱呢？

**Comment by mauersu** [comment]
com.alibaba.fastjson.JSONException: not match : - " 
我也遇到这个问题了，非法json字符串，@wenshao 可否报的错误信息更清晰些呢，对于大json找错误真心好费劲啊
