### ISSUE TITLE
序列化的json字符串有语法错误，版本 1.2.14

### ISSUE THREAD

**Issue by CodeYouth** [alibaba/fastjson#745]
使用 `JSON.toJSONString` 方法序列化 java 对象为 String，解析的时候出现语法错误
```
com.alibaba.fastjson.JSONException: syntax error, expect {, actual :, pos 92212
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:337)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:783)
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_1_CrawledWord.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:185)
	at com.alibaba.fastjson.parser.deserializer.ArrayListTypeFieldDeserializer.parseArray(ArrayListTypeFieldDeserializer.java:118)
	at com.alibaba.fastjson.parser.deserializer.ArrayListTypeFieldDeserializer.parseField(ArrayListTypeFieldDeserializer.java:52)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:543)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:189)
	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:47)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:543)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:189)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:185)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:614)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:339)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:243)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:456)
	at com.alibaba.fastjson.JSON$parseObject.call(Unknown Source)
```

```
Error: Parse error on line 1:
...lue":0.0163789287295:0,"c2cClick":0,"cli
-----------------------^
Expecting 'EOF', '}', ',', ']', got ':'
```

double类型的数据

**Comment by wenshao** [comment]
double类型？能够提供重现问题的case么？
