### ISSUE TITLE
com.alibaba.fastjson.util.TypeUtils.castToJavaBean 报错 java.lang.ArrayIndexOutOfBoundsException: 0

### ISSUE THREAD

**Issue by codefan** [alibaba/fastjson#749]
版本：1.2.11
调用JSONObject.getObject(String key, Class<T> clazz)时，  在com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer的第666行
 Type paramType = method.getGenericParameterTypes()[0]; 中报 java.lang.ArrayIndexOutOfBoundsException: 0
 错误。

原因是对象中有一个List<>类型的属性，刚好json 数据为 attr:[] 这样的空数组。

**Comment by codefan** [comment]
1.2.14版本还是有这个问题，在738行

Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.createInstance(JavaBeanDeserializer.java:738)
	at com.alibaba.fastjson.util.TypeUtils.castToJavaBean(TypeUtils.java:919)

**Comment by wenshao** [comment]
能帮忙提供重现问题的testcase么？

**Comment by codefan** [comment]
非常感谢 wenshao  这么及时的回复。 我今天重写了一下代码就可以避免这个错误，不知道是不是我理解的问题。

>   public static void toOptInfo(){
		try {
			String text = FileIOOpt.readStringFromFile("D:\\Projects\\RunData\\optinfo.josn");
	    	JSONObject jsonMap = (JSONObject)JSON.parse(text);	
	    	for(String skey : jsonMap.keySet()){
	    		String str = JSON.toJSONString(jsonMap.get(skey));
	    		OptInfo opt =  JSON.parseObject(str, OptInfo.class); 
	    		System.out.println(opt.getOptName());
	    	}   
		} catch (IOException e) {
			return;
		}

    }
    public static void toOptInfo2(){
		try {
			String text = FileIOOpt.readStringFromFile("D:\\Projects\\RunData\\optinfo.josn");
	    	JSONObject jsonMap = (JSONObject)JSON.parse(text);	
	    	for(String skey : jsonMap.keySet()){	    		
	    		OptInfo opt =  jsonMap.getObject(skey, OptInfo.class);
	    		System.out.println(opt.getOptName());
	    	}   
		} catch (IOException e) {
			return;
		}
    }

上面的 toOptInfo 是不报错的，toOptInfo2 会报错，不知道什么原因。

**Comment by wenshao** [comment]
不等价的，上面这种是parse，下面这种类型转换

**Comment by codefan** [comment]
非常感谢 wenshao及时的回复。 那下面这种报错算不算问题呢？还是本来就不能这么使用？
