### ISSUE TITLE
使用SpringMVC3.2.17集成报错？

### ISSUE THREAD

**Issue by 805728578** [alibaba/fastjson#768]
2016-08-11 18:21:09|ERROR| [ContextLoader-->initWebApplicationContext] --- Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter#1' defined in class path resource [spring-mvc.xml]: Cannot create inner bean 'com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter#550b4521' of type [com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter] while setting bean property 'messageConverters' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter#550b4521' defined in class path resource [spring-mvc.xml]: Cannot create inner bean 'com.alibaba.fastjson.support.config.FastJsonConfig#3b7a3860' of type [com.alibaba.fastjson.support.config.FastJsonConfig] while setting bean property 'fastJsonConfig'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.fastjson.support.config.FastJsonConfig#3b7a3860' defined in class path resource [spring-mvc.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.alibaba.fastjson.support.config.FastJsonConfig]: Constructor threw exception; nested exception is java.lang.NoSuchFieldError: UTF8
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:287)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:122)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveManagedList(BeanDefinitionValueResolver.java:358)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:157)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1419)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:636)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:938)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4994)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5492)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1247)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1897)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter#550b4521' defined in class path resource [spring-mvc.xml]: Cannot create inner bean 'com.alibaba.fastjson.support.config.FastJsonConfig#3b7a3860' of type [com.alibaba.fastjson.support.config.FastJsonConfig] while setting bean property 'fastJsonConfig'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.fastjson.support.config.FastJsonConfig#3b7a3860' defined in class path resource [spring-mvc.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.alibaba.fastjson.support.config.FastJsonConfig]: Constructor threw exception; nested exception is java.lang.NoSuchFieldError: UTF8
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:287)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:122)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1419)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:276)
	... 30 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.fastjson.support.config.FastJsonConfig#3b7a3860' defined in class path resource [spring-mvc.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.alibaba.fastjson.support.config.FastJsonConfig]: Constructor threw exception; nested exception is java.lang.NoSuchFieldError: UTF8
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1039)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:985)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:487)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:276)
	... 36 more
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.alibaba.fastjson.support.config.FastJsonConfig]: Constructor threw exception; nested exception is java.lang.NoSuchFieldError: UTF8
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1032)
	... 40 more
Caused by: java.lang.NoSuchFieldError: UTF8
	at com.alibaba.fastjson.support.config.FastJsonConfig.<init>(FastJsonConfig.java:59)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
	... 42 more

**Comment by 805728578** [comment]
在SpringMVC4.3.2没有问题，在SpringMVC3.2.17中报错

**Comment by 805728578** [comment]
![fastjson](https://cloud.githubusercontent.com/assets/9798724/17586235/0698dda2-5ff3-11e6-80db-f164c2683056.png)

**Comment by 805728578** [comment]
public FastJsonConfig() {
		
		this.charset = IOUtils.UTF8;
		
		this.serializeConfig = SerializeConfig.getGlobalInstance();
		this.parserConfig = ParserConfig.getGlobalInstance();
		
		this.serializerFeatures = new SerializerFeature[0];
		this.serializeFilters = new SerializeFilter[0];
		this.features = new Feature[0];
	}

in error line:
this.charset = IOUtils.UTF8;

**Comment by wenshao** [comment]
@VictorZeng 帮忙看看

**Comment by VictorZeng** [comment]
@805728578 IOUtils中的UTF8是从fastjson 1.2.10版本就开始有了 确认一下是否存在多个fastjson版本

**Comment by 805728578** [comment]
@VictorZeng 没有，项目只有一个版本1.2.15

**Comment by VictorZeng** [comment]
@805728578 请提供一下测试用例

**Comment by 805728578** [comment]
@VictorZeng 项目配置后启动时报错

**Comment by VictorZeng** [comment]
@805728578 能否提供完整的mock testcase 包括配置文件等等 这个问题实在不好定位
