### ISSUE TITLE
1.1.41版本对含有特殊字符$ref的json串如何解析？

### ISSUE THREAD

**Issue by ruobing2009** [alibaba/fastjson#786]
使用fastjson 1.1.41版本如下简单的json
````XML
{
    "properties": {
        "type": {
            "items": {
                "allOf": [
                    {
                        "$ref": "title",
                        "required": [
                            "iconImg"
                        ]
                    }
                ]
            }
        }
    }
}
````
         String jsonTest = "{\"properties\":{\"type\":{\"items\":{\"allOf\":[{\"$ref\":\"title\",\"required\":[\"iconImg\"]}]}}}}";

**目的：**
  * 通过Object object = JSON.parseObject(jsonTest);解析该Json串，获取$ref-->对应title

**结果：**程序报错

````
Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:372)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1076)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:418)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:442)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:442)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:442)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1241)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1210)
	at com.alibaba.fastjson.JSON.parse(JSON.java:109)
	at com.alibaba.fastjson.JSON.parse(JSON.java:100)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:171)
	at testaa.main(testaa.java:12)
````

想要关闭循环引用，使用
````
Object object = JSON.parseObject(jsonTest,Feature.DisableCircularReferenceDetect);

程序同样报错
````
请问怎么才能正确解析出$ref-->对应title  的对象呢？

**Comment by githublaohu** [comment]
String jsonTest = "{\"properties\":{\"type\":{\"items\":{\"allOf\":[{\"$ref\":\"title\",\"required\":[\"iconImg\"]}]}}}}";
        JSONObject object = JSON.parseObject(jsonTest, Feature.DisableSpecialKeyDetect);
        System.out.println( object.get( "properties"));

{"type":{"items":{"allOf":[{"$ref":"title","required":["iconImg"]}]}}}

版本 1.2.7,没有问题。

**Comment by wenshao** [comment]
升级到最新版本吧
http://repo1.maven.org/maven2/com/alibaba/fastjson/1.2.16/

**Comment by ruobing2009** [comment]
果然可以了，谢谢

**Comment by wenshao** [comment]
既然好了，我就关闭issue啦
