### ISSUE TITLE
fastjson 1.2.16版本高并发场景下抛出java.lang.NumberFormatException

### ISSUE THREAD

**Issue by jackiehff** [alibaba/fastjson#788]
用Jmeter对HTTP接口做性能测试时，fastjson 抛出java.lang.NumberFormatException：

`java.lang.NumberFormatException: -
	at com.alibaba.fastjson.parser.JSONLexerBase.integerValue(JSONLexerBase.java:478)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1304)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1268)
	at com.alibaba.fastjson.JSON.parse(JSON.java:137)
	at com.alibaba.fastjson.JSON.parse(JSON.java:128)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:201)`

性能测试的线程数是150, 循环次数是1000次
FastJson的版本是1.2.16版本

**Comment by wenshao** [comment]
不应该啊，这个点上应该没有并发问题，会不会是输入的JSON文本格式错了？

**Comment by jackiehff** [comment]
单个请求的话数据解析都挺正常的

**Comment by jackiehff** [comment]
@wenshao 单个请求的话数据解析都挺正常的

**Comment by wenshao** [comment]
会不会是上层框架有并发问题？
