### ISSUE TITLE
jsonpath 数组解析 抛出IllegalArgumentException异常

### ISSUE THREAD

**Issue by Jingtian1989** [alibaba/fastjson#799]
jsonpath定义："$.array[0:-1].bizData"  当array不存在时，抛出如下异常：
java.lang.IllegalArgumentException: Illegal Capacity: -1
	at java.util.ArrayList.<init>(ArrayList.java:156)
	at com.alibaba.fastjson.JSONPath$RangeSegement.eval(JSONPath.java:1120)
	at com.alibaba.fastjson.JSONPath.eval(JSONPath.java:79)

更好的方式，不是应该直接返回null吗？

fastjson版本：1.2.7

**Comment by wenshao** [comment]
问题修复，等下一个版本1.2.17吧
