### ISSUE TITLE
1.2.5版本，bean转JSON时arraylist出错， 怎么解

### ISSUE THREAD

**Issue by xysoko** [alibaba/fastjson#832]
java.lang.IndexOutOfBoundsException: Index: 0, Size: -1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at Serializer_2.write1(Unknown Source)
	at Serializer_2.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:361)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:393)
	at com.game.player.Manager.PlayerManager.makeRoleBeanByPlayer(PlayerManager.java:358)
	at com.game.player.Manager.PlayerManager.timingSavePlayer(PlayerManager.java:1060)
	at com.game.Server.Timer.ServerHeartTimer.action(ServerHeartTimer.java:40)
	at game.core.net.thread.ServerThread.run(ServerThread.java:97)

**Comment by wenshao** [comment]
升级到最新版本就好了
http://repo1.maven.org/maven2/com/alibaba/fastjson/1.2.17/
