### ISSUE TITLE
fastjson读取json文件异常

### ISSUE THREAD

**Issue by wzlee** [alibaba/fastjson#836]
json文件内容：
```json
{
  "nickname":"leoops",
  "openid":"12e1f31a2d8bae8395c424752be18e02"
}
读取的代码：
```java
public static void main(String[] args) throws FileNotFoundException {
		JSONReader reader = new JSONReader(new FileReader("/Users/leo/Documents/test.json"));
		reader.startObject();
		while (reader.hasNext()) {
			Map<String, Object> map = new HashMap<String, Object>();
			reader.readObject(map);
			System.out.println(JSON.toJSONString(map));
		}
		reader.endObject();
		reader.close();
	}

异常信息：
```exception
Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error, expect {, actual string, 
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:219)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:1051)
	at com.alibaba.fastjson.JSONReader.readObject(JSONReader.java:282)
	at com.example.DemoApplicationTests.main(DemoApplicationTests.java:30)

**Comment by dexteraquatic** [comment]
文件第一个字符不是'{'
