### ISSUE TITLE
SpringMVC环境下，JSON反序列化为对象时日期字段出错

### ISSUE THREAD

**Issue by lifeixiang027** [alibaba/fastjson#837]
1、配置如下：

	<bean id="fastJsonConfig" class="com.alibaba.fastjson.support.config.FastJsonConfig">
		<property name="charset" value="UTF-8" />
		<property name="dateFormat" value="yyyy/MM/dd HH:mm" />
	</bean>
	<mvc:annotation-driven>
		<mvc:message-converters>
			<bean class="com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter4">
				
				<property name="supportedMediaTypes">
					<list>
						<value>application/json</value>
						<value>text/xml</value>
						<value>text/html</value>
					</list>
				</property>
				
				<property name="fastJsonConfig" ref="fastJsonConfig" />
			</bean>
		</mvc:message-converters>
	</mvc:annotation-driven>

2、错误信息

> java.lang.NumberFormatException: For input string: "2016/09/22 16:55"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at com.alibaba.fastjson.parser.deserializer.SqlDateDeserializer.castTimestamp(SqlDateDeserializer.java:115)
	at com.alibaba.fastjson.parser.deserializer.SqlDateDeserializer.cast(SqlDateDeserializer.java:31)
	at com.alibaba.fastjson.parser.deserializer.AbstractDateDeserializer.deserialze(AbstractDateDeserializer.java:142)
	at com.alibaba.fastjson.parser.deserializer.AbstractDateDeserializer.deserialze(AbstractDateDeserializer.java:19)
	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:68)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:543)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:189)
	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:59)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:543)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:189)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:185)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:614)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:339)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:307)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:270)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:370)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:452)
	at com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter4.read(FastJsonHttpMessageConverter4.java:71)

3、在Java对象中增加JSONField注解错误一样

	@JSONField(format = "yyyy/MM/dd HH:mm")
	private Timestamp modifyStamp;

4、查看FastJsonHttpMessageConverter4源码，FastJsonConfig中配置的dateFormat只影响序列化方法，不影响反序列化方法

    @Override
    public Object read(Type type, //
                       Class<?> contextClass, //
                       HttpInputMessage inputMessage //
    ) throws IOException, HttpMessageNotReadableException {
        InputStream in = inputMessage.getBody();
        return JSON.parseObject(in, fastJsonConfig.getCharset(), type, fastJsonConfig.getFeatures());
    }

    @Override
    protected void writeInternal(Object obj, //
                                 Type type, //
                                 HttpOutputMessage outputMessage //
    ) throws IOException, HttpMessageNotWritableException {

        HttpHeaders headers = outputMessage.getHeaders();
        ByteArrayOutputStream outnew = new ByteArrayOutputStream();
        int len = JSON.writeJSONString(outnew, //
                fastJsonConfig.getCharset(), //
                obj, //
                fastJsonConfig.getSerializeConfig(), //
                fastJsonConfig.getSerializeFilters(), //
                fastJsonConfig.getDateFormat(), //
                JSON.DEFAULT_GENERATE_FEATURE, //
                fastJsonConfig.getSerializerFeatures());
        headers.setContentLength(len);
        OutputStream out = outputMessage.getBody();
        outnew.writeTo(out);
        outnew.close();
    }

请问在不修改 JSON.DEFFAULT_DATE_FORMAT的情况下，可以通过FastJsonConfig或注解设置反序列化时的日期格式吗？

**Comment by lifeixiang027** [comment]
@wenshao

**Comment by lifeixiang027** [comment]
@wenshao 请问这个问题是我使用方法不对还是其他原因？谢谢!

**Comment by lifeixiang027** [comment]
关闭问题，已换用其他工具。
