### ISSUE TITLE
颜文字转法

### ISSUE THREAD

**Issue by nei10u** [alibaba/fastjson#877]
String string = "{\"description\":\"\\(^o^)/\"}";
JSONObject json = JSONObject.parseObject(string);

Feature应该用哪个？

Exception in thread "main" com.alibaba.fastjson.JSONException: unclosed string : (
	at com.alibaba.fastjson.parser.JSONLexerBase.scanString(JSONLexerBase.java:967)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:424)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1298)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1264)
	at com.alibaba.fastjson.JSON.parse(JSON.java:125)
	at com.alibaba.fastjson.JSON.parse(JSON.java:181)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:185)

**Comment by nei10u** [comment]
String string = "{\"description\":\"\\\\(^o^)/\"}";
JSONObject json = JSON.parseObject(string);
System.out.println(JSONObject.toJSONString(json).replace("\\\\","\\"));

{"description":"\(^o^)/"}

这种方式感觉不优雅。。。

**Comment by githublaohu** [comment]
建议的方式。是在前段转义，然后在进行传输。
