### ISSUE TITLE
JSONArray不能转换为JSONObject异常

### ISSUE THREAD

**Issue by xuesong123** [alibaba/fastjson#914]
问题描述：
版本： 1.2.12
原始数据如下：
[
  {
    "a": [
      {
        "b": 200,
        "p": [
          {
            "dd": 1,
            "ee": 200.00,
            "ff": 200.00,
            "gg": [
            ]
          }
        ]
      }
    ]
  }
]
调用过程： JSON.parseObject(json);
异常信息：
Exception in thread "main" java.lang.ClassCastException: com.alibaba.fastjson.JSONArray cannot be cast to com.alibaba.fastjson.JSONObject
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:194)
        at test.JSONTest.test(JSONTest.java:85)

**Comment by abnerbos** [comment]
你给的json串是数组呢，要用 JSON.parseArray 转换成数组来获取

**Comment by xuesong123** [comment]
是我搞错了
