### ISSUE TITLE
1.2.21反序列泛型时报java.lang.ClassCastException，在1.2.12中却不报错

### ISSUE THREAD

**Issue by dengyj3** [alibaba/fastjson#937]
1、自定义泛型类（Out类中带泛型类型T）：
`public class Out<T> {
	private T outPara;
	public void setOutPara(T t) {
		outPara = t;
	}
	public T getOutPara() {
		return outPara;
	}
	public Out() {
	}
	public Out(T t) {
		setOutPara(t);
	}
}`
2、对象类：
`public class Info {
	private String name;
	private int id;
	private String content;
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
}`
3、测试代码：
`public class JsonTest {
	public static void main(String[] args) {
		Info info = new Info();
		info.setId(0);
		info.setName("user");
		info.setContent("info");
		Out<Info> out = new Out<Info>(info);
		String jString = JSON.toJSONString(out);
		System.out.println(jString);
		
		Out<Info> out1 = returnOut(jString, Info.class);
		System.out.println(out1);
               Info info2 = out1.getOutPara();
		System.out.println(info2.getName());
	}
	public static <T> Out<T> returnOut(String jsonStr, Class<T> c2){
		Out<T> out = JSON.parseObject(jsonStr, new TypeReference<Out<T>>(c2){});
		return out;
	}
}`
4、报错信息(1.2.21版本下执行结果)：
{"outPara":{"content":"info","id":0,"name":"user"}}
Exception in thread "main" java.lang.ClassCastException: fastjson.test.Info cannot be cast to fastjson.test.Out
	at fastjson.test.JsonTest.returnOut(JsonTest.java:21)
	at fastjson.test.JsonTest.main(JsonTest.java:17)
5、1.2.12版本下执行结果：
{"outPara":{"content":"info","id":0,"name":"user"}}
fastjson.test.Out@433a87a0
user
请问1.2.21和1.1.12 在泛型类的反序列化上有什么差异？

**Comment by wuwen5** [comment]
目前使用这种方式是ok的
```Java
Out<Info> out = JSON.parseObject(jString, new TypeReference<Out<Info>>(){});
```

**Comment by dengyj3** [comment]
@wuwen5 ,这种方式是可以获取到，但是可能不符合我的场景，我的场景下，Info是通过反射获取到的，需要传个参数进去才能知道是Info类，就像1.2.12版本那样，这样显式的我无法通过反射传入Info类型
Out<Info> out = JSON.parseObject(jString, new TypeReference<Out<Info>>(){});

**Comment by wuwen5** [comment]
@dengyj3  这个问题是1.2.18版本 修复内存占用问题引入的.（1.2.17可以使用）

建议不要 使用```new TypeReference<Out<T>>(c2){}```每次```new```的写法，可以自己先弄个map缓存下，不然fastjson内部的全局```ParserConfig```中的```IdentityHashMap```会撑爆得.（见 #849）

这个问题我已提交了pull request，在等@wenshao审核.

**Comment by wuwen5** [comment]
@dengyj3  这个问题已经修复，请使用1.2.22版本。
性能有很大的提升，针对这个例子做了100万次循环反序列化，速度提升百倍。
