### ISSUE TITLE
springmvc请求报错？

### ISSUE THREAD

**Issue by kervin521** [alibaba/fastjson#962]
@RequestMapping("saveOrUpdateInforelease")
  public @ResponseBody Object saveOrUpdateInforelease(@RequestParam(required=false)MultipartFile file,String imgs,@RequestParam(defaultValue = "0") long officeId) throws Exception {
..................
}

@RequestParam(required=false)MultipartFile file由于未上传文件而报错，但是required=false不上传文件不应该报错

**Comment by kervin521** [comment]
14:11:42,815 INFO  [STDOUT] 4)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:194)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:296)

**Comment by CharkeyQK** [comment]
详细的错误给出来看看
