### ISSUE TITLE
v1.2.7：JSON.toJSONString() 方法在参数为net.sf.JSONObject并且其中包含null值的时候会抛空指针异常

### ISSUE THREAD

**Issue by Dijkspicy** [alibaba/fastjson#997]
```code
public static void main(String[] args) {
        net.sf.JSONObject map = JSONObject.fromObject("{\"test\":null}");
        System.out.println(JSON.toJSONString(map));
    }
```
```output
Exception in thread "main" net.sf.json.JSONException: Object is null
	at net.sf.json.JSONNull.isEmpty(JSONNull.java:69)
	at Serializer_1.write1(Unknown Source)
	at Serializer_1.write(Unknown Source)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:189)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:374)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:394)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:382)
	at com.huawei.cloudsop.decomp.core.common.InputAssignment.main(InputAssignment.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by wenshao** [comment]
已经支持，请用最新版1.2.24
