### ISSUE TITLE
FastJson针对Class反序列化，字符串信息不全导致出错。

### ISSUE THREAD

**Issue by xinghalo** [alibaba/fastjson#999]
```
public static void main(String[] args) {
        String json = "{\"a\":\"1\",\"b\":2}";
        ABC abc = JSON.parseObject(json,ABC.class, Feature.IgnoreNotMatch);
        System.out.println(abc);
    }
    class ABC {
        private String a;
        private String b;
        private String c;

        public String getA() {
            return a;
        }

        public void setA(String a) {
            this.a = a;
        }

        public String getB() {
            return b;
        }

        public void setB(String b) {
            this.b = b;
        }

        public String getC() {
            return c;
        }

        public void setC(String c) {
            this.c = c;
        }
    }
```

代码如上：
```
Exception in thread "main" com.alibaba.fastjson.JSONException: create instance error, class xxxxx.OrderInformation$ABC
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.createInstance(JavaBeanDeserializer.java:116)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:323)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:135)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:250)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:226)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:185)
	at com.tgou.market.orderbasic.bean.OrderInformation.main(OrderInformation.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.NullPointerException
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.createInstance(JavaBeanDeserializer.java:113)
	... 12 more
```
请问有什么解决办法，能忽略Class类中在字符串不存在的字段。

**Comment by xinghalo** [comment]
我也是内部类的原因导致的。
